[1단계 - 음식점 목록] 파인(임낭경) 미션 제출합니다.
woowacourse/javascript-lunch pull request #10
Opened 2023-03-03 07:56 UTC by nangkyeonglim

작성중...

2023-03-05 13:41 UTC, Puterism requested changes
파인 안녕하세요! 이번 미션의 리뷰어를 맡은 체프라고 합니다. 만나서 반갑습니다 😄 
전체적으로 깔끔한 구조로 코드를 작성하신 것 같아요! 테스트 코드도 적절하게 잘 작성하신 것 같구요. 크게 떠오르는 피드백이 없었어요.
기타 피드백은 각 코드 라인마다 남겨두었으니 확인 부탁드릴게요!

--- 

> 위에 저희가 나눈 컴포넌트의 기준에 대해서 말씀드렸는데, 여기서 컴포넌트를 더 나눌 수 있을지,, 나눈다면 그 컴포넌트들은 어차피 재사용이 되지 않는 컴포넌트일텐데 더 나누는 것이 적합한지 궁금합니다.

컴포넌트를 나누는 기준에 따라서 달라질 것 같습니다. 더 작은 단위로 추가로 나누려면 버튼과 같은 컴포넌트로 나눌 수는 있을 것 같습니다. 하지만 말씀하신 기준에 따르면 동적으로 렌더되는 요소는 아니니 적합하다고 보긴 힘들겠네요.
저는 지금도 나쁘지 않은 것 같습니다 👍 

> step2에서 음식점 추가 모달 외에 음식점 상세정보 모달이 추가되는데, 이 경우 Modal을 custom element로 만든 다음에 이를 재사용해서 두 가지 모달을 재사용할 수 있을까요? 이런 경우에 태그의 id나 class, 그리고 안에 들어가는 내용이 다르니까 태그들 등이 필요한데 vanilla JS로 구현이 가능할지 궁금합니다.

모달을 재사용할 수 있도록 구현할 수 있는지에 대한 여부를 질문주신 걸까요? 모달은 안에 들어가는 내용이 달라도 항상 재사용하기 좋은 컴포넌트라고 생각합니다. 충분히 구현 가능하지 않을까 생각합니다.

> 렌더링 테스트에 현재 getByText를 해서 단지 그 컴포넌트가 그려져있는지 여부만 테스트하고 있는데 렌더링 테스트에서 이것만 하면 충분한지 궁금합니다!

테스트 코드를 작성하는 기준에 따라서 다르겠지만 저는 getByText로도 충분하지 않을까 생각합니다. 수행하신 미션 같은 경우는 컨텐츠가 중요하니까 컴포넌트에 그려지는 텍스트만 테스트해도 충분하지 않을까 생각해요.

2023-03-05 13:41 UTC, Puterism commented on src/components/RestaurantList.js
> +customElements.define(
Custom Elements를 사용하셨는데요. 소감이 어떠셨는지 궁금합니다.

2023-03-05 13:41 UTC, Puterism commented on src/domain/restaurants.ts
> +    return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
이중 삼항 연산자는 코드의 가독성을 많이 떨어뜨린다고 생각해요. if문을 적절하게 사용해주시는 것이 어떨까요?

2023-03-05 13:41 UTC, Puterism commented on src/domain/restaurants.ts
> +    this.list = getLocalStorage('restaurants') ?? sampleRestaurants;
중요한 콘텐츠 데이터를 localStorage에서 불러오는 만큼 key도 상수화를 진행해주시면 어떨까요?

2023-03-05 13:41 UTC, Puterism commented on src/LunchMenuApp.js
> +      'registerRestaurant',
커스텀 이벤트도 사용하셨군요 👍 소감이 어떠셨나요?

2023-03-06 08:48 UTC, nangkyeonglim reviewed
안녕하세요 체프😊 
질문에 대한 답변 주셔서 감사합니다. 코멘트는 모두 반영하여 커밋하였습니다! 
각 코멘트마다 답글을 달았는데 확인해주시면 감사하겠습니다 :)

2023-03-06 08:48 UTC, nangkyeonglim commented on src/LunchMenuApp.js
> +      'registerRestaurant',
커스텀 이벤트를 사용하지 않았을 때에는, App 내에서 각 컴포넌트의 element에 이벤트 리스너를 추가해주거나, 각 컴포넌트에게 이벤트 리스너 함수를 넘겨서 bind해주는 식으로 사용을 해야했습니다. 

app에서 레스토랑이 등록되었다는 이벤트(`registerRestaurant`)가 발생되었다는 것만 알면 submit시에 restaurants의 정보만를 받아서 도메인 로직을 이용하기 때문에 form의 세부 마크업을 신경쓸 필요가 없다는 점이 좋았던 것 같습니다.

2023-03-06 08:48 UTC, nangkyeonglim commented on src/domain/restaurants.ts
> +interface Restaurants {
사실 처음에 `type`만 사용하다가 객체나 클래스를 정의할 때에는 interface를 주로 사용한다는 것을 보고 `Restaurants`에는 적용했지만 `Restaurant`에는 적용을 하지 못했네요.🥲 통일성이 있게 수정하였습니다!

객체나 클래스에 interface를 사용했을 때에 다음과 같은 점 때문에 interface를 사용하려고 했습니다.
1. **상속** 시 type은 `&`, interface는 `extends`키워드를 사용하기 때문에 interface가 좀 더 직관적이다. 
2. property확장 시 interface가 더 유연하다. interface는 타입 중복 선언이 가능하고, 중복 선언 시 extends한 것과 동일하게 동작
```typescript
type Restaurant = {}
}
// 타입 중복 선언 불가
type Restaurant = {}

interface Restaurant {}
// 타입 중복 선언 가능
interface Restaurant {}
```

2023-03-06 08:48 UTC, nangkyeonglim commented on src/domain/restaurants.ts
> +    this.list = getLocalStorage('restaurants') ?? sampleRestaurants;
restaurants key를 상수화해서 get, set localStorage 모두에서 사용하도록 리팩토링하였습니다!

2023-03-06 13:56 UTC, Puterism commented on src/utils/localStorage.js
> +  return item ? JSON.parse(item) : null;
현재는 큰 이상이 없을 것 같다는 데에 동의합니다. 하지만 혹시 모르는 경우가 언제든지 존재할 수 있다는 점을 인지해주셨으면 좋겠습니다. 유지보수가 계속 되고 코드에 변경이 계속 일어난다면 언제든지 위험성은 존재한다고 생각해요.
제가 했던 경험으로는 JSON.parse가 실행되는 데이터를 fetch해오는 서버에서 데이터 형식를 다르게 내려주는 바람에 JSON.parse 구문에서 에러가 발생해서 앱 전체가 깨져버리는 문제가 발생한 적이 있었어요.

2023-03-06 13:59 UTC, Puterism approved these changes
빠르게 피드백 적용해주셔서 감사드립니다. 다음 단계도 화이팅입니다 💪

2023-03-06 13:59 UTC, merged