Step1
woowacourse/javascript-lunch pull request #107
Opened 2024-03-08 07:13 UTC by soi-ha

안녕하세요, 카일!
이번 **점심 뭐 먹지?** 미션 피드백 잘 부탁드립니다 :)

### [🖥️ 점심 뭐 먹지? 소하 페이지 바로가기](https://soi-ha.github.io/javascript-lunch/dist/)

## 피드백 전, 전달 사항

- 기본 제공해주는 templates 폴더를 사용하지 않고, 페어와 합의하여 직접 UI를 구현하였습니다.
- 저는 이번 미션을 통해 타입스크립트를 처음 사용해보았습니다. 따라서 이번 미션은 페어의 많은 도움으로 학습하며 구현할 수 있었습니다. 이점 양해 부탁드립니다!
- README에 기능 구현 영상 및 폴더 구조 설명이 존재합니다. 참고 부탁드립니다.

## 질문 사항

- li 태그를 button 태그로 감싸는 것이 좋을까요?
    
    restaurant를 클릭 했을 때, 해당 음식점에 대한 정보를 모여주는 모달을 띄우는 기능이 2단계에 존재합니다.  그래서 li 자체에 click 이벤트를 주는 방법이 있지만 li 아래를 button으로 감싸는게 스크린 리더기를 통해서 보는 사용자들을 위해서 좋을 것  같다는 생각을 했습니다. button으로 감싸는 방법에 대한 리뷰어님의 생각이 궁금합니다.
    
    ```html
    <li class="restaurant">            
    				<button>
                  <div class="restaurant__icon">
                    <div class="icon-western"></div>
                  </div>
                  <div class="restaurant__contents">
                    <h3 class="restaurant__contents__title">타이틀</h3>
                    <p class="restaurant__contents__distance">거리</p>
                    <p class="restaurant__contents__explanation">설명</p>
                  </div>
                </button>
    </li>
    ```
    
- url 정규표현식 사용?
    
    url 유효성 검사에를 현재는 http/https만 검사하고 있는데, 프로토콜 이후에 들어오는 부분에 대한 유효성 검사도 진행하고 싶어서 찾아보다가 url 정규표현식을 알게 되었습니다. 
    
    ```jsx
    /^(https?):\/\/(?:www\.)?[a-zA-Z0-9-]+\.[a-zA-Z]{2,}(?:\/[^\s]*)?$/
    ```
    
    url 정규표현식이 위와 같이 매우 긴데, 이게 오히려 코드의 가독성이 좋지 않을 것이라고 판단하여 일단은 프로토콜 검사만 진행했습니다. 해당 url 정규표현식을 사용해도 좋을까요? 혹은 정규표현식 이외에 url 유효성 검사를 할 수 있는 다른 좋은 방법이 있을지 의견을 묻고 싶습니다.
    
- 커스텀 웹 컴포넌트안에  커스텀 웹 컴포넌트를 자식 요소로 두는 법:
    
    A라는 커스텀 웹 컴포넌트 안에 B라는 커스텀 웹포넌트를 자식 요소로 두고 싶었습니다.
    그냥 A 컴포넌트 태그 안에 B 컴포넌트 태그를 넣으면 B 컴포넌트가 출력되지 않는 것을 확인했습니다.
    
    그래서 저희는 `shadowDom`과 `slot`을 사용하여 A 컴포넌트 태그 안에 B 컴포넌트 태그를 넣는 방법을 사용했습니다.  
    
    하지만, 이 방법을 사용하면서 불편한 점을 느끼게 되었습니다. shadowDom을 통해 생성된 태그는 css 파일에 스타일을 입력하면 적용되지 않고, 해당 태그를 선언한 파일에서 style태그를 innerHTML을 해야지만 스타일 적용이 되는 번거로움이 발생했습니다.
    또한, shadowDom의 자식 요소를 찾을 때에도 shadowRoot를 사용해야 지만 찾을 수 있었습니다.
    
    shadowDom을 사용하는 것이 그닥 좋지 않다고 느꼈는데, 웹 컴포넌트 안에 다른 웹 컴포넌트를 넣는 방법은 shadowDom을 사용하는 것 밖에 없을까요?
    
- interface와 type alias 혼합하여 사용?
    
    typescript는 interface 혹은 type alias 둘 중 하나만 일관되게 사용하는 것이 좋다고 들었습니다. 
    type alias 보다는 interface를 사용하는 것이 공식 문서에서 더 선호하는데, union 타입일 시에는 type alias가 더 효과적이라고 알고 있습니다. 
    이럴 경우에는 interface와 type alias가 혼합되어 사용하게 될 수 밖에 없을 것 같은데, interface와 type alias를 혼합해서 사용하는 것이 좋을까요? 아니면 그래도 일관되게 하나로 사용하는 것이 좋을까요?

2024-03-09 09:32 UTC, GwangYeol-Im requested changes
안녕하세요 소하, 기간이 꽤 짧았을 텐데 많은 코드를 작성해주셨네요~ 다만 수많은 file changed에 비해 실제 확인해야할 코드는 절반 정도였던 거 같아 PR을 올려주시기 전에 해당 부분에 대한 정리를 해주셨으면 어떨까 싶었습니다..! 세부 코멘트 확인 부탁드리고 질문에 대한 답변 남기고 마무리 할게요~

> li 태그를 button 태그로 감싸는 것이 좋을까요?

button 내부에 text만 들어가야 하는 것은 아니기 때문에 전체가 clickable한 영역이라면, 말씀대로 시맨틱을 고려해서 작성해주는 것도 괜찮아 보입니다. 다만, UI를 작성하면서 다양한 상황에 마주할 수 있기 때문에 (e.g. 접근성보다 일단 기능이 돌아가는 것에 초점을 둔다거나, 이미 구현된 디자인 시스템에서는 button으로 처리가 되어있지 않다거나) 상황마다 trade off를 고려하여 유연한 선택을 해주시면 되겠습니다.

> url 정규표현식 사용?

정규 표현식이라는 방법론 자체는, 좀 더 low한 level에서 문자열을 파싱하고 가공할 수 있기 때문에 성능 상의 이점을 도모할 수 있습니다. 따라서 낮은 가독성의 이유가, 코드를 복잡하게 짜서인지 혹은 아직 그 문법에 익숙하기 않기 때문인지는 구분할 필요가 있어 보여요. 추후에 정규식에 대한 학습을 해보시면서 현재 예시로 올려주신 정규식보다 좀 더 간결한 정규식으로 작성해보는 방식도 고려해보면 어떨까 싶습니다.

> 커스텀 웹 컴포넌트안에 커스텀 웹 컴포넌트를 자식 요소로 두는 법:

이건 검색으로 충분히 찾을 수 있을 듯 하여 스킵하겠습니다!

> interface와 type alias 혼합하여 사용?

- typescript는 interface 혹은 type alias 둘 중 하나만 일관되게 사용하는 것이 좋다고 들었습니다. -> 어떤 이유 때문에 일관적으로 사용하는 게 좋은 건가요?
- type alias 보다는 interface를 사용하는 것이 공식 문서에서 더 선호하는데 -> 해당 부분 발췌 가능할까요?

2024-03-09 09:32 UTC, GwangYeol-Im commented on src/components/AddBtn/index.ts
`AddBtn`이라는 단순 UI를 표현하는 데 사용할 것 같은 컴포넌트가 `handleClickToAddStore`라는 특정 도메인의 관심사를 알고 있는 것이 부자연스러워 보입니다. 사용 범위와 코드가 매칭되어야 할 것 같아요.

2024-03-09 09:32 UTC, GwangYeol-Im commented on src/components/CategoryIcon/index.ts
> +class CategoryIcon extends HTMLElement {
아이콘, 버튼, 셀렉트, 인풋 등 단순 UI를 표현하는 계층의 컴포넌트들은 되도록 도메인의 정보를 모르도록 작성하는 것이 높은 재사용성을 이끌어낼 수 있습니다. MUI나 radix같은 UI를 위한 라이브러리에서 어떤 식으로 이름과 역할을 부여하는지 찾아보시면 좋을 듯 해요!

2024-03-09 09:32 UTC, GwangYeol-Im commented on src/components/CustomInput/index.ts
> +class CustomInput extends HTMLElement {
기존의 html tag가 보여주는 UI를 앱에 맞게 변형한 모든 컴포넌트가 커스텀 컴포넌트이기 때문에, `Custom`이라는 별도의 이름은 없어도 괜찮을 것 같아요.

2024-03-09 09:32 UTC, GwangYeol-Im commented on src/components/DefaultBtn/index.ts
> +class AddBtn extends HTMLElement {
파일명과 맞춰주세요!

2024-03-09 09:32 UTC, GwangYeol-Im commented on src/components/DropBox/DropBoxInnerHtmlMaker.ts
> +  }
`html`을 반환한다는 것은 컴포넌트의 캡슐화 원칙과 다소 상이해 보이는데, 의도가 궁금합니다.

2024-03-09 09:32 UTC, GwangYeol-Im commented on src/constants/enum.ts
파일명을 `enum.ts`으로 두는 거보단 어떤 목적으로 사용하기 위한 코드를 모아둔 파일인지에 대한 의미가 담기면 좋겠습니다. 만일 이름이 명확하게 떠오르지 않는다면 코드 분리를 권장드려요~

2024-03-09 09:32 UTC, GwangYeol-Im commented on src/data/restaurantData.ts
> +export const INITIAL_RESTAURANT_DATA: RestaurantInfo[] = [
`initialData`가 필요한 이유가 무엇일까요? 사용성 측면에서 사용자가 앱에 초기 진입할 때에는 아무런 데이터가 없는 게 좋지 않을까요?

2024-03-09 09:32 UTC, GwangYeol-Im commented on src/data/restaurantData.ts
> +export const RESTAURANT_INFO_FOR_VALIDATE_TEST: RestaurantInfo = {
이 코드의 역할은 무엇인가요?

2024-03-10 13:02 UTC, soi-ha commented on dist/add-button.svg
이번 1단계 미션 작업을 저의 노트북에서 진행했습니다. 페어의 노트북에 dist 폴더를 보내기 위해서 .gitignore 파일에 `/dist`를 지우고 커밋했습니다. 그 이후에 `/dist` 폴더를 삭제했어야 했는데.. 저의 부주의로 같이 PR에 올리게 되었습니다…ㅜ

남겨주신 피드백에 답변하기 위해서 찾아보면서 알게 되었는데, 페어에게 `/dist`폴더를 굳이 보내주지 않아도 되었다는 사실을 새롭게 알게 되었습니다. 해당 폴더가 존재하지 않아도, 빌드를 진행하면 해당 폴더가 다시 생기더라구요..! 

따라서, PR을 보내는 브랜치에는 dist 폴더를 삭제해두었습니다.

2024-03-10 13:17 UTC, soi-ha commented on src/data/restaurantData.ts
> +export const RESTAURANT_INFO_FOR_VALIDATE_TEST: RestaurantInfo = {
음식점을 등록할때 url 유효성 검사를 위해 사용하는 데이터입니다.

유효성 검사를 진행하는 domains/Restaurant.ts 파일을 살펴 보시면 음식점 이름, 설명, url에 대해 유효성 검사를 진행하고 있습니다. 현재 개발한 서비스에서 이름과 설명은 html에서 올바른 값만 입력받도록 강제해두어서 유효성 검사가 필요하지 않게 되었습니다. 

하지만 url의 경우에는 프로토콜이 존재하는지 확인해야 합니다. url의 유효성 검사를 위해서는 이름과 설명 데이터 또한 같이 들어가야 Restaurant.ts에서 url 유효성 검사가 가능합니다.

따라서, url의 유효성 검사를 위해서 이름과 설명의 데이터를 임시로 만들어, FormTextField/index.ts에서 해당 데이터를 활용하여 유효성 검사를 진행합니다.

2024-03-10 13:45 UTC, soi-ha commented on src/types/storageKeyType.ts
> +export type StorageKey = keyof typeof StorageKeyEnum;
- 원래 StorageKey를 활용하기 위해서 우선 만들고 시작했다가, 개발을 진행하면서 해당 파일이 존재하던 것을 잊어버려.. 활용하지 못하게 되었습니다. 그래서 StorageKey가 아닌 전부 StorageKeyEnum으로 사용하게 되었습니다.  해당 부분은 StorageKey로 변경해 두도록 하겠습니다.
 - enum을 직접 사용하는 것 보다 key로 추출하여 사용하는 것이 유연성, 코드 간결성, 유지 관리에 더 좋다고 알고 있어서 key로 추출하여 사용하였습니다.
enum을 직접 타입으로 사용하게 된다면, enum의 값이 변경 되었을 때 수정해야 할 사항이 늘어나게 됩니다. 그러나 enum의 key를 추출하여 type으로 사용하게 된다면 수정사항의 최소한이 될 것입니다. type이 enum에서 key를 추출한 것이기 때문에 enum을 변경해도 type 코드는 변경되지 않을 것 입니다.

2024-03-10 13:56 UTC, soi-ha commented on src/types/addBtnType.ts
> +export type BtnType = 'submit' | 'reset' | 'button' | undefined;
카일이 말씀해주신 방법이 더 맞는 것 같습니다. undefined를 사용하는 곳에서 넣어주면 되겠다라는 생각을 당시에는 하지 못하고 BtnType에 같이 주게 되었습니다. BtnType 사용처에서 undefined를 주는 것이 더 맞는 것 같습니다. 수정하도록 하겠습니다!

2024-03-10 14:39 UTC, soi-ha commented on src/components/CategoryIcon/index.ts
> +class CategoryIcon extends HTMLElement {
말씀해주신 부분에 대해서 도메인의 정보를 모르도록 작성한다는 것에 대해서 감이 잡히지 않습니다..ㅜ

`iconMap`만 따로 분리를 하면 이것이 도메인의 정보를 모르도록 작성한 것일지.. 해당 CategoryIcon에서 어떤 부분이 도메인의 정보를 가지고 있는 잘 모르겠습니다..!

2024-03-10 14:41 UTC, soi-ha commented on src/components/DropBox/DropBoxInnerHtmlMaker.ts
> +  }
컴포넌트의 캡슐화 원칙에 대해 알지 못했어서.. 해당 부분은 더 공부 후에 수정하도록 하겠습니다..ㅜ!

2024-03-10 15:49 UTC, soi-ha commented
- typescript는 interface 혹은 type alias 둘 중 하나만 일관되게 사용하는 것이 좋다고 들었습니다. → 어떤 이유 때문에 일관적으로 사용하는 게 좋은 건가요?
    
    해당 질문에 대해서 제가 찾아보고 여쭤본 것이 아니라 전해 듣고 여쭤본 것이라. 답변을 하기 위해 찾아보았습니다. interface 혹은 type alias를 일관되게 사용하는 것이 좋은 이유는 코드 일관성을 유지하는 것이 좋기 때문이라고 합니다. 
    
    근데, 이 두개를 일관되게 사용하는 것이 좋다는 것이 해당 질문을 작성할 당시에는 프로젝트에서 모두 interface아니면 type alias 둘 중에 하나만 사용하는 것이 좋다! 라고 이해하고 질문했던 것입니다.
    
    하지만 제가 찾아보면서 그런 의미에서 둘 중에 하나를 사용하는 것이 좋다가 아니었다는 것을 알게 되었습니다. 둘 중에 일관되게 사용해야 한다는 것은 **같은 상황에서 동일한 방법으로 명명된 타입을 정의해 일관성을 유지**하라는 것이었습니다.
    
    카일의 역질문에 답변을 하면서 궁금증이 해결되었습니다! 감사합니다 :)
    
- type alias 보다는 interface를 사용하는 것이 공식 문서에서 더 선호하는데 -> 해당 부분 발췌 가능할까요?
    
    제가 공식 문서에서 찾은 것이 아니라 블로그의 글을 통해서 알게된 내용이라..  공식 문서를 찾기 위해 서칭을 하다가 알게 된 점이 있습니다.
    
    아마도 interface를 사용하는 것을 선호한다는 부분은 **두개 이상의 타입을 조합해야 할 때**에는 type alias에서 교차 타입을 사용하는 것 보다 interface에서 확장을 하는 것을 더 선호한다는 것이 아닐까..? 싶습니다.
    
    [Preferring Interfaces Over Intersections](https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections)

---
남겨주신 피드백을 최대한 반영해보려고 했지만, 타입스크립트를 처음하다 보니 공부를 같이 하면서 진행하여 속도가 나지 못해 일단 당장 반영이 가능한 부분에 대해서 수정하여 재PR 요청을 보냈습니다. 반영을 많이 못 한 것 같아서 아쉽지만.. 일단 저의 속도에 맞춰서 해 나가보도록 하겠습니다. 많이 느리겠지만 잘 부탁드립니다! :)

2024-03-12 09:01 UTC, GwangYeol-Im commented on src/data/restaurantData.ts
> +export const RESTAURANT_INFO_FOR_VALIDATE_TEST: RestaurantInfo = {
음.. 설명을 보고 해당 코드의 사용처를 모두 확인해보았는데, form input이 변경될 때 `Restaurant`의 인스턴스를 만들어 값의 유효성을 검사를 하는 점, 이를 위해 임의로 설정해둔 값을 넣어주는 흐름이 조금 부자연스러워보입니다.

결국 확인하려는 건 url의 정합성인 듯 한데 이를 위해 필요로 하는 코드가 너무 많지 않을까요?

2024-03-12 09:10 UTC, GwangYeol-Im approved these changes
안녕하세요 소하! 리뷰가 다소 늦어진 점 사과 드립니다 😂 코멘트 모두 확인한 뒤 추가 코멘트 남겨두었으니 확인 부탁드립니다!

type alias와 interface에 대해 추가적으로 남길 코멘트는 아래와 같습니다.

- 새로운 지식이나 의견을 받아들일 땐, 해당 의견에 대한 공식적인 근거를 확보해보시는 습관을 들여보시면 좋을 것 같아요. 이러한 습관이 추후 동일한 맥락에 대해 상대방과 토론을 하거나, 면접에서 나의 주장에 대한 근거를 들 때 도움이 될 수 있습니다.
- 저는 개인적으로 type alias과 interface 사이에 크게 선호되는 문법은 없다고 생각합니다. 대부분 비슷한 기능을 제공하며 차이가 있더라도 미미하여 팀 컨벤션에 따라 달라질 수 있다고 봐요. 다만, 두 문법이 비슷하다 하더라도 명시적으로 한 쪽에서는 되고 다른 쪽에서는 되지 않는 몇몇 기능들이 존재합니다. 이러한 경우에는 해당 기능을 제공해주는 문법을 사용하는 게 적합할 듯 싶습니다.

2024-03-12 09:11 UTC, merged