[1단계 - 음식점 목록] 에디(강상원) 미션 제출합니다.
woowacourse/javascript-lunch pull request #11
Opened 2023-03-03 08:00 UTC by ksone02

[배포페이지](https://ksone02.github.io/javascript-lunch/)
작성중

2023-03-04 17:04 UTC, lsw1164 requested changes
안녕하세요 에디, 리뷰어 리트입니다 :) 
플럭스 패턴을 도입하셨군요. 어떤 장단점을 느끼셨을까요?

웹컴포넌트를 사용하셨는데 모든 돔 요소를 document에서 접근하고 있어요. 

컴포넌트 간에 의존성이 없는 거 같지만 애매하게 다른 영역을 침범하는 컴포넌트가 보여서 오히려 더 위험하다고 느꼈어요.

예를 들면 헤더 컴포넌트는 모달 컴포넌트를 직접 참조하고 있지 않지만 
헤더컴포넌트에서 .modal 클래스를 가진 돔객체에 접근해서 modal--open이라는 classList를 추가하고 있죠.
이 로직이 헤더컴포넌트 코드에 직접 배치되면서 모달컴포넌트가 해야될 책임을 대신 수행하고 있어요.

어떻게 개선할 수 있을까요?


## 질문

> 1. 도메인 로직을 테스트 할 때 Store에 구현되어있는 localStorage의 존재 때문에 테스트를 진행할 수 없었습니다. 이런 경우 localStorage를 모킹해주나요? 아니면 로직 자체를 localStorage를 분리하는 다른 방향으로 작성해야 할까요?

일단, 두 방법 모두 테스트 가능할 거 같아요. 


이런 상황이라면 어떨까요? 가정해볼게요. 
로컬스토리지, 다양한 클라우드 스토리지들이 존재.
비용/경영 이슈로 어떤 스토리지를 사용할 지 주기적으로 바뀌고 있음.

이런 상황이라면 어떻게 구조를 짜야하고 테스트를 할 수 있을까요?



> 2. 상수(constants)에는 타입선언을 해줄 필요가 없나요?

상수가 string 타입 인지 number 타입 인지 명시적으로 표기하는 걸 말씀하시는 걸까요?   
개인의 선호나 사내 컨벤션인 거 같아요. 
- 타입 추론이 자동으로 되기 때문에 생략해도 괜찮다는 입장 
- 그래도 타입 선언을 명시적으로 하는 게 가독성이 좋다는 입장


> 3. RestaurantsComponent -> RestaurantComponent로 음식점 목록을 map을 돌며 attribute를 통해 data를 전달해주는데, 이런 경우 보통 음식점 객체를 전달해주나요? 아니면 아래 코드와 같이 프로퍼티들을 나누어 전달해주니요?
> 
> ```js
> rerender(restaurantList) {
>     const restaurants = restaurantList
>       .map((restaurant) => {
>         return `
>         <restaurant-element 
>           category="${restaurant.category}" 
>           name="${restaurant.name}" 
>           distance="${restaurant.distance}" 
>           description="${restaurant.description}" 
>           link="${restaurant.link}"
>         >
>       </restaurant-element>`;
>       })
>       .join("");
>     document.querySelector(".restaurant-list").innerHTML = restaurants;
>   }
> ```
> 

전달할 요소가 많아지면 객체로 전달하는 걸 선호합니다.  
함수 파라미터 개수가 늘어날 때 객체로 전달하는 거랑 비슷하죠.
그런데 웹컴포넌트는 객체를 전달하려면 직렬화해서 전달해야 돼서 추천하고 싶지 않네요


> 4. 엘리먼트의 스타일을 변경할 때 클래스(className)을 추가, 삭제하는 방식과 직접 element.style 로 접근하는 방식에는 무슨 차이가 있나요?

class 추가 방식을 잘 활용하면 CSS를 재활용 할 수 있죠.  
단점은 없을까요? 정리해보면 좋을 거 같네요.

2023-03-05 04:50 UTC, ksone02 commented on src/components/HeaderComponent.js
> +  }
이름에 혼동이 있을 것 같아요. 수정해두겠습니다!

2023-03-05 04:50 UTC, ksone02 commented on src/components/restaurant/RestaurantsComponent.js
> +class RestaurantsComponent extends CustomElement {
충분히 헷갈릴 수 있는 여지가 있어보입니다. 구분하기 쉽게 바꿔보겠습니다!

2023-03-05 04:51 UTC, ksone02 commented on src/components/restaurant/RestaurantsComponent.js
> +    document.querySelector(".restaurant-list").innerHTML = restaurants;
앗 그렇네요! 수정하겠습니다!

2023-03-05 05:08 UTC, ksone02 commented on src/domain/RestaurantsStore.ts
> +    );
불필요한 호출이 반복되어 서버에 부담이 될 수 있을 것 같습니다. 더 좋은 방법을 고민하고 수정해보겠습니다!

2023-03-05 05:08 UTC, ksone02 commented on src/abstracts/types.ts
> +}
감사합니다!

2023-03-05 05:12 UTC, ksone02 commented on src/components/modal/ModalComponent.js
> +    document
document가 아닌 this로 수정해두겠습니다!

2023-03-05 05:13 UTC, ksone02 commented on src/abstracts/CustomElement.js
> +  setEvent() {}
돔에서 이루어지는 이벤트들을 관리하기 위한 메서드입니다.
set이라는 prefix 때문에 헷갈릴 수 있는 부분인 것 같네요!
더 적절한 방향으로 수정해보겠습니다.

2023-03-05 10:31 UTC, ksone02 commented
우선 질문에 대한 답변과 피드백 정말 감사합니다!

> 플럭스 패턴을 도입하셨군요. 어떤 장단점을 느끼셨을까요?

평소에 MVC를 사용하며 프론트엔드에서 MVC 패턴을 사용하는게 맞는지에 대한 의문과 찝찝함이 있었습니다. 플럭스 패턴을 도입하며 그 찝찝함이 해소되었습니다. 우선 데이터의 단방향 흐름으로 구조가 더욱 깔끔하고 단순화되었다고 생각하며, 데이터를 싱글톤 Store에서 전역적으로 관리해주어 상태관리도 해결했습니다. 하지만 Action을 따로 정의, 관리해주어야 하는 점은 단점이라는 생각이 들었습니다.

> 웹컴포넌트를 사용하셨는데 모든 돔 요소를 document에서 접근하고 있어요.
>
>컴포넌트 간에 의존성이 없는 거 같지만 애매하게 다른 영역을 침범하는 컴포넌트가 보여서 오히려 더 위험하다고 느꼈어요.
>
>예를 들면 헤더 컴포넌트는 모달 컴포넌트를 직접 참조하고 있지 않지만
>헤더컴포넌트에서 .modal 클래스를 가진 돔객체에 접근해서 modal--open이라는 classList를 추가하고 있죠.
>이 로직이 헤더컴포넌트 코드에 직접 배치되면서 모달컴포넌트가 해야될 책임을 대신 수행하고 있어요.
>
> 어떻게 개선할 수 있을까요?

해당 컴포넌트 내에서 이루어지는 돔 조작은 document -> this로 수정했습니다.
모달과 같은 경우는 두가지 방향으로 리팩터링 할 수 있을 것 같습니다.
1. 모달 컴포넌트를 헤더 컴포넌트 하위에서 조작한다.
2. 모달의 ON / OFF 상태를 전역적으로 관리한다.

컴포넌트간의 의존성을 최대한 잘 관리할 수 있도록 두번쨰 방법으로 개선해보겠습니다.

> 일단, 두 방법 모두 테스트 가능할 거 같아요.
>
>이런 상황이라면 어떨까요? 가정해볼게요.
>로컬스토리지, 다양한 클라우드 스토리지들이 존재.
>비용/경영 이슈로 어떤 스토리지를 사용할 지 주기적으로 바뀌고 있음.
>
>이런 상황이라면 어떻게 구조를 짜야하고 테스트를 할 수 있을까요?

스토리지를 Store에서 직접 관리하는 것 보단 따로 관리하는 방법이 좋을 것 같다는 판단이 듭니다.
그러면 스토리지에 있는 데이터를 테스트 하기 보단 객체가 갖고 있는 데이터를 테스트하라는 말씀이신가요?

감사합니다 :)

2023-03-06 17:50 UTC, lsw1164 approved these changes
에디, 피드백 반영하느라 고생 많으셨어요👍

2023-03-06 17:50 UTC, lsw1164 commented on __tests__/render.test.js
> +});
독립적인 테스트가 서로 연결돼 있어요.  
하나의 테스트가 수정되면 다른 테스트도 같이 깨지겠군요  
개선할 수 있을까요?

2023-03-06 17:50 UTC, lsw1164 commented on src/abstracts/CustomElement.js
> +  rerender(data) {}
render와 rerender 구분은 어떤 의도인지 설명해주실 수 있을까요?

2023-03-06 17:50 UTC, lsw1164 commented on src/domain/RestaurantsStore.ts
> +    if (!localStorage.getItem(RESTAURANTS_STORAGE)) {
다음 스텝에서는 스토리지도 분리해보면 좋을 거 같아요 :)

2023-03-06 17:50 UTC, merged

2023-03-07 04:23 UTC, ksone02 commented on __tests__/render.test.js
> +});
저는 중복되는 코드라고 생각했는데, 다시 생각해보니 독립적 테스트로 판단해야 하니 수정이 필요할 것 같네요! 감사합니다 :)

2023-03-07 04:24 UTC, ksone02 commented on src/abstracts/CustomElement.js
> +  rerender(data) {}
render는 컴포넌트가 맨 처음 렌더링될 때 실행되는 메서드, rerender는 컴포넌트가 데이터를 받고 리렌더링 될 때 실행되는 메서드라고 정의했습니다. render 메서드명을 initRender와 같은 형태로 적어주는 게 이해하기 쉬울까요?

2023-03-07 04:24 UTC, ksone02 commented on src/domain/RestaurantsStore.ts
> +    if (!localStorage.getItem(RESTAURANTS_STORAGE)) {
감사합니다!