[1단계 - 음식점 목록] - 파란(안영훈) 미션 제출합니다.
woowacourse/javascript-lunch pull request #116
Opened 2024-03-08 08:09 UTC by greetings1012

# 🚀 프로젝트 실행 링크 
https://greetings1012.github.io/javascript-lunch/

## 📖 신경 쓴 부분들
안녕하세요, 지그! 잘 부탁드립니다 😄
저와 페어(아르)가 코드를 작성하면서 집중한 부분은

✅ 최대한 TypeScript를 사용하면서 타입 명시해주기
✅ 구체적이고 효율적인 폴더링으로 프로젝트 관리, 확장이 용이하게 하기
✅ webcomponent를 활용해 root와 modal간의 이벤트 중첩 혹은 충돌 방지
✅ type와 interface를 통해 사용하는 데이터들의 형태를 명확하게 선언, 데이터 무결성 유지
✅ localStorage에 데이터가 없을 경우 기본 데이터를 넣어주어 사용자 경험 개선(사용자는 빈 화면을 볼 일이 없음!)

## 🧐 놓친 부분들
위의 부분들을 신경쓰느라 놓친 부분들도 많았어요 🥲

❌ TypeScript에 익숙하지 않아 모든 인자와 변수, 상수를 함수로 전달할 때 형태를 유지하면서 전달하는 것이 어려웠어요. 특히 JSON, string 형태의 데이터를 ILocation 형태로 파싱하여 사용해야 하는데, 몇 시간동안이나 고민하고 찾아봤지만 결국은 [!, ?, as, any]가 많이 쓰였어요 😥
❌ 위 문제가 프로젝트 전체에 걸쳐 일어나다 보니 결과적으로 시간이 부족해져
- 리터럴의 상수화
- css 파일 분리
- 사용자가 잘못된 입력을 했을 때 메시지 일관되게, 아름답게 표시
- validation 구체화
- test코드 작성
에 대해서는 거의 신경쓰지 못했어요.
시간이 더 있었으면 할 수 있는 것들이라 더 아쉬움이 많이 남습니다 😭
추가 질문들은 각 코드 부분에 남겨놓도록 할게요!

## 프로젝트 구조
📦src
 ┣ 📂app
 ┃ ┣ 📂controller
 ┃ ┃ ┗ 📜AppController.ts
 ┃ ┣ 📂modal
 ┃ ┃ ┗ 📂AddRestaurantModal
 ┃ ┃ ┃ ┗ 📜AddRestaurantModal.ts
 ┃ ┗ 📂root
 ┃ ┃ ┣ 📂LunchHeader
 ┃ ┃ ┃ ┗ 📜LunchHeader.ts
 ┃ ┃ ┣ 📂RestaurantItem
 ┃ ┃ ┃ ┗ 📜RestaurantItem.ts
 ┃ ┃ ┣ 📂RestaurantList
 ┃ ┃ ┃ ┗ 📜RestaurantList.ts
 ┃ ┃ ┗ 📂SelectBoxSection
 ┃ ┃ ┃ ┗ 📜SelectBoxSection.ts
 ┣ 📂assets
 ┃ ┗ 📂image
 ┃ ┃ ┣ 📜add-button.png
 ┃ ┃ ┣ 📜category-asian.png
 ┃ ┃ ┣ 📜category-chinese.png
 ┃ ┃ ┣ 📜category-etc.png
 ┃ ┃ ┣ 📜category-japanese.png
 ┃ ┃ ┣ 📜category-korean.png
 ┃ ┃ ┣ 📜category-western.png
 ┃ ┃ ┣ 📜favorite-icon-filled.png
 ┃ ┃ ┗ 📜favorite-icon-lined.png
 ┣ 📂constants
 ┃ ┣ 📜Type.ts
 ┃ ┗ 📜setting.ts
 ┣ 📂css
 ┃ ┗ 📜style.css
 ┣ 📂data
 ┃ ┗ 📜defaultRestaurants.json
 ┣ 📂domain
 ┃ ┗ 📜Restaurant.ts
 ┣ 📂interface
 ┃ ┗ 📜Interface.ts
 ┣ 📂service
 ┃ ┗ 📜RestaurantService.ts
 ┣ 📂utils
 ┃ ┣ 📜domSelector.ts
 ┃ ┗ 📜fetchLocalData.ts
 ┣ 📂validator
 ┃ ┗ 📜RestaurantValidator.ts
 ┗ 📜index.js

2024-03-08 08:22 UTC, greetings1012 commented on src/interface/Interface.ts
> +}
처음에는 가게의 인터페이스를
```
interface ILocation = {
  name: string;
  category: Category;
  minutesWalk: MinutesWalk;
  description?: string;
  referenceUrl?: string;
};
```
와 같이 형태를 지정해주는 용도로 사용했지만, 인터페이스에 대해 찾아보니

> "상속을 사용하면서 일어나는 종속성에서부터 자유로워지기 위해 인터페이스를 사용한다"

라는 글을 보고 형태를 바꿨어요.

2024-03-08 08:30 UTC, greetings1012 commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +              <input type="text" name="name" id="restaurant-name" required />
required 속성을 사용하니 event에서 alert를 추가해도 required 속성이 먼저 실행되는 것을 확인했어요.

> ex) 이름 값에 아무것도 입력하지 않고 추가하기를 누르면 alert가 등장하지 않고 '값을 입력해주세요' 라는 크롬 경고모달이 등장함

이 문제를 해결하기 위해 검색해보았지만 해답을 찾을 수 없었습니다 😥
required 태그의 효과는 event보다 상위에 있는 걸까요?

2024-03-09 02:12 UTC, zigsong requested changes
안녕하세요, 파란! 리뷰를 맡은 지그입니다.

이번 미션부터 타입스크립트를 사용하시면서 고민하신 흔적이 많이 보이는데요, 

- 모든 인자와 변수, 상수를 타이핑하실 필요는 없습니다.
- JSON 문자열을 타입으로 변환할 때도 지금 사용하신 `as` 단언 이외에 더 확실한 방법도 없습니다.

처음부터 타입스크립트를 완벽하게 작성하시려고 애쓰실 필요는 없을 것 같아요. 지금도 충분히 잘 작성해주셨습니다 ☺️ 코드 설계 역시 놀랄 정도로 객체 간 필요한 메시지 및 값을 잘 전달해주는 구조로 작성해주셔서 크게 리팩토링할 부분은 없을 것 같아요. 

리뷰 반영하시면서 시간이 되신다면, 본문에 말씀해주셨던 내용들을 보완해서 재요청 남겨주셔도 좋을 것 같습니다.

2024-03-09 02:12 UTC, zigsong commented on src/interface/Interface.ts
> +}
미션에 타입스크립트를 쓰기 시작한 순간부터 `type` vs `interface` 에 대한 논의가 끊이지 않을 것 같은데요… 

사실 `type`과 `interface`는 거의 유사하며, 다만 몇 가지 부분에서 사용 방식 및 사용할 수 있는 방식에 차이가 있기 때문에 쓸모에 맞춰 쓰면 됩니다.(이 차이점들은 검색하면 많은 양의, 똑같은 내용의 자료가 나오기 때문에 제가 설명하진 않겠습니다.) 아니면 협업하는 동료와 컨벤션을 맞추면 되구요. 

다만 일반적으로 `type`은 할당할 수 있는 ‘값’에 초점, `interface`는 형태를 맞추기 위한 ‘구조’에 초점을 맞춥니다. 그런 관점에서 `interface`는 상속, 선언적 병합의 방식으로 쓸 수 있는 것이구요. 

> "상속을 사용하면서 일어나는 종속성에서부터 자유로워지기 위해 인터페이스를 사용한다”
> 

라는 문장은, 파란이 보신 글의 앞뒤 맥락을 알기 어렵기 때문에 제가 이해하기 어려운데요, 링크를 첨부해주시면 한번 확인해보고 설명드리도록 하겠습니다. 

지금 코드의 경우 오히려 원래 파란이 생각하신 기존 방식의 인터페이스가 더 잘 맞는 것 같아요. 

인터페이스는 어떤 객체의 ‘구조’를 지정해주기 위해 많이 사용된다고 했는데요, 

- `getName`, `getMinutesWalk`와 같은 함수들은 인터페이스가 아니라 클래스의 getter와 같다고 여겨지며
- 지금의 `ILocation`은 `Location` 에 대한 정보를 다 가지고 있지도 않습니다.

즉 타입스크립트에서 의도한 인터페이스의 목적대로 사용되고 있지 않아요. 

현재 코드에서 굳이 `LocationData`와 `ILocation` 이 분리될 필요도 없어 보이고, `class Restaurant`이 `ILocation`을 implements할 필요도 없어 보입니다. 코드 추상화를 위해서는 좋은 방법이지만, 우선은 인터페이스의 사용부터 제대로 짚고 넘어가는 것이 좋을 것 같아요.

2024-03-11 07:13 UTC, greetings1012 commented on src/constants/Type.ts
> +type MinutesWalk = (typeof TYPE_SETTING.minutesWalk)[number];
처음에는
```
type Category = '한식' | '중식' | '일식' | '양식' | '아시안' | '기타';
```

와 같이 enum을 활용한 type 형식 하나로 만들었는데, 이 경우에 SelectboxSection.ts의 getCategoryName()과 getFilterName() 에서

```
private getCategoryName() {
    return TYPE_SETTING.category.map((category) => {
      return `<option value="${category}">${category}</option>`;
    });
  }
```

을 구현할 때 map 등 내장 함수로 type 안의 값들을 불러올 수 없어 하나하나 하드코딩 해야 하는 문제가 있었어요.
그래서 내용을 일단 상수로 선언하고, 선언한 것들을 다시 type으로 불러와 선언했습니다.
사실 상수 선언과 type 선언을 둘 다 하는 것은 매우 비효율적이긴 하지만, type을 쓰며 데이터 형식을 선언하는 연습을 해보고 싶었어요.

만약 위의 getCategoryName과 같이 내장 함수를 통해 하드코딩을 피하고 싶을 땐 상수로 선언하고, type은 사용하지 않는 것이 좋은 방법일까요?

2024-03-11 08:15 UTC, greetings1012 commented on src/interface/Interface.ts
> +}
미션을 들어가면서

> 만약 '점심 뭐 먹지'에서 다른 기능이 생겨 근처 PC방, 노래방 등 다른 장소도 관리하게 된다면, 어떻게 만들어야 다른 카테고리까지 쉽게 확장할 수 있을까?

ex) 스피커의 확장
![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FmetvC%2FbtrKmGqoKwM%2Fx7hL6j0kcKboJp3szRBe2k%2Fimg.png)

라는 생각에서 interface를 설계했어요.
따라서 다른 사람들과의 협업, 또는 관리의 필요성에 의해 getter 또한 interface 안에 선언해주는 것이 좋다고 생각했습니다!
또한 'json에서 파싱해오는 data type' 과 'Restaurant, 노래방 등의 class에게 상속하는 interface' 는 다르다고 생각해서 
ILocation은 여러 장소들을 상속해 구조를 선언해주기 위한 interface, 
LocationData는 json 데이터를 받아올 때 등 데이터를 관리할 때 데이터의 값을 지정해주기 위한 type로 선언했습니다.
사실 오버엔지니어링이라는 생각이 들기도 하지만... interface를 사용하는 김에 확장성에 대한 고민도 하고 싶었어요 🥹

ILocation에 name, category 등 모든 필드값을 선언한 후 데이터를 관리하냐, 클래스를 관리하냐에 따라 ILocation과 LocationData를 둘 다 사용하는 것에 대해서는 어떻게 생각하시나요?

PS: 블로그는 제가 인터페이스를 설계할 때 마구잡이로 찾다 마주친 글에서 찾은 글이라 지금은 아무리 찾아도 보이지 않네요 🥲

2024-03-11 08:22 UTC, greetings1012 commented on src/constants/Type.ts
> +export { Category, MinutesWalk, Sort, CompareFunction, LocationData };
수정했습니다!

2024-03-11 16:19 UTC, greetings1012 commented on src/constants/setting.ts
> +    기타: require('/src/assets/image/category-etc.png').default,
반영했습니다! 👍

2024-03-11 16:21 UTC, greetings1012 commented on src/app/root/LunchHeader/LunchHeader.ts
> +          bubbles: true,
수정했습니다! 오류 수정을 위해 몇몇 곳에 추가했다가 해결하고 지운 구문인데, 아직 남아있는 곳이 있었네요 🥲

2024-03-11 16:26 UTC, greetings1012 commented on cypress/e2e/Restaurant.cy.ts
> +describe('[Restaurant] 음식점 객체 테스트', () => {
크론 코치가 '이렇게도 cypress를 사용할 수 있다' 라는 것을 알려주면서 예시를 들어준 것 몇 개를 TDD를 진행하면서 따라해봤어요.
간단한 객체 테스트를 몇 개 작성해서 cypress 문법에 익숙해 진 다음 e2e 테스트를 진행하려고 했는데, 시간이 부족해서 테스트를 완성하진 못했네요 😭
리팩터링 하면서 e2e 테스트 코드를 완성하는 것을 목표로 하겠습니다!

2024-03-11 16:51 UTC, greetings1012 commented on src/app/controller/AppController.ts
> +    document.querySelector('#app')!.appendChild(restaurantList);
수정했어요! 
else에 error를 반환하게 하거나 console에 메시지를 출력하게 하고 싶지만, 그렇게 하면 코드가 너무 길어질 것 같아 일단은 보류하겠습니다 😂

2024-03-11 17:14 UTC, greetings1012 commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +        this.submitNewRestaurantData(restaurantInputData);
수정했습니다! 확실히 input이 검증되지도 않았는데 강제로 LocationData로 형변환 시키는 것이 올바른 방법으로는 보이지 않네요.

2024-03-11 17:20 UTC, greetings1012 commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +              <label for="name text-caption">이름</label>
for attribute는 자신과 연결된 attribute의 id에 연결되는 것으로 알고 있어요!
원본 저장소에 들어있는 템플릿을 그대로 사용했는데, 추후 CustomEvent를 만들면서 id값을 수정하던 중 for의 내용을 바꾸는 것을 잊어버린 듯 합니다 😅
수정했습니다!

2024-03-11 17:23 UTC, greetings1012 commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +        }
저는 submit 버튼을 누를 때 RestaurantValidator를 호출해서 문제가 있을 경우 alert를 띄우는 것을 의도했었어요.
그래서 여기에 try~catch문을 사용했는데, 혹시 이곳에서 error가 잡히지 않는 이유를 여쭤볼 수 있을까요?

2024-03-12 11:40 UTC, greetings1012 commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +        }
+) name input에 require, maxlength, minlength, pattern을 적용해 잘못된 입력을 막고 placeholder으로 사용자에게 올바른 입력 방식을 안내한 후 try-catch문을 일단 제거했습니다. 이전의 방식보다는 지금 방식이 더 간결하고 일관적인 것 같네요!

2024-03-12 11:55 UTC, zigsong commented on src/interface/Interface.ts
> +}
1. 말씀하신 대로 현재 미션의 요구사항에 비하여 오버엔지니어링이라고 생각합니다. 하지만 지금은 교육 과정이기에 '추후 확장성까지 고려하여' 설계해보신 점에 대해서는 따로 더 이견을 제시하진 않겠습니다.
2. 다만 특정 interface를 implements 해서 사용하는 클래스 패턴은 실무에서는 흔하지 않으며, 현재 파란이 클래스로 선언하신 `Restaurant` 자체를 특정 함수와 필드들을 가진 인터페이스로 선언하는 편이 이해하기 쉬웠을 것 같습니다. 
3. `LocationData`와 `ILocation`을 꼭 분리하고 싶었다면, 둘 다 interface로 통일하는 것이 좋아보입니다. '데이터를 관리하는가, 클래스를 관리하는가'는 전제부터가 잘못된 문장입니다. 보통은 클래스가 데이터를 가지고 있죠.

2024-03-12 11:59 UTC, zigsong commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +import RestaurantValidator from '../../../validator/RestaurantValidator';
`RestaurantValidator` 이제 아무데서도 안 쓰이고 있는 것 같은데요?

2024-03-12 11:59 UTC, zigsong commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +              <input type="text" name="name" id="restaurant-name" placeholder="1~20글자 사이로 입력해주세요. 공백만 입력할 수 없습니다." pattern="^\S.*$" minlength="1" maxlength="20" required />
placeholder가 잘리네요.

<img width="400" alt="image" src="https://github.com/woowacourse/javascript-lunch/assets/44080404/0a9f902f-d8e5-48f7-aa6f-825d6aa6d46e">

추가로, https://brunch.co.kr/@ebprux/250 글을 참고하셔서 placeholder에 어떤 내용이 들어가야 하는지 공부해보시면 좋을 것 같습니다.

2024-03-12 11:59 UTC, zigsong commented on src/constants/setting.ts
> +    기타: require('/src/assets/image/category-etc.png').default,
assets로 파일도 분리해주셨네요 👍 훨씬 좋습니다

2024-03-12 12:11 UTC, zigsong commented on src/constants/Type.ts
> +type MinutesWalk = (typeof TYPE_SETTING.minutesWalk)[number];
아하 그런 이유가 있었군요

다만 지금과 같은 패턴은 마치 객체(배열)를 type처럼 사용하려는 의도로 보여서(`TYPE_SETTING`안에 객체들이 들어있기 때문), 객체와 타입을 분리해서 선언하는 것은 필요할 것 같습니다.

```tsx
const category = ['한식', '중식', '일식', '양식', '아시안', '기타'] as const;
const minutesWalk = [5, 10, 15, 20, 30] as const;
const sort = ['이름순', '거리순'] as const;
```

```tsx
type Category = (typeof category)[number];
type MinutesWalk = ... 
```

아니면 제가 말씀드린 대로 enum을 사용해도 되구요

```tsx
export enum Category {
  '한식',
  '중식',
  '일식',
  '양식',
  '아시안',
  '기타',
}
```

```tsx
  private getCategoryName() {
    return Object.values(Category).map((category) => {
      return `<option value="${category}">${category}</option>`;
    });
  }
```

실무에서는 enum을 많이 활용하는 것 같습니다. 서버에서 받은 응답값에도 특정 값들의 목록을 제한하는 데 많이 사용되고요.

2024-03-12 12:14 UTC, zigsong commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +        this.submitNewRestaurantData(restaurantInputData);
여기서 `RestaurantValidator`가 버려졌군요... 🤔🤔

2024-03-12 12:17 UTC, zigsong commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +        }
> 혹시 이곳에서 error가 잡히지 않는(혹은 부적절한 에러 핸들링 위치인) 이유를 여쭤볼 수 있을까요?

지금 코드를 바꾸셔서 다시 이전으로 돌려보았는데요, 

```jsx
    $('#add-restaurant-form')!.addEventListener('submit', (event: Event) => {
      try {
        // ...        
        this.submitNewRestaurantData(restaurantInputData);
      } catch (error) {
        if (error instanceof Error) {
          alert(error.message);
        }
      }
    });
```

위 코드에서, input에 내용이 잘못 입력되었다 하더라도 그것은 input 자체의 validation인 것이지 form submit 이벤트의 에러가 아니라 catch 구문에 걸리지 않습니다.

2024-03-12 12:24 UTC, zigsong requested changes
안녕하세요 파란, 고민한 내용들 함께 공유해주셔서 감사합니다.

수정해주신 내용들에 대해 추가 코멘트 남겼는데요, 바로 머지할까 했지만 조금 수정의 여지를 남겨주신 부분들이 있는 것 같아 한번 더 request 드립니다. 개선 사항들을 2단계에서 진행하실 예정이라면, 알려주시면 바로 머지하도록 하겠습니다 :D

2024-03-12 12:24 UTC, zigsong commented on package.json
> +  "readme": "https://github.com/woowacourse/javascript-lunch#readme",
package.json에 요런것도 넣을 수 있군요 👀

2024-03-12 12:24 UTC, zigsong commented on src/app/controller/AppController.ts
> +  }
2단계에서 기능들이 더 추가되면 앱의 모든 로직을 `AppController`에 넣는 대신 각 컴포넌트의 역할별로 구분해주면 더 좋을 것 같아요 :D

2024-03-13 01:43 UTC, greetings1012 commented on src/interface/Interface.ts
> +}
> 2. 다만 특정 interface를 implements 해서 사용하는 클래스 패턴은 실무에서는 흔하지 않으며, 현재 파란이 클래스로 선언하신 `Restaurant` 자체를 특정 함수와 필드들을 가진 인터페이스로 선언하는 편이 이해하기 쉬웠을 것 같습니다.
> 3. `LocationData`와 `ILocation`을 꼭 분리하고 싶었다면, 둘 다 interface로 통일하는 것이 좋아보입니다. '데이터를 관리하는가, 클래스를 관리하는가'는 전제부터가 잘못된 문장입니다. 보통은 클래스가 데이터를 가지고 있죠.

위의 내용들을 종합해서 제가 이해한 내용으로는, 굳이 LocationData와 ILocation을 type와 interface로 나누기보다는 class를 LocationData와 ILocation을 합친 것으로 활용하는 것이 훨씬 더 효율적이고 유지보수가 편하다는 뜻이라고 생각합니다!
제가 이해한 것이 맞을까요?

2024-03-13 02:25 UTC, greetings1012 commented on src/constants/Type.ts
> +type MinutesWalk = (typeof TYPE_SETTING.minutesWalk)[number];
지그의 피드백을 듣고 고민해 본 결과, enum으로 작성하는 것이 더 실용적인 코드가 될 것 같네요!
확실히 하나의 분류를 type와 const로 나누는 것이 옳지 않은 접근 방식 같아요.
모두 enum으로 변경했습니다 👍

2024-03-13 02:31 UTC, greetings1012 commented on cypress/e2e/Restaurant.cy.ts
> +describe('[Restaurant] 음식점 객체 테스트', () => {
현재로서는 e2e 테스트를 작성하려면 validator 구조부터 다시 만들어야 해서 시간 소요가 많을 것 같습니다 😭
이 부분은 머지해주시면 2단계 때 도전해보도록 하겠습니다.

2024-03-13 02:31 UTC, greetings1012 commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +        this.submitNewRestaurantData(restaurantInputData);
2단계 때 다시 붙여서 테스트를 완성해보도록 하겠습니다....

2024-03-13 02:33 UTC, greetings1012 commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +        }
코드를 수정해 일단 html만으로도 입력을 제한할 수 있도록 코드를 수정했습니다.
위에서 말씀드린 대로, 2단계 때 Validation을 다시 구현해서 연결해 보도록 하겠습니다!

2024-03-13 02:34 UTC, greetings1012 commented on src/app/modal/AddRestaurantModal/AddRestaurantModal.ts
> +              <input type="text" name="name" id="restaurant-name" placeholder="1~20글자 사이로 입력해주세요. 공백만 입력할 수 없습니다." pattern="^\S.*$" minlength="1" maxlength="20" required />
글을 참고해 형식을 바꿨습니다!
placeholder는 focus를 주는 순간 내용이 사라져 input되어야 하는 값을 알려주는 용도로 쓰기에는 부적절하군요 😭

2024-03-13 02:36 UTC, greetings1012 commented on package.json
> +  "readme": "https://github.com/woowacourse/javascript-lunch#readme",
gh-pages@6.1.1 패키지를 이용해 커맨드를 입력하면 자동으로 빌드 후 github pages로 배포되도록 설정했습니다 😁

2024-03-13 02:40 UTC, greetings1012 commented on src/app/controller/AppController.ts
> +  }
확인했습니다! 
저도 AppController가 조금 많은 내용을 담고 있다고 생각하고 있었어요.
2단계를 진행하면서 같이 리팩터링 해보도록 하겠습니다!

2024-03-13 12:14 UTC, zigsong commented on src/interface/Interface.ts
> +}
네 정확히 이해하셨습니다! 굳이 나눌 필요는 없어용 :)

2024-03-13 12:15 UTC, zigsong commented on src/constants/Type.ts
> +type MinutesWalk = (typeof TYPE_SETTING.minutesWalk)[number];
enum이 반드시 정답은 아니지만, 실무에서 유용하게 쓰일 때가 많습니다. 😄

2024-03-13 12:18 UTC, zigsong approved these changes
안녕하세요 파란~! 두번째 리뷰 반영까지 고생 많으셨습니다. 

여러 고민들을 하며 많이 배우신 것 같아요. 남은 고민들은 2단계에서 기능을 발전해보며 함께 더 이야기 나눠봐요. 화이팅! 💪

2024-03-13 12:19 UTC, merged