[1단계 - 음식점 목록] 포메(김우성) 미션 제출합니다.
woowacourse/javascript-lunch pull request #117
Opened 2024-03-08 08:09 UTC by novice0840

배포링크: https://novice0840.github.io/javascript-lunch/dist/

안녕하세요, 호프. Fe 크루 포메라고 합니다. 이번 미션 잘 부탁드립니다!

# 고민점

프레임워크를 사용하지 않고 UI를 컴포넌트 단위로 분리하는게 가장 관건인 미션이었다고 생각합니다. Web component를 쓸 까 고민했었지만 페어와 저 둘 다 사용 경험이 없고 미션 제출 기한이 3일인 것을 감안해 무리라고 판단해 사용하지 않고 진행했습니다. 겹겹히 트리의 형태로 쌓여있는 UI를 컴포넌트로 분리를 하는 것이 굉장히 어렵게 느껴졌었습니다. 뿐만 아니라 서로 다른 두 컴포넌트에서 한 컴포넌트의 데이터가 바뀌었을 때 반대쪽 컴포넌트를 re-render해주는 방식에 대해서도 많을 고민을 해보았습니다. 결과적으로, 동작은 하지만 내부 설계에 아쉬움이 남은 미션이었습니다. 

# 질문

전체적인 설계에 대한 호프의 의견을 듣고 싶습니다. 저희의 상황에서 어떠한 방식이 가장 보편적인 해결방식일지 제 3자의 관점에서의 의견을 듣고 싶습니다.

2024-03-09 07:03 UTC, moonheekim0118 requested changes
안녕하세요 포메~ 이번 미션 리뷰하게된 호프입니다ㅎㅎ 앞으로 잘부탁드려요 :)

제출 기한과 러닝커브를 생각하여 웹컴포넌트 도입을 하지 않은 결정을 내려주셨다고 했는데, 현명한 결정이라고 생각합니다.  👏 


제 개인적인 생각으로는..러닝 커브가 높은 기술을 도입 할 때에는 아래와 같은 사항들을 확인하면 좋다고 생각합니다.

1. 해당 기술이 문제를 해결하는데 도움이 되는가? (정말 다른 대안은 없는가?)
2. 1번에서 yes라면, 위에서 도출한 기술 도입의 장점과 학습 시간의 트레이드오프를 계산했을 때, 이익 > 손해인가?

를 고려하는 것 같습니다. ㅎㅎ 그 관점에서 봤을 때 제출기한을 우선시하여 결정을 내려주신게 인상깊었습니다 👍 👍 👍 


> 전체적인 설계에 대한 호프의 의견을 듣고 싶습니다. 저희의 상황에서 어떠한 방식이 가장 보편적인 해결방식일지 제 3자의 관점에서의 의견을 듣고 싶습니다.

보편적인 해결방식이라는건 없는 것 같습니다ㅎㅎ개발에 은탄환은 없으니까요. 
오히려 포메는 어떤 생각으로 이러한 구조를 잡아주셨는지 궁금하네요. 

그래도 저의 의견을 말씀드리자면, 전체적인 설계는 코드를 읽을 때 크게 걸림돌이 될만한 부분은 없었고요, 리렌더링 관련한 고민도 주어진 범위 내에서 잘 해결해주신 것 같아요.
컴포넌트 관련한건 코멘트 남겨놨으니 거기서 이야기 나눠봐요ㅎㅎ


그럼 고생하셨습니다 👍 👍  코멘트 확인해주시고, 재리뷰요청 주세요 :) 


(+ 추가로 모달이 모바일 뷰포트에서는 잘려져보이는데 개선해주시면 좋을 것 같아요!)
<img width="469" alt="스크린샷 2024-03-09 오후 4 11 22" src="https://github.com/woowacourse/javascript-lunch/assets/61469664/7c95f9ad-0007-4072-a097-5f93a9f2a967">

2024-03-09 07:03 UTC, moonheekim0118 commented on src/view/components/RestaurantFormModal.ts
> +      listener(e);
또한 '모달'이라는 UI의 역할(닫힘/열림)은 앱의 어떤 페이지에서도 동일할 것 같은데요,
이를 한번 재사용 가능한 형태로 만들어보면 어떨까요?
앱에 모달이 추가될 때마다 **Modal이란 컴포넌트를 만들어야할까요?

2024-03-11 05:44 UTC, novice0840 commented on src/view/components/RestaurantFormModal.ts
> +      listener(e);
리액트의 디자인을 제공해주는 UI design 라이브러리인거 같은데 제가 찾은게 맞을까요?

2024-03-12 05:26 UTC, novice0840 commented on src/view/index.ts
> +    ) as HTMLButtonElement;
Generic Type을 사용해 as를 없애보았습니다.

2024-03-12 11:36 UTC, novice0840 commented on src/view/components/RestaurantFormModal.ts
> +    });
초기 렌더링 함수에 포함시키는 방식으로 변경해 보았습니다.

2024-03-12 12:22 UTC, novice0840 commented
안녕하세요, 호프. 정리해주신 요구사항들 확인했습니다. 수정사항들 적용 후 커밋 올려놨습니다.

2024-03-12 12:24 UTC, novice0840 commented on src/view/components/RestaurantSelectSection.ts
UI와 비즈니스 로직을 분리해서 만드는 것이 좋다고 생각하긴 합니다. UI와 관련된 로직들은 가능하면 컴포넌트화를 하고 도메인과 관련있는 비즈니스 로직들은 외부에서 컴포넌트 외부에서 조작하는 방식으로요.

2024-03-12 14:46 UTC, moonheekim0118 approved these changes
안녕하세요 포메~ 리뷰 반영해주신 것 확인했습니다. 고생하셨어요~

하지만 아직까지 `재사용가능한 컴포넌트를 만든다`라는 요구사항 충족은 조금 아쉽긴 하네요. 현재 포메가 만들어주신 컴포넌트들은 오로지 하나의 페이지 내에서만 유효할 것 같아요.
 그러나 제가 리뷰로 백번 말하는것보다는 2단계 가시면 자연스럽게 현재 컴포넌트 구조의 한계점을 직접 느끼실 수 있을 것 같아서 step1은 이만 마무리할게요!
step2시작하시면 여러 도메인에서도 범용적으로 사용할 수 있는 컴포넌트를 만들어주시는데 집중해주시면 좋을 것 같습니다. 🙂

(+ 아직 최신버전으로 배포되지 않은 것 같은데 한번 확인부탁드려요.)

2024-03-12 14:46 UTC, moonheekim0118 commented on src/types/index.ts
> +type ArrayToEnum<T extends readonly unknown[]> = T[number];
👏 👏 👏 훌륭합니당

2024-03-12 14:47 UTC, merged

2024-03-12 14:56 UTC, moonheekim0118 commented on src/view/index.ts
> +    ) as HTMLButtonElement;
여기 아직도 as 가 있는것 같아요ㅎㅎ
또한 제가 리뷰하면서 의도드린 키워드는 `타입가드`였습니다.

2024-03-12 14:59 UTC, moonheekim0118 commented
@novice0840 

답변 주신 부분에 대해서 코멘트도 추가로 남겼는데 확인부탁드리고,
https://github.com/woowacourse/javascript-lunch/pull/117#discussion_r1521581676
https://github.com/woowacourse/javascript-lunch/pull/117#discussion_r1521622650

아직 반영안된 리뷰는 다음단계에 반영하시는걸로 인지하고 있을게요 :)
만약 반영이 어려우시다면 어떤 이유에서 어려우신지 알려주시면 좋겠습니다ㅎㅎ