[1단계 - 음식점 목록] 다르(이상엽) 미션 제출합니다.
woowacourse/javascript-lunch pull request #121
Opened 2024-03-08 08:24 UTC by pp449

[배포주소](https://pp449.github.io/javascript-lunch/dist/)

반가워요 유조 :) 저는 다르입니다 🦦
웹 컴포넌트의 개념을 처음 들어보고 작업했기에 어려운게 많았고 지금 돌이켜 생각해보니 잘 작업했는지 모르겠네요.. 🥲

이번 미션 잘 부탁드립니다 🙇‍♂️

# 🎯 미션 목표

<details>
  <summary>자세히 보기</summary>

- 이번 미션의 취지인 공통 컴포넌트 재사용에 대해서 고민을 많이 했고, 재사용이 될 수 있다고 생각한 컴포넌트는 최대한 재사용할 수 있도록 만들었어요

- 컴포넌트, 도메인 등등 각 객체별로 책임을 분리하도록 노력했어요

- 최대한 타입을 정해서 사용하려고 노력했어요
</details>

# 🗂️ 컴포넌트
<details>
  <summary>자세히 보기</summary>
  
  
<img width="632" alt="image" src="https://github.com/woowacourse/javascript-lunch/assets/71641127/c5d9b4a2-98c0-4a81-91d6-f6c1b42b7515">
<img width="654" alt="image" src="https://github.com/woowacourse/javascript-lunch/assets/71641127/3a90a012-f16f-4014-9120-496a2ae43e6c">

## 📁 components/common/

### FormItem
- 새로운 식당 추가 시 각 입력폼을 재활용하기 위해 만든 컴포넌트

### Modal
- 식당 추가에 사용되는 모달 창 컴포넌트

### Select
- select 엘리먼트의 경우 option 을 어트리뷰트 받아 쉽게 사용하는 컴포넌트

## 📁 components/

### CategoryIcon
- 카테고리 별 아이콘을 보여주는 컴포넌트

### RestaurantItem
- 레스토랑의 정보를 보여주는 컴포넌트

### RestaurantList
- RestaurnatItem 들을 보여주는 컴포넌트

### FilterBar
- 필터 및 정렬하는 버튼을 관리하는 컴포넌트

### RestaurantHeader
- 앱의 헤더 컴포넌트

### RestaurantForm
- 새로운 음식점을 추가하는 폼 컴포넌트

</details>

# 🙋궁금한 점
<details>
  <summary>자세히 보기</summary>

### Category 상수
1. 현재 Category 관련 상수가 아래와 같이 4개가 있는데 "꼭 이렇게 4개로 만들어야하는가?" 와 "잘 사용하고 있는가" 에 대한 의문점이 있었어요!  그 이유는 공통된 요소가 있었기에 충분히 재사용할 수 있을거라 생각은 했지만 방법을 찾지 못했어요..

2. KOREAN_CATEGORY 의 타입을 보면 저는 [key: string]: string 으로 사용되었는데 key값을 Category 타입으로 설정해주는 방법이 없을까요?  `export const KOREAN_CATEGORY: {
 [key: Category]: string;
}`

``` ts
export const CATEGORY: {
  [key in Category]: Category;
} = {
  korean: "korean",
  chinese: "chinese",
  japanese: "japanese",
  western: "western",
  asian: "asian",
  etc: "etc",
};

export const KOREAN_CATEGORY: {
  [key: string]: string;
} = {
  [CATEGORY.korean]: "한식",
  [CATEGORY.chinese]: "중식",
  [CATEGORY.japanese]: "일식",
  [CATEGORY.western]: "양식",
  [CATEGORY.asian]: "아시안",
  [CATEGORY.etc]: "기타",
};

export const RESTAURANT_DISPLAYING_FILTER: {
  [key in CategoryFilter]: CategoryFilter;
} = {
  ...CATEGORY,
  all: "all",
};

export const KOREAN_RESTAURANT_DISPLAYING_FILTER: {
  [key: string]: string;
} = {
  [RESTAURANT_DISPLAYING_FILTER.all]: "전체",
  [RESTAURANT_DISPLAYING_FILTER.korean]: "한식",
  [RESTAURANT_DISPLAYING_FILTER.chinese]: "중식",
  [RESTAURANT_DISPLAYING_FILTER.japanese]: "일식",
  [RESTAURANT_DISPLAYING_FILTER.western]: "양식",
  [RESTAURANT_DISPLAYING_FILTER.asian]: "아시안",
  [RESTAURANT_DISPLAYING_FILTER.etc]: "기타",
};
```

### IndexedDB
미션과는 다른 이야기일 수 있는데 localStorage를 공부를 하는 도중 indexedDB를 알게되었어요. 

제가 찾아보기로 indexedDB 에서는 개발자 도구에서 임의로 데이터 수정이 안되고, localStorage 보다 더욱 많은 데이터를 저장하고 활용할 수 있겠다 생각이 들었는데 indexedDB 는 왜 잘 사용하지 않는지에 대해 궁금하고 현재 미션에 대한 요구사항에서는 localStorage 보다 indexedDB 가 더욱 좋지 않을까는 궁금증이 있어요!

(제가 생각하기에는 클라이언트 측에서 저장할 데이터는 많지 않기에 사용하기 편한 localStorage 를 사용하는게 아닐까? 생각합니다!)
</details>

2024-03-08 22:03 UTC, yujo11 requested changes
안녕하세요 다르~

점심 뭐 먹지 미션 함께하게 된 유조입니다 잘 부탁드립니다 ㅎㅎ

>웹 컴포넌트의 개념을 처음 들어보고 작업했기에 어려운게 많았고 지금 돌이켜 생각해보니 잘 작업했는지 모르겠네요.. 🥲

웹 컴포넌트로 작업하는게 어렵다고 하셨는데 왜 이번 미션에서 웹 컴포넌트를 사용하셨는지 이유가 궁금합니다 ㅎㅎ 

### 궁금한 점

>현재 Category 관련 상수가 아래와 같이 4개가 있는데 "꼭 이렇게 4개로 만들어야하는가?" 와 "잘 사용하고 있는가" 에 대한 의문점이 있었어요! 그 이유는 공통된 요소가 있었기에 충분히 재사용할 수 있을거라 생각은 했지만 방법을 찾지 못했어요..

크게 억지스럽다고 느낀 부분은 없었는데요. all이 CATEGORY에 기본으로 추가되면 훨씬 간결해지겠다는 생각은 드네용

>KOREAN_CATEGORY 의 타입을 보면 저는 [key: string]: string 으로 사용되었는데 key값을 Category 타입으로 설정해주는 방법이 없을까요? export const KOREAN_CATEGORY: {  [key: Category]: string; }

아래처럼 사용할 수 있을거 같아요

<img width="555" alt="image" src="https://github.com/woowacourse/javascript-lunch/assets/61097373/92c21863-6a22-4abd-b2a3-f5551b854a1a">


>IndexedDB

IndexedDB의 경우 저도 존재만 알고 있고 한번도 사용해본 적이 없는데요 ㅎㅎ 

큰 데이터를 브라우저에 저장하며 관리 할 일도 많이 없고, localStorage와 비교해보면 API도 복잡하기 때문에 많이 사용되지 않는거 같아요. 특정한 상황에서 유용하게 사용 될 수도 있겠다는 생각을 해오고는 있는데 그게 어떤 상황일런지는 저도 잘 모르겠네요 😅


---

미션 진핸하느라 고생 많으셨습니다 다르~

코멘트 확인해보시고 다시 리뷰요청 부탁드려요~~ 👍 👍 👍

2024-03-13 01:58 UTC, pp449 reviewed
안녕하세요 유조 정성스러운 피드백 감사드립니다 🙇‍♂️
유조 덕분에 여러가지 키워드와 얕은 지식을 조금 채울 수 있게 되었던거 같아요 

이번주 테코톡 발표 준비하느라 피드백 반영이 늦어졌지만 잘 부탁드려요 😊

## 웹 컴포넌트를 사용한 이유
우선 이번 미션을 진행할 때 목표는 `컴포넌트의 단위를 묶고 중복되는 컴포넌트는 재활용하자` 였어요
그렇다면 어떻게 컴포넌트를 구현할것이고 어떻게 재사용하게 만들것인지에 대한 논의가 필요했어요.

우선 저번 미션을 진행하면서 createElement 메서드를 사용해서 엘리먼트를 만든다면 부모-자식간의 관계가 복잡해지면 코드 작성이 힘들고 가독성이 안좋아진다고 생각하였고 
비슷한 컴포넌트를 인자값을 기반으로 커스텀해서 사용하기 불편하다는 생각이 들었어요.

그래서 웹 컴포넌트를 사용하면 이런 고민들을 해결할 수 있을까? 생각해서 웹 컴포넌트를 사용해보았어요!

그런 이유도 있었지만 "웹 컴포넌트를 사용할까 말까?" 에 대한 고민을 했을 때 웹 컴포넌트에 대해 무지한 상태에서 웹 컴포넌트를 논하는게 않다고 생각하였고 실제로 구현해보면 조금 더 웹 컴포넌트의 장단점을 논할 수 있지 않을까는 생각에 공부 목적으로 적용한 점도 큰거 같아요!

## 웹 컴포넌트 사용 후 느낀점
### 장점
1. 컴포넌트별로 기능의 그룹화가 잘 되어있어 각 컴포넌트별 책임에 대해 확인하기 쉬웠어요
2. 아래와 같이 props child 를 받아서 사용할 수 있었기에 ModalBox 컴포넌트 사용성이 용의하여 재사용성이 높았고 가독성도 좋았던거 같아요
``` ts
<modal-box modal-id="restaurant-form-modal">
          <restaurant-form></restaurant-form>
</modal-box>
```
3. `<restaurant-header></restaurant-header> ` 와 HTML 코드 내 같이 태그로 컴포넌트를 정의하기에 재사용되지 않는 컴포넌트여도 태그 이름만 봐도 어떤 컴포넌트인지 추상화가 잘 되어있어 HTML 코드 내 가독성이 좋았어요

### 단점
1. 어트리뷰트로 값을 넘겨서 받기에 브라우저 런타임 시 HTML 태그 어트리뷰트의 값이 노출이 되는게 부담스러웠어요
2. 컴포넌트별 이벤트 기반으로 소통하는 방식이 불편했어요. 만일 컴포넌트끼리 이벤트로 소통할 일이 많아진다면 유지/보수 측면에서 어려울것 같았어요

바쁜 와중에도 귀한 시간 내주셔서 감사해요 다음 피드백부터는 조금 더 빠르게 반영하도록 노력하겠습니다! 😊

2024-03-13 10:16 UTC, yujo11 approved these changes
안녕하세요 다르~

그새 테코톡 발표를 하셨군요 우테코 때를 회상하면 미션하랴 테코톡 준비하랴 엄청 정신없었던 기억이 있는데 고생 많으셨습니다 ㅎㅎ 👍 👍 👍 

지난 번에 남긴 코멘트들 하나하나 꼼꼼하게 확인하고 반영해주셨군요 👍 웹 컴포넌트를 왜 사용했는지에 대한 가벼운 질문에도 꼼꼼하게 정리하고 답변주셔서 감사합니다 ㅎㅎ  👍 💯 💯 💯 

추가로 주신 질문들에 대한 답변과 변경된 코드를 보면서 소소한 코멘트들 추가로 남겼는데 확인해주시면 좋겠습니다!

이번 step은 여기서 이만 merge하고 다음 step으로 넘어가도 좋을거 같아요!

고생 많으셨습니다 다르 step2에서 다시 만나요~~~ 👍 👍 👍

2024-03-13 10:16 UTC, yujo11 commented on src/components/RestaurantForm.ts
> +    this.dispatchEvent(
>Event 와 CustomEvent 객체

오 꼼꼼히 공부하고 정리해주셨군요 ㅎㅎ 👍 👍 👍 

Event와 CustomEvent 객체의 가장 큰 차이는 위에 다르가 적어주신 내용인거 같아요. 앞으롣 특정 상황에 맞게 적절하게 선택해서 사용하시면 좋겠네요 ㅎㅎ 👍

2024-03-13 10:16 UTC, yujo11 commented on src/components/CategoryIcon.ts
> +  private isCategory(category: string): category is keyof CategoryToImagePath {
`category is keyof CategoryToImagePath`를 사용하게 되면 `boolean`으로 return type을 정의 했을 때와 다르게 `category`가 `CategoryToImagePath`의 key 중 하나인지를 TypeScript가 인지하여 변수를 더 정확하게 추론할 수 있습니다 ㅎㅎ

추가로 코드를 읽을 때 `boolean`을 사용하는 것보다 더 구체적이고 명확하게 코드의 의도가 전달되기도 하구요. 저는 개인적으로 코드의 의도를 최대한 명확하게 드러내는게 좋다는 생각을 가지고 있어서 `a is keyof A` 방식을 사용하는 것을 선호하는데요. 

두 가지 방식의 차이에 대해 명확히 인지하시고 다르의 의도가 코드를 통해 잘 드러내도록 작성해보시면 좋겠습니다 ㅎㅎ

2024-03-13 10:16 UTC, yujo11 commented on src/components/common/Modal.ts
> +  private handleFormModalAction(e: CustomEvent, modalId: string) {
저는 함수를 정의할 때 보통 함수의 타입을 먼저 작성하는 편이라 제가 작성한 함수는 모두 return type이 명시되어 있습니다 ㅎㅎ
ex)
```
// 1. 함수의 타입 작성 (내부에서 number가 반환되지 않아 에러가 발생하는 상태)
const sum = (a: number, b: number): number => {}

// 2 함수의 내부 로직 구현 
const sum = (a: number, b: number): number => {
  return a + b
}
```
이 부분은 취향에 따라 갈릴 수 있는 부분이라고 보지만 저는 작은 단위에서의 TDD라고 생각하고 함수 타입을 명시해주는걸 선호하는 편입니다. 

위에 적은건 제 개인적인 의견이니 이 부분은 다르가 코드를 더 많이 작성해보면서 다르만의 기준을 만들어가시면 좋겠네용~

2024-03-13 10:16 UTC, yujo11 commented on src/LunchApp.ts
> +customElements.define("modal-box", ModalBox);
이 부분은 꼭 이름이 일치해야 한다는 관점보다는 하나의 코드베이스에서 하나의 컨벤션이 유지되었으면 좋겠다는 생각으로 남긴 리뷰였습니다 ㅎㅎ

하나의 코드베이스 내에서 다양한 컨벤션이 공존하게 되면 코드를 보는 사람으로 하여금 쉽게 혼란을 느끼게 하는데요. 예를 들어 어떤 컴포넌트는 A로직으로, 어떤 컴포넌트는 B로직으로 구현되어 있다고 했을 때 새로운 컴포넌트를 구현하려고 한다면 어떤 로직으로 구현을 해야할지 고민이 필요하고, A로직으로 구현된 컴포넌트를 먼저 봤다면 다른 컴포넌트도 으레 A로직으로 구현되었을거라고 생각하기 때문에 다른 컴포넌트가 B로직으로 구현되어 있다면 다른 컴포넌트를 봤을 때 혼란을 느낄 수 있을거에요 ㅎㅎ

하나의 코드베이스에서 일관된 하나의 컨벤션이 유지되도록 신경 써보시면 좋겠습니다!

2024-03-13 10:16 UTC, yujo11 commented on src/components/common/SelectBox.ts
> +    const required = this.getAttribute("required") ?? "";
👍 👍 👍

2024-03-13 10:16 UTC, yujo11 commented on src/components/common/SelectBox.ts
> +    const required = this.getAttribute("required") ?? "";
OR 연산자(`||`)와 널 병합 연산자(`??`)는 얼핏 보면 비슷한 로직을 수행하는걸로 보일 수 있으나 동작과 쓰임이 분명히 다르기 때문에 앞으로도 신경써서 사용해보셨으면 좋겠네용 ㅎㅎ 👍

2024-03-13 10:16 UTC, merged