[1단계 - 음식점 목록] - 소파(차승하) 미션 제출합니다.
woowacourse/javascript-lunch pull request #124
Opened 2024-03-08 08:27 UTC by ss0526100

안녕하세요~ 브콜~ 미션 3 리뷰이 소파입니다.

(배포 링크)[https://ss0526100.github.io/javascript-lunch]

## 실행 방법

```
npm run start
```

## 메인 실행 흐름

index.js에서 전반적인 흐름 관리

## 궁금한 점

현재 컴포넌트 생성방식이 너무 꼬여있다는 생각이 듭니다.  그 이유는 event를 추가하는 시점이 애매해 통일성이 없기 때문이라고 생각합니다. 어떤 이벤트는 index.html에서 넣어주고, 어떤 이벤트는 컴포넌트를 생성할 때 넣어주기 때문입니다. 이벤트를 언제 어떻게 넣어주는 것이 좋을 지 궁금합니다. 

저는 평소에 이런 궁금한 점을 작성하는 것이 어렵습니다. 너무 근본적으로 질문하는 것은 정답이 없는 질문을 묻는 것 같고, 간단한 질문은 제가 조금 더 찾아보면 될 것 같아서 질문하기 꺼려집니다.

브콜은 평소에 궁금한 점을 어떻게 질문하시는 지 궁금합니다.

## 아쉬운 점

E2E 테스트를 포함한 어떤 테스트도 진행하지 못했습니다. 테스트는 리뷰 이후 추가하겠습니다.

기타 궁금한 사항 코멘트 달아놓겠습니다!

2024-03-08 08:30 UTC, ss0526100 commented on src/view/components/AddRestaurantForm.ts
> +  #urlFormItem: FormItem;
현재 값을 제출하는 이벤트를 위해 많은 private 필드를 활용하고 있습니다. 혹시 필드 수를 줄이는 방식이 있을지 궁금합니다.

2024-03-10 11:42 UTC, Tanney-102 requested changes
안녕하세요 소파!
리뷰가 많이 늦어 죄송합니다ㅜㅜ
작성해주신 코드 잘 보았습니다.
ui 요소들이 재사용 가능한 형태로 잘 분리된 것 같아요.
다만 조금 더 일관된 방식의 컴포넌트를 제공하면 좋겠다는 생각이 들었어요.
이벤트를 추가하는 방식에 통일성이 없다고 느끼신 것도 이러한 점에서 오지 않았을까 싶어요.
어떤 컴포넌트는 class 형태를 띄고 어떤 컴포넌트는 generate 같음 함수 형태를 띄기도 하네요.

컴포넌트에 대해 너무 많은 생각을 하신 나머지 이러한 구조가 나오지 않았나 싶습니다.
컴포넌트를 뭐라고 정의하시나요?
이런 저런 말로 표현은 할 수 있겠지만 결국 핵심은 `재사용 가능한 UI 모듈`이 아닐까 싶어요.
특정 영역을 그리는 함수, 업데이트 하는 함수만 하나의 모듈의 모아놔도 컴포넌트라 부르기에 충분하지 않나요?
이전 미션에서 학습하셨던 domain & ui 중 ui영역만 각 관심사 별 모듈로 분리하자는 생각으로만 접근했어도 조금 더 간결한 구현이 가능했을 것 같아요.

> 저는 평소에 이런 궁금한 점을 작성하는 것이 어렵습니다. 너무 근본적으로 질문하는 것은 정답이 없는 질문을 묻는 것 같고, 간단한 질문은 제가 조금 더 찾아보면 될 것 같아서 질문하기 꺼려집니다.

간단한 질문은 찾아보면 될 것 같다 => 직접 찾아보시면 판단이 빠르겠죠~
찾아봐서 해결되면 좋은거고 해결이 안된다면 애초에 소파에게 간단하지 않은 질문이었을테니까요 ㅎㅎ
근본적인 질문도 괜찮아요. 정답이 없는 질문도 물론 괜찮습니다.
간혹 `좋은 질문이 무엇이냐` 라든가 `질문 잘하는법` 같은 이야기를 하시는 분도 계신데 사실 학습하는 입장에서 조금 이른 얘기일 수도 있을 것 같네요. 사람마다 기술을 이해하는 수준이 다르고 정보를 이해할만한 배경도 다 다른데 해야할 질문 하지 말아야 할 질문을 구분부터 하기 시작하면 오히려 성장에 방해가 된다고 생각해요.
차라리 편하게 질문하시고 피드백을 받으시죠.
질문도 많이 던져보고 피드백을 받아봐야 늘지 않을까요?

2024-03-10 11:42 UTC, Tanney-102 commented on src/domain/RestaurantList.ts
> +    RestaurantList.#restaurants = new Map(restaurantEntries);
map로 관리하는 거 좋네요 👍

2024-03-10 11:42 UTC, Tanney-102 commented on src/domain/RestaurantList.ts
> +    if (category === CATEGORY_WITH_ENTIRE[0]) {
number index를 통한 접근 말고 의미 있는 key로 접근할 수는 없을까요?

2024-03-10 11:42 UTC, Tanney-102 commented on src/index.js
왜 이 친구만 js인가요~

2024-03-10 11:42 UTC, Tanney-102 commented on src/index.js
> +});
filterContianer를 셑렉하고 => append => 이벤트 붙이는 것까지 수행하는 모듈을 하나 따로 작성했으면 어땠을까 싶네요

2024-03-10 11:42 UTC, Tanney-102 commented on src/index.js
> +main.addEventListener("submit", (e) => {
이 submit 이벤트는 어느 form에서 발생하는 건가요? 해당form을 렌더하는 곳에서 이 핸들러도 작성되어야 하지 않을까요?

2024-03-10 11:42 UTC, Tanney-102 commented on src/utils/getLocalStorageItem.ts
> +    localStorage.setItem(key, stringifiedDefaultValue);
6번 라인이 필요한가요?

2024-03-10 11:42 UTC, Tanney-102 commented on src/view/components/FormItem.ts
> +  }
form element의 reset메서드 활용은 어려울까요?

2024-03-10 11:42 UTC, Tanney-102 commented on src/view/components/AddRestaurantForm.ts
> +  #urlFormItem: FormItem;
여기서 줄일 수 있는 필드가 있나요?
많다는 기준은 뭘까요? 줄여야 할 이유는요?

2024-03-11 08:45 UTC, ss0526100 commented on src/view/components/AddRestaurantForm.ts
> +  #urlFormItem: FormItem;
기존의 미션에서 private field를 2개 이하로 해라라는 말에 갖혀서 드렸던 질문이었습니다. 꼭 필요한 필드라면 사용해야한다는 생각이 들었네요.

2024-03-11 08:46 UTC, ss0526100 commented on src/index.js
구현상에 시간이 없어서 js로 만들었습니다.. ts로 바꿔서 제출하겠습니다!

2024-03-13 03:13 UTC, ss0526100 reviewed
리팩토링을 진행하다보니 코드의 구조가 많이 바뀌었네요... 기존 코드와 많이 달라져서 코드를 읽으시는데 부담이 되시진 않을까 걱정이 됩니다. 일단 리뷰요청 보내겠습니다!

2024-03-13 03:13 UTC, ss0526100 commented on src/controller/MainController.ts
> +import {
UI와 도메인 분리를 위해, 레스토랑 리스트를 추가할 때의 이벤트를 외부에서 주입해주었습니다.

또한 컴포넌트 간의 연결을 위해 두 컴포넌트가 상호작용하는 이벤트 역시 외부에서 주입해주었는데요.

외부에서 주입을 해주는 내용이 너무 많다보니 유연성은 높아졌지만 가독성이 떨어지지 않았나라는 생각이 딉니다.

주입 방식에 대한 브콜의 생각이 궁금합니다.

2024-03-13 03:13 UTC, ss0526100 commented on src/view/components/AddRestaurantForm/AddRestaurantForm.ts
> +import "./style.css";
모든 컴포넌트들을 클래스형으로 분리해주었습니다.

어떤 컴포넌트들은 컴포넌트들을 만드는 경우가 있어 컴포넌트가 많아졌는데요.

그래서 컴포넌트 폴더 관리가 어려워지 않을까에 대한 생각이듭니다.

계층적으로 폴더를 구분해 관리하고자 하는 방식도 생각해보았지만, 추후에 계층 구조가 복잡해지는 등, 여러가지 상황이 우려되어 일단은 하나의 폴더에서 컴포넌트들을 관리해보았습니다.

브콜은 어떻게 컴포넌트들을 관리하는 것이 좋다고 생각하시나요?(한 폴더에 넣기, 계층적으로 관리하기 등등..)

2024-03-13 17:15 UTC, Tanney-102 approved these changes
안녕하세요 소파!
깔끔하게 리팩터링을 해주셨군요!
확실히 더 일관성 있고, 역할에 맞게 각 모듈이 잘 분리되어 있는 코드가 된 것 같습니다.
질문 주신 내용 코멘트 드렸으니 확인 부탁드립니다!
이번 스텝은 머지하도록 하겠습니다. 고생 많으셨어요!

2024-03-13 17:15 UTC, Tanney-102 commented on src/controller/MainController.ts
> +import {
가독성 측면에서는 그렇게 문제될만한 수준은 아니라고 생각해요.
오히려 컴포넌트가 서로 의존하지 않아서 더 좋아 보입니다👍👍

2024-03-13 17:15 UTC, Tanney-102 commented on src/view/components/AddRestaurantForm/AddRestaurantForm.ts
> +import "./style.css";
컴포넌트가 컴포넌트를 가지고 있다는 건 AddRestaurantForm처럼 다른 컴포넌트를 멤버로 가지고 있다는 말씀이시겠죠?
확실하게 A컴포넌트가 B컴포넌트에서만 핸들링 되는 것이 보장이 된다면 계층을 두고 관리해도 괜찮다고 생각은 하는데요. 독립적이고 재사용 가능한 컴포넌트들을 설계한다는 관점에서는 하나의 폴더에 관리하는 방식이 더 나아보여요.
나중에 앱이 복잡해지면 기능 별로 먼저 분리하고 그 안에 관련 컴포넌트를 넣는다던지 하는 옵션도 있을 것 같습니다.
ex)
```
/A
    /components/...
/B
    /components/...
```

2024-03-13 17:15 UTC, merged