[1단계 - 음식점 목록] 리버(최재희) 미션 제출합니다.
woowacourse/javascript-lunch pull request #130
Opened 2024-03-08 08:45 UTC by 0jenn0

안녕하세요 샐리
이번 미션에서 페어와 함께 웹 컴포넌트를 학습하고 처음으로 웹 컴포넌트로 구현해보았는데,
타입스크립트에 대한 지식도 부족해서 학습과 구현에 있어서 시간이 예상보다 많이 소요되는 바람에 프로그래밍 요구 사항을 잘 맞추지 못했습니다...
2단계에서 열심히 리팩토링해보겠습니다..! 🙇‍♀️ 💦

### 실행 방법

```
npm i
npm run start
```

### 배포 링크

[🍴 리버 | 점심 뭐 먹지 배포 링크](https://0jenn0.github.io/javascript-lunch/dist)

### 폴더구조

+ 처음에 컴포넌트명 폴더 안에 html,css,js 파일들로 웹 컴포넌트를 구성하려 했는데 html를 module로 import하는 기능이 없어진 상태였고, 제공된 template 폴더 안의 `index.html`,`style.css`를 사용하게 중간에 수정하게 되어서 현재와 같은 폴더 구조가 되었습니다. 폴더를 없앴어야했는데 시간상 그러지 못했습니다..

### 아쉬운 점

+ 비즈니스 로직(`restaurantAPI`)에 대한 테스트 코드를 작성하지 못했습니다.
+ 이미 등록되어있는 음식점을 등록할 때 이미 등록되어있는 음식점인지 검증하는 부분을 구현하지 못했습니다.
+ 음식점 추가 모달창에서 추가하기 버튼을 눌렀을 때 `음식점이 추가되었습니다.`라는 토스트가 뜨게 하고싶었는데 하지 못했습니다.
+ figma에서 UI가 핸드폰같은 크기인데 이에대한 CSS 수정을 하지 못했습니다.

2024-03-09 07:11 UTC, liswktjs requested changes
안녕하세요 리버 
이번에 리뷰를 맡게된 샐리라고 합니다 

타입스크립트를 깔끔하게 선언하고 사용해주셨더라고요 👍
코드들도 전반적으로 깔끔했습니다 

다만 제안드리고 싶은 점들은 재사용 가능한 컴포넌트를 더 많이 만들어 보시면 좋을 것 같습니다 
현재, 큰 단위로 컴포넌트들이 나누어져 있는데 
얼마든지 작은 단위로 분리가 가능해보입니다 
예를 들어, dropdown,button 더 나아가서는 input,  title, 음식 이미지 Icon  등등으로 분리를 할 수 있을 것 같습니다 

꼭 웹 컴포넌트를 사용하실 필요 없이 
재사용 가능한 작은 단위로 컴포넌트를 나눠보는 연습을 이번 미션을 통해서 해보시면 추후 리액트 등으로 개발을 하실 때에도 도움이 많이 될 것 같습니다  🔥 

나머지 내용들은 코멘트에서 확인부탁드립니다! 
(테스트 코드도 다음 요청에 기다리고 있겠습니다 👀 )

2024-03-09 07:11 UTC, liswktjs commented on src/component/modalComponent/ModalComponent.js
> +      this.emit(EVENT.clickedModalSubmitButton);
이부분에 코멘트에 작성해주셨던 것 처럼 중복 검사를 포함해서 유효성 검사가 필요해보입니다! 
현재는 input에 required를 붙여서 입력 처리를 해주셨지만 
html은 유저가 직접 조작이 가능하기 때문에 required문을 지우게 되면 
![스크린샷 2024-03-09 오후 3 59 48](https://github.com/woowacourse/javascript-lunch/assets/60773373/69af9311-2ca7-4177-809e-ee36fa429043)
이런 식으로 빈값이 저장 가능해지게 됩니다 

추가로 storage에 저장하는 값이 다 보니 따지고 보면 서버에 저장 요청을 보내는 데이터들이다 보니  유효성 검사도 꼭 필요할 것 같습니다

2024-03-09 07:11 UTC, liswktjs commented on src/component/modalComponent/ModalComponent.js
> +      restaurant.link = form.link.value;
![스크린샷 2024-03-09 오후 4 01 18](https://github.com/woowacourse/javascript-lunch/assets/60773373/fbaa9053-371e-45e8-889d-cd816a279ea8)

링크의 경우에도 빈값이 아닌 경우 유효성을 체크해서 에러 메세지를 보여주면 유저 사용성도 올리고 유효한 값을 입력받을 수 있게 될 것 같습니다

2024-03-09 07:11 UTC, liswktjs commented on src/component/modalComponent/ModalComponent.js
> +
추가로 제안드리고 싶은 기능은 
필수 입력 항목들이 입력되기 전까지는 제출하기 버튼을 비활성화 해주면 좋을 것 같습니다 
![스크린샷 2024-03-09 오후 4 02 31](https://github.com/woowacourse/javascript-lunch/assets/60773373/13996fa9-5aea-4ff6-9110-1bb2cd8c0526)

2024-03-11 06:02 UTC, 0jenn0 commented on src/component/baseComponent/BaseComponent.js
> +  }
`<template>`태그는 웹페이지에 직접적으로 렌더링되지 않지 않고 html 코드를 저장하는데만 사용된다고 알고있습니다
그렇기 때문에 이 부분에서 사용자가 dom을 직접 조작할 수 없다고 생각했습니다!

2024-03-13 17:27 UTC, 0jenn0 commented on src/component/modalComponent/ModalComponent.js
> +
`<button>`태그의 `disabled` 속성을 이용하여 구현했습니다
 ux적으로 더 좋아진것같아요 감사합니다!

2024-03-13 17:27 UTC, 0jenn0 commented on src/component/selectFilterComponent/SelectFilterComponent.js
> +  render(instance, filterType) {
기존 컴포넌트들을 typescript로 변환하는것이 너무 어려워서 다시 처음부터 타입스크립트로 구현해보았습니다!

2024-03-14 07:39 UTC, 0jenn0 commented
안녕하세요 샐리
일단 너무 늦어서 죄송하다는 말씀 드리고싶습니다..

----

## 1. 늦은 이유
미션을  다시 처음부터 다시 시작했습니다. 다시 시작한 이유를 아래와 같습니다.
### 1-1 ) 웹 컴포넌트에 대한 이해 부족
  + 리뷰를 반영하면서 컴포넌트를 타입스크립트로 수정해야했는데, 기존 웹 컴포넌트들 안에 이벤트들과 dom 요소들을 등등 타입스크립트로 변환하려하는데 못했습니다
### 1-2 ) customEvent,dispatch를 사용하지 않고 구현해보고 싶었습니다.
  + 웹 컵포넌트 안에서 customEvent들로 서로 이벤트 발생과 데이터 교환이 이루어 지는게 가독성이 안좋다 생각했기때문입니다.
  + `lunchAppController`를 만들어서 이벤트 핸들러 및 이벤트 할당했습니다.


## 2. 양해 부탁드리는 점
+ 아무래도 시간이 촉박했기에 하루정도 시간을 할애해서 다른 브랜치에 처음부터 짜보다가 안되면 그래서 수정 초반부 git commit이 뭉텅이로 올라와져있는데 이 점 양해부탁드립니다. 죄송합니다


## 3. 새로 구현한 점

### 컴포넌트 구조

### RestaurantList 
1. RestaurantList 처음 생성시 음식점 초기값들과 로컬스토리지에 들어있는 데이터들을 로드합니다.
2. Filter컴포넌트들이 RestaurantList안의 category,sorting 필드 값을 수정합니다.
3. RestaurantList는 자신의 category,sorting 값이 수정되면 자신이 가지고있는 음식점 데이터를 그에 맞춰 갱신합니다.
4. 음식점 데이터가 갱신되면 음식점 목록을 렌더링합니다.

| 순서 | 모듈명                    | 상호작용 설명                                                                                              |
|-----|-------------------------|---------------------------------------------------------------------------------------------------------|
| 1   | `restaurantAPI`         | 초기 음식점 데이터 로딩: `RestaurantList`는 애플리케이션 시작 시 `restaurantAPI`를 통해 초기 음식점 데이터를 로딩합니다.      |
| 2   | `CategoryFilterComponent` | 카테고리 선택 반영: 사용자가 선택한 카테고리는 `CategoryFilterComponent`를 통해 `RestaurantList`로 전달되어, 데이터를 해당 카테고리에 맞게 필터링합니다. |
| 3   | `SortFilterComponent`   | 정렬 기준 선택 반영: 사용자가 선택한 정렬 기준은 `SortFilterComponent`를 통해 `RestaurantList`로 전달되어, 데이터를 해당 기준에 맞게 정렬합니다.    |
| 4   | `RestaurantList`        | 데이터 처리: `RestaurantList`는 필터링 및 정렬 로직을 수행하여 최종 음식점 데이터 목록을 준비합니다.                                |
| 5   | `RestaurantCardComponent` | 화면 렌더링: 준비된 음식점 데이터는 `RestaurantCardComponent`를 사용하여 사용자에게 표시되는 음식점 정보 카드로 변환되어 화면에 렌더링됩니다.    |
| 6   | `LunchAppController`     | UI 총괄 관리: `LunchAppController`는 전체 UI 렌더링 과정을 총괄하며, 필요에 따라 `RestaurantList`를 업데이트하고, 관련 컴포넌트를 조정합니다.   |


## 4. 해결하지 못한 점

### 4-1 ) 테스트 코드
이번에도 도메인 테스트 코드를 구현하지 못했는데요...!
`RestaurantList` 안에서 dom요소를 렌더까지 하기 때문에, jsdom 이슈가 있었는데 시간이 촉박해서 해결하지 못하고 다시 리뷰를 신청하게되었습니다.. RestaurantList에서 dom요소를 분리해야할것같은데 이에 대한 해답을 아직 못찾았습니다.

## 5. 부족하다 느끼는 점
### 5-1 ) 코드의 통일성 부재
+ 새로 컴포넌트들을 분리하게되었는데, 
  + 어떤 컴포넌트는 이벤트를 컴포넌트 안에서 달아주고, 어떤 컴포넌트는 외부에서 이벤트를 달아줍니다.
  + 컴포넌트들의 getTemplate함수가 반환하는 type이 다릅니다.(string,DocumentElement )

### 5-1 ) Modal이 너무 복잡합니다.
  + 모달창에서 컴포넌트들의 이벤트들을 모두 다루다 보니 너무 복잡해진것같습니다.
 
그 외에 사항들은 코드 코멘트로 남기겠습니다 감사합니다

2024-03-14 11:57 UTC, liswktjs commented on src/component/baseComponent/BaseComponent.js
> +  }
아하 그렇군요 그렇다 해도 재사용한 컴포넌트를 만들때 Template을 활용한 string으로 선언해야하냐에 대해서는 의문이 있긴합니다 
현재 리버가 개발해준 곳을 보면 template의 경우 string이다 보니 innerHTML을 통해서 붙일 때는 편리할 수 있지만 유지보수와 디버깅 측면에서는 어려움이 있다고 생각합니다 
예를 들어 문자열이다 보니, < 을 닫지 않아도 코드 단 에서는 그 에러를 알아차릴 수 없게 됩니다 
실행을 시켜야만 해당 template이 제대로 잘 작성이 되었는지 확인을 할 수 있죠 
이런 측면에서 생각을 해본다면 string으로 dom을 관리하는 건 어려움이 있을 수 있습니다

2024-03-14 13:06 UTC, liswktjs approved these changes
안녕하세요 리버
1차 미션 피드백 반영 수고하셨습니다! 

컴포넌트 단위를 잘 분리해서 오신 것 같습니다 👍
추가적인 코멘트들도 달았으니 2단계 때 같이 반영해주시면 좋을 것 같습니다 

innerHTML을 사용하긴 하셨지만, web component를 활용해서 잘 구현을 해오셨더라고요 
다만, innerHTML안에 넣어주는 값이 string이다 보니 오타가 나거나 했을 때 코드 단에서 바로 확인하기 힘들다는 단점이 존재합니다 관련해서는 코멘트에 더 자세히 남겼으니 확인 부탁드려요 👀


추가로 변경된 커밋들을 코멘트 부분에 같이 달아주시면 소통이 더 쉬워질 수 있을 것 같아요 
다음 리뷰 때 부터는 커밋 번호들을 같이 붙여 주는 것도 추천 드립니다  🧚

2024-03-14 13:06 UTC, merged

2024-03-18 06:48 UTC, 0jenn0 commented on src/constants/constants.ts
> +} as const;
저도 쓰면서 뭔가 어색하다 생각했는데 index로 바꾸면 import 경로가 깔끔하게 폴더에서 끝나는군요 
알려주서 감사합니다~!

2024-03-18 06:51 UTC, 0jenn0 commented on src/components/CategoryIconComponent.ts
> +        `;
앗 그러게요 왜 button으로 했을까요 잘 못 적은것같습니다.. 바로 수정했습니다!

2024-03-18 07:44 UTC, 0jenn0 commented on src/components/CategoryFilterComponent.ts
> +      restaurantList.setCategory(selectedCategory);
반영 커밋 주소 : 9829f47bc0e4eeffd97e212de7f14f9d7443f107

수정했습니다!

2024-03-18 07:44 UTC, 0jenn0 commented on src/components/AddButtonComponent.ts
> +    template.innerHTML = /*html*/ `
이에 대한 내용은 2단계 pr 메시지에 적어보았습니다!

2024-03-18 07:44 UTC, 0jenn0 commented on src/components/ModalComponent.ts
> +  const buttonComponent = new ButtonComponent();
반영 커밋 주소 : 4fe2cf2b5157caeac1465b315ebd4302d2ddfe78
모달창 밑에 버튼들을 컴포넌트를 이용해서 구현해볼려다가 포기했었는데 그 과정에서 남은 흔적같습니다..
삭제했습니다!

2024-03-18 07:44 UTC, 0jenn0 commented on src/components/ModalComponent.ts
> +            }
반영 커밋 주소 : 82371223f4caf8941562bb9372a4fe19051c3a89

이번에 HTMLelement로 컴포넌트 구현 방법을 바꾸면서 이벤트 핸들링이 쉬워져서 빠르게 분리할 수 있었습니다!

2024-03-18 07:44 UTC, 0jenn0 commented on src/controller/lunchAppController.ts
> +    this.$filterContainer = document.querySelector('.restaurant-filter-container') as HTMLElement;
반영 커밋 주소 : 4ab541460d13ae91aaee465e605d04ab5413331f

type 에러 뜨는것을 바로 없앨려는 생각만해서 as 타입 단언을 해준것같습니다.. 앞으로는 타입스크립트를 타입스크립트답게 쓸려는 노력해보겠습니다!

2024-03-18 07:44 UTC, 0jenn0 commented on src/domain/restaurantAPI.ts
> +    }
반영 커밋 주소 : c9349ac1ebee89af69c74fdaa7b409ab248302f6
return 문을 잊었던것같습니다 짚어주셔서 감사합니다!

2024-03-18 07:44 UTC, 0jenn0 commented on src/validator/restaurantInfoValidator.ts
> +    return true;
커밋 반영 주소 : de6b57dbeab5fff4053e1a9c5520fcc63964f8b7
프리코스 때 부터 매직 넘버 사용하지 않기를 배워왔는데 이번에는 잊었네요 💦 
바로 수정했습니다 감사합니다