[1단계 - 음식점 목록] - 리안(오혜린) 미션 제출합니다.
woowacourse/javascript-lunch pull request #132
Opened 2024-03-08 08:48 UTC by ooherin

2024-03-10 11:53 UTC, ooherin commented on cypress/e2e/RestaurantDBService.cy.ts
> +    cy.stub(localStorage, 'getItem', () => JSON.stringify(restaurants));
로컬 스토리지를 테스트하기 위해 stub을 사용하였습니다! 이렇게 까지 해서 로컬 스토리지의 입출력을 테스트하는 것이 맞는 방식인지 궁금합니다!

2024-03-10 11:53 UTC, ooherin commented on src/components/Input/Input.ts
> +    this.outerHTML = $input.outerHTML;
커스텀 엘리먼트(웹 컴포넌트)를 사용하면 커스텀 엘리먼트로 한번 감싸지는 문제가 있습니다. 이를 막기 위해 outerHTML 을 사용해 감싸진 태그를 없애주었습니다!

2024-03-10 11:53 UTC, ooherin commented on src/components/NewRestaurantModal/NewRestaurantModal.ts
> +      (this.#form.elements.namedItem('distance') as HTMLSelectElement).value.slice(0, -3),
이 부분은 '3' 을 '3분 내'로 고치기 위해 사용했는데, 이렇게 하지말고 처음부터 select의 옵션의 text와 value 값을 분리하는 것이 좋을까요?

2024-03-10 12:09 UTC, ooherin commented
커밋 [dc2dfb7](https://github.com/woowacourse/javascript-lunch/pull/132/commits/dc2dfb76097f26e2ee358a500251d7e0e4dca96e) 부터 1단계 PR 이후 리팩토링을 진행하였습니다!

2024-03-10 18:32 UTC, iborymagic requested changes
안녕하세요 리안! 고생 많으셨습니다 👏👏
우선, 리뷰가 많이 늦어진 점에 대해 사과드립니다. 

PR에서 다소 걱정을 내비치신 것과 달리, 굉장히 잘 구현해주셨다고 생각합니다.
컴포넌트의 재사용성을 고민하신 모습이 잘 보였고, 결과도 훌륭합니다. 타입스크립트도 간결하게 잘 사용해주셨구요. 
리안이 다음에 리팩토링한다고 말씀해주신 부분들도 기대해보도록 하겠습니다. 질문주신 부분에 대해 답변 드릴게요.

1. DOM을 다루다보면 어쩔 수 없이 as를 사용해야하는 경우가 있습니다. 예를 들면, value 값을 사용하고 싶은데 querySelector의 return type인 Element에는 value가 없다던가 하는 경우에요. 그것보다는, 현재 as를 사용함으로써 querySelector가 null인 경우까지 덮어버리는 것이 문제라고 생각됩니다. 아래 코멘트에서 조금 더 자세한 내용 언급하겠습니다.
2. 요런거는 사실 스스로 검색해보시고 해결책을 찾는 연습을 자주 해보셔야 합니다. 생각보다 [공식문서](https://docs.cypress.io/guides/tooling/typescript-support#Install-TypeScript)만 봐도 금방 답이 나오는 경우가 많습니다. tsconfig.json의 include를 보시면 src로 지정해놓으셨는데, cypress 디렉토리가 src 바깥에 있기 때문에 타입을 인식하지 못하는 상태인 것 같습니다. 공식 문서에 나온대로 tsconfig를 고쳐보시고, 에러에 나와있는대로 @types/jest를 설치한 후에 restart ts server를 해보시면 아마 해결되지 않을까 싶습니다. (대답 안해드리는게 더 도움되시겠지만.. 늦었으니까 이번에만 답변드립니다 🙄)

코멘트로 달아드린 내용들도 확인해주시고, 다시 리뷰 요청 부탁드려요.
리뷰가 너무 늦어진 점에 대해 다시 한 번 죄송하다는 말씀 드립니다. 🙏

2024-03-11 02:46 UTC, iborymagic approved these changes
일단 이번 PR은 규칙 상 머지를 바로 하도록 하겠습니다. 리뷰 내용은 2단계에서 반영해주시면 될 것 같습니다!

2024-03-11 02:46 UTC, merged

2024-03-11 02:59 UTC, ooherin commented
> 일단 이번 PR은 규칙 상 머지를 바로 하도록 하겠습니다. 리뷰 내용은 2단계에서 반영해주시면 될 것 같습니다!
> 

네 알겠습니다! 감사합니다

2024-03-11 03:31 UTC, ooherin commented on cypress/e2e/RestaurantDBService.cy.ts
> +    cy.stub(localStorage, 'getItem', () => JSON.stringify(restaurants));
맞습니다! localStorage가 사실상 이 미션에서 DB의 역할을 하고 있기 때문에, stub을 사용해서 DB에 저희가 원하는 대로 데이터가 잘 들어가고 나오는지 테스트를 진행한 것입니다! localStorage.getItem 을 테스트한 이유는 restaurantDBService.set을 테스트하기 위함이었습니다. 근데 이렇게 복잡하게 테스트할 로직이 아니었던 것 같다는 생각도 듭니다! step2에서는 더 유용한 테스트를 설계하기 위해 노력하겠습니다 🙂

2024-03-11 03:37 UTC, ooherin commented on .prettierrc.js
> +};
죄송한데 EOL을 조심하라는 게 어떠한 의미일까요? 페어는 Window, 저는 MacOS가 작업환경이어서 통일성을 위해 LF로 설정해주었습니다. auto로 설정하면 각 운영체제에 맞게 유연하게 변경되는 것 같은데, LF로 강제하는 것보다 auto가 더 좋은 작업  협업 방식일까요?

2024-03-11 03:38 UTC, ooherin commented on cypress/unit/Restaurant.cy.ts
> +  it('성공 케이스', () => {
테스트명을 간과했었네요! 테스트명을 쓸 때는 더 자세하게 쓰도록 하겠습니다!

2024-03-11 03:40 UTC, ooherin commented on src/components/BaseComponent.ts
> +  }
optional이 편리해서 많이 썼었는데, 그러한 단점이 있겟네요! 간과했던 부분인 것 같습니다. `DOM이 null일 수도 있다`는 사실을 명심하고 걸러주도록 하겠습니다!

2024-03-11 03:45 UTC, ooherin commented on src/components/NewRestaurantModal/NewRestaurantModal.ts
> +      };
두개는 필수 조건이 아닌 선택 사항이라서 그렇게 했습니다! 원래 저 코드는 if 문으로 해당 변수가 있는지 확인하고 객체에 넣어주는 로직이었으나, 위와 같이 간소화했습니다😄

2024-03-11 04:57 UTC, ooherin commented on src/components/NewRestaurantModal/NewRestaurantModal.ts
> +  #submitForm() {
그 부분을 신경 쓰지 못했던 것 같습니다 언급해 주셔서 감사합니다😄

2024-03-11 05:00 UTC, ooherin commented on src/components/NewRestaurantModal/NewRestaurantModal.ts
> +class NewRestaurantModal extends NewRestaurantModalView {
extends가 아니라, 그렇게 레이어를 분리를 하는 방법도 있겠네요! 참고하도록 하겠습니다

2024-03-11 05:02 UTC, ooherin commented on src/components/Header/Header.ts
> +      BasicModal.blockModalBodyScroll();
아하 그래야 통일성이 있겠네요! 반영하겠습니다😀

2024-03-11 05:02 UTC, ooherin commented on src/domains/services/RestaurantDBService.ts
> +  getFromRestaurantList(category: Category, sortCriteria: keyof typeof CONDITIONS.SORT_CRITERION) {
네 좋은 것 같습니다 어디선가 또 쓰일 타입일 것 같아서요! 분리를 하는 것이 관심사 분리에도 좋겠죠!

2024-03-11 05:03 UTC, ooherin commented on src/types/Restaurant.d.ts
> +export type SortCriteria = keyof typeof CONDITIONS.SORT_CRITERION;
사실 이 부분은 생각없이 파일명을 지운 것 같습니다! 일반 파일명은 d.ts가 아닌 ts로 하겠습니다. 이유는 한번 찾아볼게요!

2024-03-11 05:03 UTC, ooherin commented on src/constants/Condition.ts
> +} as const;
통일하겠습니다:)

2024-03-11 06:15 UTC, ooherin commented on src/components/Header/Header.ts
> +      BasicModal.blockModalBodyScroll();
공감합니다!

2024-03-11 06:16 UTC, ooherin commented on src/domains/services/RestaurantDBService.ts
> +  getFromRestaurantList(category: Category, sortCriteria: keyof typeof CONDITIONS.SORT_CRITERION) {
이미 만들어져 있었는데 사용을 안했군요..😂 언급 감사합니다!

2024-03-11 08:10 UTC, ooherin commented on src/components/NewRestaurantModal/NewRestaurantModal.ts
> +    );
앗 유효하지 않은 링크를 넣어도 입력되는 군요..ㅠㅠ