[1단계 - 음식점 목록] - 마루(박규한) 미션 제출합니다.
woowacourse/javascript-lunch pull request #139
Opened 2024-03-08 08:56 UTC by rbgksqkr

안녕하세요 샐리! 잘부탁드립니다! 세번째 페어 프로그래밍을 진행하여 미션을 수행하였습니다.

가장 중요하게 생각한 점은 `컴포넌트의 모듈화와 재사용성` 이였습니다. 모든 부분을 컴포넌트화시키기보단 정적인 부분은 그대로 두고, 데이터값에 따라 다른 컴포넌트가 생성되는 로직을 구현하기 위해 노력하였습니다.

cypress로 도메인 로직만 단위 테스트 작성 완료하였고, 도메인 로직은 typescript를 사용하였고 dom 관련 로직은 javascript를 사용하여 미션을 구현하였습니다. 2단계 미션에서 DOM 관련 로직도 ts 파일로 수정하고, cypress로 e2e 테스트 작성 예정입니다.

이전 프로그래밍 요구사항에 mocking을 사용하지 말라는 요구사항이 있었습니다. 그때는 사용했던 jest.fn()을 제거하였는데 `테스트하기 쉬운 코드를 고민해보라` 는 의미로 요구사하을 이해하였습니다. 하지만 이번에는 LocalStorage를 DB 대신 사용하였고, `테스트할 때마다 DB 작업을 하는 건 비효율적` 이라고 생각하여 localStorage의 getItem과 setItem을 cypress stub을 활용하여 mocking하였습니다.

# **✅ 구현사항**

구현사항은 다음과 같습니다.

### **domain**

**Restaurant** 

- 음식점에 데이터를 필드값으로 갖고 있고 카테고리와 일치하는지를 Restaurant의 역할로 판단하여 isMatchedCategory 메서드 사용

**RestaurantList** 

- 음식점 목록을 새로고침해도 유지하기 위해 LocalStorage 에서 데이터를 가져옴
- localStorage에 restaurants 데이터가 있으면 localStorage에서 가져오고, 없으면 초기값으로 설정
- 카테고리를 인자로 받아 this.restaurants를 필터링하는 메서드
- 정렬된 데이터를 가져오는 getSorted 메서드
---
### **components**

**Restaurant**

- 입력값으로 들어오는 음식점 데이터에 따라 동적으로 생성되는 음식점 컴포넌트

**SelectBox**

- option을 인자로 받는 select 컴포넌트
- select가 홈에서 2개, modal에서 2개 사용되고 있어서 재사용성 극대화
---
### **eventHandler**

**HomeEventHandler**

- 홈화면에서 사용되는 이벤트 핸들러
- 우측 상단 버튼 클릭 시 modal open 등록

**ModalEventHandler**

- 모달화면에서 사용되는 이벤트 핸들러
- form 제출, modal 닫기 이벤트 리스너 등록
---
# **💭** 질문사항

### **컴포넌트 생성 기준**

저희는 모든 부분을 컴포넌트화시키지 않고 `재사용되고 모듈화시킬 수 있는 경우에만 컴포넌트를 적용` 하였습니다. 그게 학습한 컴포넌트의 의미에 적합하다고 생각하였습니다. `동적인 부분과 정적인 부분을 분리` 하여 최대한 정적인 데이터는 정적 파일인 HTML로 유지하였습니다.

한편으론 HTML + vanila JS보다 리액트 형태가(jsx) 익숙해서 그런지, HTML을 모두 컴포넌트로 묶는 게 깔끔하고 예측가능하다는 생각이 들기도 했습니다! 그래서 컴포넌트로 묶은 기준이 합리적인지 궁금합니다!

### **innerHTML vs createElement vs insertAdjacentHTML**

innerHTML이 XSS 공격에 취약하다는걸 알고있는데, 컴포넌트화시켰을때 createElement를 사용하여 만드는 경우 코드양이 많아지고 가독성이 떨어진다는 생각이 들었습니다. 이 부분에 대해 어떻게 생각하시는지도 궁금합니다!

### **ModalEventHandler(handleCategoryFilter, handleSortingFilter)**

SelectBoxComponent 를 사용할 때 필터링 eventHandler를 현재 index.js에서 불러오고 있는데, 현재 분리한 것처럼 ModalEventHandler에서 불러오려고 했는데 제대로 동작하지 않았습니다.

```js
  new SelectBoxComponent({
    $target: $restaurantFilterContainer,
    attributes: FILTERED_CATEGORY_ATTRIBUTE,
    eventHandler: handleCategoryFilter,
    options: FILTERED_CATEGORY,
  });
```
modalEventHandler에서 불러오는게 깔끔할 것 같은데 제대로 태그를 가져오지 못했습니다. 구조가 잘못된 걸까요 아니면 제가 DOM 생성 시점을 다르게 생각한 것인지 이유가 궁금합니다!
```js
  new SelectBoxComponent({
    $target: $restaurantFilterContainer,
    attributes: FILTERED_CATEGORY_ATTRIBUTE,
    eventHandler: modalEventHandler.handleCategoryFilter,
    options: FILTERED_CATEGORY,
  });
```

2024-03-09 08:55 UTC, liswktjs requested changes
안녕하세요 마루 
이번에 리뷰를 맡게된 샐리라고 합니다 

> 컴포넌트 생성 기준

이번 미션의 목표가 " 정적으로 렌더링할 영역과 동적으로 렌더링할 영역을 구분해서 고민한다." 인 점을 고려해보았을 때 고민을 많이 해주시고 적용해주신 것 같아요 
다만, 버튼이나 sort dropdown과 같은 경우에는 현재 서비스 내에서도 2개씩 중복되어서 사용되고 있어요 중복되어 사용되는 컴포넌트는 분리해주는 것이 좋다고 생각합니다 

> innerHTML vs createElement vs insertAdjacentHTML

마루가 말해준 것 처럼 innerHTML은 XSS공격에 취약합니다 
crateElement가 코드량이 많아지기는 하지만 
createElement를 사용하여야 한다고 생각합니다 

createElement들을 util로 함수를 만들어서 활용하거나 컴포넌트를 작은 단위로 재사용할 수 있게 분리하면 코드 양도 어느 정도 줄일 수 있을 거라고 생각됩니다 
예를 들어 button 단위의 컴포넌트를 만들 때 이곳에서 createElement를 호출하고 이후에 button을 사용할 일 이 있을 때는 따로 createElement 코드를 작성해줄 필요 없이 button 컴포넌트를 호출하면 중복을 제거할 수 있습니다! 

> ModalEventHandler(handleCategoryFilter, handleSortingFilter)

해당 질문은 제가 이해가 잘 안 되어서 😅 좀 더 자세히 설명해줄 수 있나요? 
eventHandler 함수들을 modalEventHandler에서 가져와서 사용하고 싶은데 그렇게 안 된다는 거 맞을까요? 
만일 후자라면, handleCategoryFilter가 modalEventHandler에 위치해야할 이유가 있을까요? 

추가로 element 들에 undefined가 들어간 부분들이 있었습니다 🤔
한 번 확인해보시고 제거해주시면 좋을 것 같습니다 👍
![스크린샷 2024-03-09 오후 4 53 24](https://github.com/woowacourse/javascript-lunch/assets/60773373/5770c406-dfa7-40f7-9cbe-c041a512794a)

2024-03-09 08:55 UTC, liswktjs commented on src/components/Restaurant.js
> +const RestaurantComponent = information => {
여기 information에 대해서도 타입을 명시해주면 좋을 것 같습니다 

혹은 이곳에서 사용되는 값들이 정해져 있으니 구조 분해할당을 활용해주는 것도 좋은 방법일 것 같습니다

2024-03-09 08:55 UTC, liswktjs commented on src/components/Restaurant.js
> +};
여기도 한번 createElement를 사용해서 구현해보면 좋을 것 같습니다

2024-03-09 08:55 UTC, liswktjs commented on src/index.js
> +new ModalEventHandler(restaurantList);
이부분 로직 정돈이 필요해보입니다 ! 
함수로 묶을 수 있는 부분은 함수로 분리해서 묶어주면 좋을 것 같아요

2024-03-09 08:55 UTC, liswktjs commented on src/index.js
> +  // 홈화면 select 생성
init 부분도 주석 처리해주신 단위별로 함수로 묶어서 호출해주면 좋을 것 같습니다

2024-03-09 08:55 UTC, liswktjs commented on src/components/SelectBox.js
> +    this.eventHandler = eventHandler;
제사용성을 위해서 eventHandler까지 넘겨주고 있었군요 👍

2024-03-09 08:55 UTC, liswktjs commented on src/components/SelectBox.js
> +  }
이 부분도 타입을 구조분해할당으로 받아오면서 타입 선언까지 해주면 좋을 것 같아요 

추가로 이부분을 createElement로 선언해서 map을 돌리면서 appendChild를 해주면 
코드 중복을 최대한 제거할 수 있어 보입니다

2024-03-09 08:55 UTC, liswktjs commented on src/components/SelectBox.js
> +    this.$target.insertAdjacentHTML(
insertAdjacentHTML도 innerHTML과 동일하게 xss 위험이 있는 걸로 알고 있습니다!

2024-03-09 08:55 UTC, liswktjs commented on src/eventHandler/ModalEventHandler.js
> +    const $restaurantForm = document.querySelector('form');
앞서 한 코멘트와 동일하게 element를 가져올 때는 null일 수 있기 때문에 점검해주는게 필요하다고 생각합니다 

element가 제대로 null이 아닌지 점검하는 util함수를 만들어서 활용해주는 것도 방법일 것 같습니다! 
```
const getElement = (id: string)=> {
  const element = document.querySelector(id);
  if(element === null){
    throw Error('not found')
  }
  return element
}
```

2024-03-09 08:55 UTC, liswktjs commented on src/eventHandler/ModalEventHandler.js
> +    const restaurantInformation = new Restaurant({ category, name, distance, description, link });
이부분에 유효성 검증이 필요해보입니다 input에서 required를 주고 있긴 하지만 유저가 dom을 직접 조작할 수 있기 때문에 다음과 같이 required를 제거하게 되면 빈 값을 저장할 수 있게 됩니다 
이런 경우에 대해서 검증 작업이 필요해보입니다! 

![스크린샷 2024-03-09 오후 5 24 39](https://github.com/woowacourse/javascript-lunch/assets/60773373/0ae3d65e-0147-46bc-a579-6888da097dbb)

2024-03-09 08:55 UTC, liswktjs commented on src/eventHandler/ModalEventHandler.js
> +    const link = $restaurantForm.elements.link.value;
참고로 링크의 경우에는 정해진 형식이 있기 때문에 
유저가 값을 입력했을 경우에는 유효성을 검증해주고 에러 메세지를 보여주는 것도 유저의 사용성을 높이는데 도움이 될 수 있을 것 같습니다 

![스크린샷 2024-03-09 오후 5 26 32](https://github.com/woowacourse/javascript-lunch/assets/60773373/994a7b7f-3a10-474f-9d87-63339d9cd1ca)

2024-03-09 08:55 UTC, liswktjs commented on src/eventHandler/ModalEventHandler.js
> +    const restaurantInformation = new Restaurant({ category, name, distance, description, link });
추가로 시간이 된다면 
유저가 필수값을 입력하지 않은 경우에는 추가하기 버튼을 비활성화 시키면 좋을 것 같습니다 
![스크린샷 2024-03-09 오후 5 27 59](https://github.com/woowacourse/javascript-lunch/assets/60773373/71bf12b2-a990-4f1c-876a-0e45b3bf9cca)

2024-03-09 08:55 UTC, liswktjs commented on src/eventHandler/ModalEventHandler.js
> +}
이 함수의 역할이 category filter에 따라서 식당 리스트를 재 랜더링 해주는 것 같아요! 
그렇다면 함수명과 역할이 조금은 미스매치 된다고 생각합니다 
한 번 함수명을 수정해보면 어떨까요?
추가로 함수도 값을 가지고 오는 부분과 렌더링 하는 부분으로 2가지로 나눌 수 있어보입니다

2024-03-09 08:55 UTC, liswktjs commented on src/domain/RestaurantList.ts
> +    if (restaurantsInStorage != null) this.restaurants = this.getStorageRestaurantList(restaurantsInStorage);
localstorage의 get과 set의 로직은 util로 분리하면 어떨까요? 
좀 더 함수가 간결해 질 것 같습니다

2024-03-09 08:55 UTC, liswktjs commented on src/domain/RestaurantList.ts
> +    localStorage.setItem(STORAGE_KEY, JSON.stringify(this.restaurants));
예를 들어 이 set도 인자로 data를 받아서 set을 해주는 함수를 만들어주면 
호출 부에서 
```
set(this.restaurants)
```
이런식으로 깔끔하게 구현할 수 있게 도와줄 수 있을 것 같습니다

2024-03-09 08:55 UTC, liswktjs commented on src/domain/RestaurantList.ts
> +    if (restaurantsInStorage != null) this.restaurants = this.getStorageRestaurantList(restaurantsInStorage);
get 해올때 JSON.parse도 같이 해주어서 사용처에서는 JSON문법을 사용 안 하는 방향으로 하면 좋을 것 같아요

2024-03-09 08:55 UTC, liswktjs commented on src/domain/RestaurantList.ts
> +    localStorage.setItem(STORAGE_KEY, JSON.stringify(this.restaurants));
push보다는 삼항연산자를 사용해보면 좋을 것 같습니다!

2024-03-09 08:55 UTC, liswktjs commented on src/constants/config.js
> +const DEFAULT_RESTAURAMT_LIST = [
이 리스트가 config에 있는 건 살짝 애매해보입니다 
여기에 위치한 이유를 알 수 있을까요?

2024-03-09 08:55 UTC, liswktjs commented on cypress/e2e/localStorage.cy.ts
> +  it('음식점 목록에 추가한 음식점이 localStorage에 잘 반영되는지 확인한다.', () => {
테스트 명세를 좀 더 자세히 적어주면 어떨까요? 
잘 보다는 아시안 음식점을 추가했을 때 localstorage에 아시안 음식점이 추가되었는지 확인한다 등으로 좀 더 자세히 써주면 좋을 것 같아요

2024-03-11 10:14 UTC, rbgksqkr commented on .prettierrc.js
> +};
[c91c0d3](https://github.com/woowacourse/javascript-lunch/pull/139/commits/c91c0d3157007bbbda40ae3ff822622a38f73088) : 수정하였습니다!

2024-03-11 10:18 UTC, rbgksqkr commented on src/index.js
> +  const $sortingFilter = document.getElementById('sorting-filter');
[89ef32e](https://github.com/woowacourse/javascript-lunch/pull/139/commits/89ef32e84e4aa4e232ea29f14ccfc4340b4b4697) : DOM 객체를 가져오는 메서드 추가하였습니다! console.error 를 할 경우 element 타입이 HTMLElement | null 이 되버려서 throw Error를 사용하였는데, 외부에서 try-catch를 사용하지 않았습니다.
selector를 잘못 넣는건 개발자의 실수이고 사용자에 의해 오류가 나진 않을 거라고 생각하여 문제 삼지 않았습니다. 추후 필요시 에러핸들링을 추가할 예정입니다!

2024-03-11 10:19 UTC, rbgksqkr commented on src/index.js
> +  });
[8896390](https://github.com/woowacourse/javascript-lunch/pull/139/commits/8896390900685aaaf43d1cd7d53695a3350a624d) : 시간이 부족하여 메서드 분리를 고려하지 않았던 것 같습니다. 분리함으로써 좀더 깔끔해진 것 같아요!

2024-03-11 10:21 UTC, rbgksqkr commented on src/index.js
> +    $restaurantList.innerHTML += RestaurantComponent(element.information);
입력값에 접근하는 것이 아니고 틀을 덮는 부분을 만들고 있기 때문에 innerHTML을 사용해도 XSS 공격에서 괜찮다고 생각을 하게 되었습니다. 이러한 점에서도 스크립트 공격에 취약한지 궁금합니다! 
하지만 취약하다는 것은 사실이라고 생각해서 createElement로 리팩토링 진행하였습니다!

2024-03-11 10:22 UTC, rbgksqkr commented on src/components/Restaurant.js
> +const RestaurantComponent = information => {
도메인 로직을 제외하고 js 파일로 진행하여서 명시하지 않았던 것 같아요! 이번 리팩토링 때 ts로 마이그레이션 하면서 타입 지정하였습니다!

2024-03-11 10:23 UTC, rbgksqkr commented on src/components/Restaurant.js
> +};
이 부분도 반영하여 createElement로 개선하였습니다!

2024-03-11 10:27 UTC, rbgksqkr commented on src/eventHandler/ModalEventHandler.js
> +    const restaurantInformation = new Restaurant({ category, name, distance, description, link });
[2c0f321](https://github.com/woowacourse/javascript-lunch/pull/139/commits/2c0f32149845d3407c428fe555ae14dc8ad71e32) : 추가로 폼의 입력값에 따라 추가하기 버튼의 disabled를 제어하기 위해 form에 input 이벤트핸들러를 등록하였습니다! 이때 모든 입력값에 따라 이벤트가 호출되는데, 이 경우 많은 함수 호출이 발생할 것 같습니다. 이를 어쩔 수 없는 부분인지 궁금합니다!

2024-03-11 10:28 UTC, rbgksqkr commented on src/eventHandler/ModalEventHandler.js
> +    const link = $restaurantForm.elements.link.value;
폼 유효성 검사와 함께 http:// 또는 https:// 로 시작할 경우에만 유효하도록 추가하였습니다

2024-03-11 10:31 UTC, rbgksqkr commented on src/constants/config.js
> +const DEFAULT_RESTAURAMT_LIST = [
프로그램이 시작될 때 1번 불러오는 상수값이라고 생각하였습니다. 이를 RestaurantList에 넣는 것도 괜찮은 선택지였는데, 이럴 경우 테스트하기 어려운 코드가 된다고 생각하였습니다. 클래스 내에 선언하여 기본값으로 받는 방법과 상수 처리하는 방법 둘 중에 후자를 택하게 되었는데, 생성자 없이 기본값으로 처리하는 게 더 나은지 샐리의 생각도 궁금합니다! 
이럴 경우 테스트케이스 수정이 불가피해지는데 그럼 테스트케이스를 잘못 고려한건지도 궁금합니다!

2024-03-11 10:32 UTC, rbgksqkr commented on src/domain/RestaurantList.ts
> +    if (restaurantsInStorage != null) this.restaurants = this.getStorageRestaurantList(restaurantsInStorage);
유틸함수로 분리하기보단 한가지 데이터밖에 없으므로 반환타입까지 명시하는 게 좋을 것 같다고 판단하여, domain 내부에 restaurantStorage 파일로 분리하게 되었습니다.

2024-03-11 10:42 UTC, rbgksqkr commented
안녕하세요 샐리! 시간 부족으로 못했던 부분들과 추가로 피드백을 반영하여 다소 많은 부분을 수정하게 된 점 양해부탁드립니다!
코멘트에도 작성하였지만 작업 내용을 요약하자면 다음과 같습니다.

- js 부분으로 구현한 UI 로직을 ts로 마이그레이션
- innerHTML과 insertAdjacentHTML를 모두 제거하고 createElement로 개선
- localStorage 파일 분리
- DOM 객체 가져오는 유틸 함수 생성
  -  Img, Button, Select 등 고유한 속성을 가지는 경우 별도의 메서드로 분리
- `Button 컴포넌트` 생성
- `form 유효성 검사` 로직 추가
- form이 유효하지 않은 경우 `등록 버튼 disabled`
- SelectBox 컴포넌트가 필터링 기능을 온전히 가질 수 있도록, 등록 버튼 클릭 시 handleCategoryFilter 메서드가 실행되는 `dispatchEvent`적용

2024-03-12 10:59 UTC, liswktjs approved these changes
안녕하세요 마루 

이번 리뷰 반영을 통해서 사용성을 잘 챙겨주신 것 같아서 좋았습니다 👍
특히, 폼에서 카테고리를 선택하지 않아서 유효하지 않을 때 --- 처리 된 부분과 
버튼 비활성화도 같이 처리해주신 부분이 유저가 한눈에 자신의 폼 입력상태를 확인할 수 있어서 좋다고 생각합니다 💫

추가로 button관련해서도 코멘트로 질문 주셔서 button 코드 부분에 답변으로 달았습니다!
2단계를 구현하면서 같이 반영해주시면 재사용하기 쉬운 컴포넌트가 될 수 있을 것 같습니다 

그럼 2단계 미션도 파이팅입니다 🍱

2024-03-12 10:59 UTC, liswktjs commented on src/utils/dom.ts
> +  },
코멘트에 try catch문을 따로 설정하시지 않는다고 써주셨더라고요
하지만 아무래도 앞으로는 동적으로 렌더링 되는 앱을 구현해야 하다 보니 dom이 없는 경우에 대해서도 에러처리가 필요해보이긴 합니다
유저의 action과 network 상태 등등으로 여러가지 변수상황이 있을 수 있어서요 
한 번 고려해보셔서 적용해보시면 좋을 것 같습니다

2024-03-12 10:59 UTC, liswktjs commented on src/utils/dom.ts
> +  },
dom 생성하는 util함수를 활용해서 구현해주셨군요 👍
재사용성도 챙기고 코드도 더 깔끔해진 것 같아서 좋습니다

2024-03-12 10:59 UTC, liswktjs commented on src/utils/dom.ts
> +    if (classNames != null) {
추가로 != 보다는 !== 을 사용하시는 걸 추천드립니다! 
두 가지 연산자의 차이점에 대해서도 공부해보시면 좋을 것 같아요

2024-03-12 10:59 UTC, liswktjs commented on src/index.ts
> +};
>  이때 모든 입력값에 따라 이벤트가 호출되는데, 이 경우 많은 함수 호출이 발생할 것 같습니다. 이를 어쩔 수 없는 부분인지 궁금합니다!

이렇게 질문을 주셨는데, 유저가 입력하는 값을 실시간으로 감시해서 button의 disabled처리해야할 때는 어쩔수 없이 함수를 input의 값이 바뀔 때마다 호출해야하는 부분이 있습니다 

만약 조금 더 다른 방법을 찾는 다면, 매번 모든 값을 다 계산해주는 것 보다 
각각의 input의 값이 변경 되었을 때 변경된 값들만 을 계산해서 유효성 여부를 업데이트 해주는 방법도 있을 것 같습니다!

2024-03-12 10:59 UTC, liswktjs commented on src/index.js
> +    $restaurantList.innerHTML += RestaurantComponent(element.information);
제가 알기로는 XSS공격을 해오는 루트는 다양하기 때문에 되도록이면 innerHTML을 사용하지 않는 것이 좋고 만약 사용한다고 하면 살균등의 작업을 할 수 있습니다

2024-03-12 10:59 UTC, liswktjs commented on src/constants/config.js
> +const DEFAULT_RESTAURAMT_LIST = [
상수를 처리하는 것이 저도 더 괜찮아보입니다
다만, config라는 파일명 아래 있는게 조금은 어색해보입니다! 

왜냐하면 만약 서버와 연결을 했다고 가정하면, 
저 리스트는 서버에서 받아온 값일 테니 config라는 파일 명하고는 어울리지 않는 역할을 하고 있는 상수라고 생각했습니다

2024-03-12 10:59 UTC, liswktjs commented on src/components/button/Button.ts
> +
코멘트로 추가 질문을 주셨는데, 
제 생각에는 button은 가볍게 하고 외부에 로직을 두어 함수를 넘겨 받아 button컴포넌트에서 실행시켜주는것이 적절하다고 생각합니다! 
왜냐하면, button이 앞으로 여러 기능들을 구현할 때 재사용하게 되면 점점 더 button 내부의 분기처리도 많아지게 되어 마루가 말한대로 컴포넌트가 무거워질 수 있다고 생각합니다!

2024-03-12 10:59 UTC, liswktjs commented on templates/style.css
> +}
여기 EOL이 있네요 👀

2024-03-12 10:59 UTC, merged

2024-03-12 11:55 UTC, rbgksqkr commented on src/utils/dom.ts
> +    if (classNames != null) {
=== 을 통해 타입까지 체크하는 걸 저도 선호하는데, 타입스크립트 lint rule에서 저렇게 사용하도록 잡더라고요 이유는 정확히 모르겠는데 다시한번 확인해보겠습니다!