[2단계 - 자주 가는 음식점] 낙타(송재석) 미션 제출합니다.
woowacourse/javascript-lunch pull request #151
Opened 2024-03-17 15:10 UTC by Largopie

## 🚀 실행 방법

1. 배포 주소 : [https://largopie.github.io/javascript-lunch](https://largopie.github.io/javascript-lunch/)
2. 로컬 실행

```bash
npm install
npm run start
```

## 📍 학습 목표

- 어플리케이션을 컴포넌트 단위로 모듈화하여 개발
    - UI를 컴포넌트 단위로 생각하고 개발하는 연습
    - 재사용할 수 있는 컴포넌트를 고민해보기
- 웹 UI 환경에서의 테스트 기초
    - 사용자 관점에서 중요하다고 생각하는 기능을 스스로 정의하고 E2E 테스트로 검증해보기
- TypeScript의 기본 문법을 익히며 필요성을 경험

안녕하세요 피터! 이번 step2를 하면서 정말 많은 부분을 느꼈다고 생각합니다.. 🥲 먼저 이전 코드에서 관련된 클래스 내부에 이벤트를 정의하고 별도로 렌더링을 해주었던 로직을 수정했습니다. 페이지가 렌더링 되기 이전에 이벤트를 주입하면 태그를 찾을 수 없어 이벤트를 적용할 수 없는 문제점을 발견했습니다. 따라서 처음에 constructor()에서 페이지를 렌더링하고, 바로 이벤트를 주입해줄 수 있도록 구현 방향성을 바꾸었습니다. 이렇게 구현하게 되면 페이지가 재렌더링 되더라도 등록된 이벤트는 유지될 것이라고 생각이 들었는데 아니였습니다.. ㅎㅎ 태그가 사라지면 이벤트도 함께 사라진다는 걸 배웠습니다.. 😂

이 때, render 함수를 다시 불러주어야 하는 상황이 생길 때를 대비하여 최대한 변하지 않는 정적 컨텐츠에 이벤트를 부여하고, 내부의 태그를 다시 렌더링 하도록 구현했습니다. 하지만 step1에서는 이러한 방법이 많은 효율성을 주었지만, step2로 넘어가서 진행하면서 불편한 점을 많이 느꼈던 것 같습니다.

클래스로 정의했기 때문에 클래스 전체를 다시 렌더링 해야하는 상황이 오는 경우, `new`로 클래스를 다시 불러와야 하는 상황이 빈번했습니다.(사실 이 부분이 제일 걸렸습니다.) 이렇게 구현하는 것 보다 `createElement`, `append` 메서드를 활용해 함수로 구현한 후 element에 이벤트를 주입할 수 있었다면 필요한 부분에 대해서만 class를 선언해서 사용할 수 있지 않았을까? 아쉬움도 들었지만, 현재 로직에서 개선할 수 있는 부분들을 개선해나가고 싶습니다.

## 🤔 고민했던 점, 질문 사항

### 1️⃣ 재사용성

재사용성에 대해서 조금 더 많은 고민을 했습니다. 따라서 모든 Modal 기능이 필요한 UI로직은 하나의 div태그에서 렌더 및 삭제를 구현하고자 했습니다. 따라서 Modal을 사용하는 기능들은 `ModalWrapper`의 상속을 통해 템블릿을 이어받아 사용할 수 있도록 구현했습니다.

이 외에도 즐겨찾기버튼 템플릿을 분리해서 사용했습니다.

### 2️⃣ 이벤트 주입

저는 이벤트를 만든 컴포넌트 자체에서 가지고 있어야 한다는 생각을 가지고 해당 컴포넌트가 생성될 때 이벤트가 함께 추가하도록 구현했습니다. 하지만 render함수를 재사용해야하는 경우, render함수 내부에 등록했던 이벤트가 사라지는 경우가 있었습니다. 따라서 다시 `new` 키워드를 통해 클래스를 다시 생성해서 렌더링하는 방식을 채택했습니다. 이렇게 되면 클래스로 정의할 의미가 모호해진다는 생각도 들었고, 매번 렌더링 될 때 마다 이벤트를 다시 생성해야된다는 부분도 고려하지 않을 수 없을 것 같습니다.

아직 정확한 정의를 내리기 어려운 듯 한데, 이벤트를 주입할 때 이벤트가 주입되는 HTMLElement가 컴포넌트 자체에서 가지고 있을 필요 없이 최대한 변하지 않는 정적 컨텐츠에 이벤트를 주입해서 render하는 부분에 대해서 무리가 없게 만드는게 좋을까요?

### 2️⃣ innerHTML 이슈

![Untitled](https://github.com/woowacourse/javascript-lunch/assets/106071687/7029a87f-7eea-419a-94ab-8012b03b9a60)

`모든 음식점/자주 가는 음식점` 메뉴를 추가하는 기능이 있었습니다. 이를 위해 필터링 select, 음식점 목록 컴포넌트를 article 태그로 하나로 감쌀 수 있도록 만들게 되었습니다. 이때 `RestaurantFilter`, `RestaurantList`가 하나의 selector를 공유해서 후에 정의한 RestaurantList로 대체되는 이슈가 있었습니다. 이를 해결하기 위해서

![스크린샷 2024-03-17 오후 11 40 11](https://github.com/woowacourse/javascript-lunch/assets/106071687/9302bb97-2fd4-480a-aa40-37765b6a9631)

고정된 태그 내부에서 음식점 목록이 렌더링되도록 수정하고, `restaurantFilter`의 `render()` 메서드 로직을 수정하여 `insertAdjacentHTML` 으로 selector에 삽입되도록 구현했습니다.

이 외에도 기존에 TypeScript로 UI로직을 마이그레이션 할 예정이였지만, 이번은 생각보다 로직이 복잡해서 오래걸리더라구요.. ㅠㅠ 따라서 이번 미션에서는 진행하기 어려울 것 같다는 생각이 들었습니다.(꼭 해보고 싶었던 부분이라 방학을 노려서 해보고 싶습니다..!)

이번 step2도 잘 부탁드리겠습니다 🙇‍♂️

2024-03-19 15:51 UTC, iborymagic commented
고민하셨던 부분 및 질문을 찬찬히 읽어봤습니다.

리렌더링마다 new로 인스턴스를 다시 생성해야한다는 부분은 사실 지금도 클래스를 변수에 할당해놓고 재사용하면 되는 부분 아닌가 싶은데, 혹시 어떤 이유 때문인지 자세히 설명해주시면 좋을 것 같아요.

이벤트에 관해 주신 질문은, 이벤트를 가지고 있다는 말은 아마 이벤트 핸들러 함수를 가지고 있다는 말일 것으로 생각됩니다. 컴포넌트가 핸들러 함수를 가지고 있어도 당연히 상관은 없고 그럴 수밖에 없는 상황이 있지만, 그 말인 즉슨 해당 함수의 동작으로 그 컴포넌트의 역할이 제한된다고도 볼 수 있습니다. 즉, 범용성이 떨어지겠죠. 
결국 이전에 배웠던 내용들과 일맥상통합니다. 도메인과 UI를 분리하여 유지보수 비용을 낮추고 각 객체의 재사용성을 높였던 것처럼, 결국 컴포넌트도 동일하게 바라볼 수 있어요. 그래서 보통 범용성을 살리려면 외부에서 로직을 주입하는 방식으로 구현하는 경우가 많긴 합니다.
 
변하지 않는 정적 컨텐츠에 이벤트를 주입해서 render한다는 말은 사실 무슨 말인지 잘 모르겠어요. 예시를 들어서 질문해주시면 이해하기가 편할 듯 합니다.

2024-03-19 15:53 UTC, iborymagic requested changes
안녕하세요 낙타! 2단계 미션까지 고생 많으셨습니다. 👏👏
원래 처음에는 UI 코드에 타입스크립트를 적용하기가 빡셉니다. 그래서 타입스크립트에 익숙하지 않다면 낙타처럼 점진적으로 적용해보는 것도 나쁘지 않고, 현명한 선택이라고 생각합니다.
그래도 코드를 읽기에 크게 복잡하지 않아서 편하게 리뷰할 수 있었습니다. 
고민한 내용 및 질문에 대한 코멘트 달아놨으니 읽어주시고, 리뷰 반영 완료되시면 다시 요청주세요~

2024-03-19 15:53 UTC, iborymagic commented on src/components/Common/RestaurantDetail/RestaurantDetail.js
> +      const close = this._handleClose.bind(this);
요 함수는 변수에 담아 둔 이유가 무엇일까요?

2024-03-19 15:53 UTC, iborymagic commented on src/components/Common/RestaurantDetail/RestaurantDetail.js
> +      const close = this._handleClose.bind(this);
그리고 딱히 this 바인딩을 하지 않아도 될 것 같아요!

2024-03-19 15:53 UTC, iborymagic commented on src/components/Common/ModalWrapper/ModalWrapper.js
> +}
모달에 공통으로 사용되는 html, css, 상호작용 로직까지 잘 모여있네요 👍
어차피 상속받는 곳들에서 super()를 실행해주고 있으니, 그걸 활용해서 backdrop의 click event를 등록하는 로직도 ModalWrapper에서 해줄 수 있지 않을까요?

2024-03-19 15:53 UTC, iborymagic commented on src/components/Common/RestaurantDetail/RestaurantDetail.js
> +  }
요 정도 로직은 FavoriteIcon에 들어가도 괜찮지 않을까 생각하는데, 어떻게 생각하시나요?

2024-03-19 15:53 UTC, iborymagic commented on src/components/RestaurantList/RestaurantList.js
>    }
그러면 여기 #toggleIconImg도 없앨 수 있겠네요.

2024-03-20 15:33 UTC, Largopie commented
> ❓ 리렌더링마다 new로 인스턴스를 다시 생성해야한다는 부분은 사실 지금도 클래스를 변수에 할당해놓고 재사용하면 되는 부분 아닌가 싶은데, 혹시 어떤 이유 때문인지 자세히 설명해주시면 좋을 것 같아요.

제가 이 부분에 대해서 설명이 부족했던 것 같습니다.
사실상 [Header 컴포넌트](https://github.com/Largopie/javascript-lunch/blob/step2/src/components/Header/Header.js) 같은 경우는 render 함수 내부 태그 이벤트가 적용되어 있지 않아서 변수로 할당한 후 `render()` 메서드의 재사용이 가능했지만,

[AddRestaurantModal 컴포넌트](https://github.com/Largopie/javascript-lunch/blob/step2/src/components/AddRestaurantModal/AddRestaurantModal.js) 같은 경우에는 `render()` 메서드 내부에 정의된 태그에 이벤트를 적용해서 다시 페이지를 `render()` 해야하는 상황이 왔을 때 할당한 변수, 예를 들어
```JavaScript
  const addRestaurantModal = new AddRestaurantModal($('modal'));
  addRestaurantModal.render();
```
이렇게 한 번 더 렌더 메서드를 실행했을 경우 태그가 다시 repaint 되어 이벤트가 사라져서 적용되지 않았습니다. 🥲

처음에 이 부분을 인지했다면 function으로 선언하고 이벤트를 바로 주입시켜주어도 괜찮지 않았을까 하는 생각에 PR에 해당 내용을 작성하게 되었습니다. 저는 한번 주입된 이벤트는 지속적으로 사용 가능하다 생각하고 class로 선언해서 만들다 보니 굳이 변수로 할당해야 할 필요성이 없었고, `new` 키워드로 선언과 동시에 페이지가 렌더링 되게 만들었습니다. 따라서 다음부터는 변수로 할당할 수 있도록 render()는 재사용성을 고려해서 태그를 만들 수 있도록 하면 좋을 것 같고, class, function을 필요한 부분에 적재적소에 활용해보면 좋을 것 같다는 생각도 들었습니다.

최대한 저의 생각을 나열해서 말씀 드렸는데 이해가 안되거나 추가적으로 궁금하신 사항 있으시면 말씀해주시면 감사하겠습니다 👍

2024-03-20 17:36 UTC, Largopie reviewed
피터 안녕하세요 :) 바쁘신 와중에도 소중한 리뷰 남겨주셔서 감사합니다. 덕분에 더 많은 고민을 할 수 있었고, 더 좋은 방향성으로 고민해볼 수 있었던 것 같습니다. 리뷰 남기신 부분에 대해서 수정사항 반영 후 답글 남겨두었습니다. 추가적으로 궁금하신 부분이나, 리뷰하실 부분 있으시면 편하게 남겨주시면 감사하겠습니다 :) 🔥🔥🔥

2024-03-20 17:36 UTC, Largopie commented on src/components/Common/RestaurantDetail/RestaurantDetail.js
> +  }
저도 이 메서드가 공통적으로 쓰이는 부분에 대해서 많은 고민을 하다가 시간상 제출하게 되었는데 피터 말씀대로 저 로직 자체는 FavoriteButton 컴포넌트 내부 로직으로 사용해도 무리가 없을 것 같습니다! 수정해보겠습니다 :)

2024-03-20 17:36 UTC, Largopie commented on src/controllers/LunchAppController.js
>      this.#restaurants = new Restaurants(localStorage);
제가 알기로는 `localStorage` 외에도 [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) 또한` setItem()`, `getItem()` 등 해당 메서드를 같이 사용하는 것으로 알고 있습니다. 그래서 추후 `sessionStorage`를 사용할 수도 있는 상황을 예상해서 인자로 주입하게 되었는데 혹시 제가 잘못알고 있는 부분이 있을까요?

2024-03-20 17:36 UTC, Largopie commented on src/components/BookmarkNavigation/BookmarkNavigation.js
> +      });
맞습니다.. 저도 PR에서 작성했듯이 클래스 자체에 선언되어진 Event는 태그가 사라져도 사용할 수 있는 줄 알고 있었습니다.(하지만 아니였네요 ㅠㅠ) 이 부분이 걸려서 `function`으로 선언하는 부분이 더 낫지 않았을까 하는 생각이 많이 들었습니다.. ㅠㅠ 다음 미션 때는 필요에 따라서 function, class를 적절하게 활용할 수 있도록 해봐야될 것 같습니다. 더 많은 고민을 할 수 있게 해주셔서 감사해요 👍

2024-03-21 08:50 UTC, iborymagic commented on src/controllers/LunchAppController.js
>      this.#restaurants = new Restaurants(localStorage);
아 sessionStorage를 염두에 두시고 작성하신거였군요. 레이어를 분리하는 것을 생각했는데, 의도가 그러하시다면 이렇게 둬도 될 것 같습니다!

2024-03-21 09:00 UTC, iborymagic approved these changes
안녕하세요 낙타! 미션 마무리하시느라 정말 고생 많으셨습니다 👏👏
제가 이해하지 못했던 부분에 대해 자세히 설명해주셔서 감사합니다 :)
달아주신 답변들도 읽어보면서 낙타가 많은 고민을 했다는 것을 알 수 있었고, 
리뷰도 훌륭하게 잘 반영해주셔서 이만 머지하도록 하겠습니다. 
고생 많으셨어요. 다음 미션도 화이팅입니다!

2024-03-21 09:01 UTC, merged