[2단계 - 자주 가는 음식점] 라이언(박한영) 미션 제출합니다.
woowacourse/javascript-lunch pull request #152
Opened 2024-03-17 17:07 UTC by Parkhanyoung

안녕하세요 하루 그동안 잘 지내셨나요~? 다시 만나뵙게 되어 반갑습니다! 🙂
지난번 step1 정성스럽게 리뷰 남겨주셔서 감동이었습니다 :)
이번 step2 리뷰도 잘 부탁드립니다! 🫡

-------------

## 페이지 구조
<img width="917" alt="스크린샷 2024-03-18 오전 1 32 27" src="https://github.com/woowacourse/javascript-lunch/assets/80797824/9f7d9aab-08c7-4364-b103-4bc38236ee54">

(컴포넌트가 많아서 조금 난잡하네요 😂)

## 이번 미션에서 특히 신경을 썼어요
**1. 사용자 관점에서의 e2e 테스트:** 이번에 e2e를 처음으로 활용해보게 되었는데요. 개발자가 아닌 사용자 관점에서 확인해야 할 사항이 무엇일지 고민하며 테스트를 작성했습니다. 또한 너무 과하게 많은 케이스를 만들지 않고 적당한 범위에서 테스트하려 노력했습니다.
**2. 컴포넌트 재사용:** step1에서 만든 Modal과 CategoryIcon 컴포넌트를 재사용했습니다. 또한 여러 곳에서 사용되는 FavoriteIcon을 컴포넌트로 만들어 필요한 곳에서 재사용했습니다.
**3. 이벤트 리스너 중복 등록 방지:** 이벤트 리스너 등록 시 addEventListener의 두번째 인자로 익명 함수를 넘겨주면, 같은 로직일지라도 새로운 함수로 인지되어 중복 등록이 가능해집니다. 그래서 이벤트 리스너 등록 시 같은 참조 값을 갖는 함수를 넘겨주어 같은 이벤트 리스너가 중복 등록되는 일이 방지했습니다.
**4. 이벤트 리스너 제거:** step1에서는 이벤트 리스너를 remove하는 기능을 미처 추가하지 못했습니다. 이는 메모리 누수의 원인이 되었습니다. 그래서 이번에는 disconnectedCallback에 removeEvent 로직을 넣어주어, 컴포넌트가 Dom에서 제거될 때 관련 이벤트 리스너들이 제거되도록 했습니다.

## 아직 고민이 더 필요할 것 같아요
**1. 역할 분리에 대한 고민:** 로컬 스토리지 관련 로직과, 도메인 로직과 UI 로직이 애매모호하게 섞여 있다는 느낌이 들었습니다. 이를 보다 명확히 분리한다면 유지보수가 더 용이해질 것 같습니다.
**2. 메모리 누수:** 이번에 이벤트 리스너와 관련한 개선 작업을 하며 처음으로 메모리 누수에 대해 고민해봤습니다. 개발자 도구 Memory 탭을 확인해보니 생각보다 메모리 누수가 많이 발생하고 있었습니다. 메모리 누수가 발생하면 사용 시간이 길어짐에 따라 사용되는 메모리 양이 늘어나고 성능이 저하됩니다. 이는 사용자 경험에 안 좋은 영향을 많이 주는 만큼, 메모리 누수 관련 학습도 필요하다 느꼈습니다.

2024-03-17 17:23 UTC, Parkhanyoung commented on src/abstract/EventComponent.ts
> +  protected eventHandlerRegistrations: EventListenerRegistration[] = [];
**[참고] 이벤트 리스너 관련 처리를 위해 eventHandlerRegistrations 멤버 변수를 둔 이유는 다음과 같습니다**
1. setEvent 메서드에서, addEventListener의 인자에 참조값이 같은 핸들러를 넘김으로써 (init 메서드 재실행 시) 동일한 리스너가 중복 등록되는 일이 방지하기 위함
2. setEvent와 removeEvent에서 이루어지는 동일한 리스너에 대한 반복적인 작업을 간결하게 처리하기 위함

2024-03-18 13:35 UTC, 365kim commented on src/LunchApp.ts
> +          <
최종 커밋이더라도 오류가 없도록 작성하는 것이 일반적입니다. 커밋은 여러 개를 합쳐서 완성하는 단위가 아니라 온전한 작업의 단위로 생각해주세요. 이럴 경우에는 `undo commit` 한 후에 다시 commit 해주시면 더 좋겠습니다. 👍🏼

2024-03-18 13:38 UTC, 365kim commented on src/constants/event.ts
> +export const TOGGLE_FAVORITE_EVENT = "toggleFavorite" as const;
기존에는 단 하나의 이벤트이더라도 객체로 관리해주신 것으로 확인했어요. 사소하지만 이런 일관성도 챙겨주시면 좋겠습니다. 👍🏼 

```ts
export const MODAL_EVENT = {
  restaurantFormModalAction: "restaurantFormModalAction",
} as const;

```

2024-03-18 13:54 UTC, 365kim commented on src/components/FavoriteIcon.ts
> +    this.setAttribute("isActive", String(changesToActive));
이 부분 관련해서 2가지 전해드려요.

#### 1

사용자 정의 attribute는 `data-*` prefix를 사용하는 것이 일반적이에요. 
그런데 이 경우 `data-*`도 필요해보이지 않아보여요. 스타일 제어는 className을 동적으로 관리하면 충분해 보입니다. (참고 링크에 예제를 보시면 조금 더 감이 오실 것 같습니다.)

- 참고: https://developer.mozilla.org/ko/docs/Learn/HTML/Howto/Use_data_attributes

<br/>

#### 2
더 중요하게는, 사용자와 상호작용하는 요소들은 HTML에 잘 정의가 되어있어요.
그래서 앞으로 div에 onclick 핸들러를 지정하실 일은 거의(정확히는 아예) 없을 거예요.

이 토글 기능의 경우, input의 type="checkbox"로 구현하는 것이 좋아보입니다. (물론 label 태그도 함께)
- 참고: https://developer.mozilla.org/ko/docs/Web/HTML/Element/input/checkbox

시간 여유가 있다면 `data-is-active`로, 혹은 checkbox로 구현을 해주시면 좋겠습니다. 없다면 그렇구나 하고 넘어가주세요 :)

2024-03-18 14:05 UTC, 365kim commented on src/components/RestaurantList.ts
>      );
getTemplate 앞 부분 로직(line79 ~ line 100) 이 조금 장황해보이는데 리팩터링 해볼 수 있을까요?

```ts
const displayRestaurantInfos = this.filterRestaurantInfos()

// 나머지 스토어 접근 등은 filterRestaurantInfos 메서드에서 처리
```

2024-03-18 14:06 UTC, 365kim commented on src/components/common/Modal.ts
> +      <div id=${modalId} class="${isOpen ? "" : "close"}">
저도 이런 코드 정말 자주 작성하는데, 이런 조건부 클래스네임 추가를 위한 유틸 패키지 추천드려요 :)

- https://www.npmjs.com/package/classnames
- https://www.npmjs.com/package/clsx

2024-03-18 14:08 UTC, 365kim commented on src/components/RestaurantList.ts
> +              : "<p class='no-restaurant-item-message'>등록된 식당이 없습니다.<br/> 식당을 추가해주세요 👨🏻‍🍳</p>")
정말 친절하네용 👏👏👏👏👏

2024-03-18 14:16 UTC, 365kim commented on src/components/FilterBar.ts
> +  private handleTabSwitch(e: CustomEvent) {
[Generic](https://www.typescriptlang.org/ko/docs/handbook/2/generics.html)으로 타입 정보를 추가해줘도 좋겠네용

```ts
  private handleTabSwitch(
    e: CustomEvent<{ switchTo: keyof typeof TAB_SWITCH_EVENT_SWITCH_TO }>
  ) {
```

2024-03-18 14:18 UTC, 365kim commented on src/abstract/EventComponent.ts
> +  protected dispatchCustomEvent(
이 리팩터링 깔끔하네용 👍

2024-03-18 14:29 UTC, 365kim commented on cypress/e2e/LunchApp.cy.js
> +    });
> 사용자 관점에서 중요하다고 생각하는 기능을 스스로 정의하고 E2E 테스트로 검증해보기

이 두 테스트를 작성해주신 의도는 무엇일까요? 

만약 '웹사이트가 정상적으로 로드되었는지'를 확인하려는 테스트로 작성해주신 거라면 하나로 합칠 수 있어보이는데, 라이언의 생각은 어떠신가요~?

2024-03-18 14:29 UTC, 365kim commented on cypress/e2e/LunchApp.cy.js
> +    it("처음 방문했을 때 기본 요소(header와 main 태그)가 존재한다.", () => {
context를 이미 잘 작성해주셔서 it의 "처음 방문했을 때"는 생략할 수 있어보여요.

2024-03-18 14:34 UTC, 365kim commented on cypress/e2e/LunchApp.cy.js
> +    });
지금의 테스트는 첫번째 요소만 우연히 일치해도 통과할 수 있어보여요. (거짓음성)

2024-03-18 14:36 UTC, 365kim commented on cypress/e2e/LunchApp.cy.js
> +    localStorage.setItem("restaurants", JSON.stringify(RESTAURANTS_INFOS));
로컬스토리지가 비어있는 사용자의 경우도 테스트해보면 어떨까요?

2024-03-18 14:42 UTC, 365kim commented on src/components/common/Modal.ts
> +      <div id=${modalId} class="${isOpen ? "" : "close"}">
여기서도, open&closeModal 에서도 동적으로 관리하고 있어 보여요. 하나로 합칠 수 있을까요?

2024-03-18 14:45 UTC, 365kim commented on templates/filled-favorite-icon.png
아이콘을 클릭한 순간 `filled` 이미지가 불러와져서, 최초에 깜빡임이 있는데, 개선해볼 수 있을까요~?

![flicker](https://github.com/woowacourse/javascript-lunch/assets/60066472/03a78a84-bc4a-4aff-921d-30289cebd86e)

2024-03-18 14:51 UTC, 365kim commented on src/abstract/EventComponent.ts
> +      target?.removeEventListener(eventName, handler);
음, '동작'이 분기되는 것은 아니고 '대상'만 분기되는 것으로 보여요. 이렇게 써볼 수 있을까요?

```ts
const targetElem = typeof target === "string" ? $(target) : target

targetElem?.removeEventListener(eventName, handler);
```

한편, string 타입의 selector와 element 둘 중 아무거나 넣을 수 있는 인터페이스는 조금 낯설어 보여요. 전부 selector를 넣거나  `$()` 를 활용해서 전부 element 으로 받는 것이 자연스러워 보입니다.

2024-03-18 14:53 UTC, 365kim commented on src/store/favoriteStore.ts
> +      alert("데이터가 훼손되어 식당 즐겨찾기 목록이 초기화되었습니다.");
이 부분도 E2E 테스트로 검증되면 더 좋겠네요.

2024-03-18 15:00 UTC, 365kim commented on src/abstract/EventComponent.ts
> +  protected eventHandlerRegistrations: EventListenerRegistration[] = [];
> detached html element으로 인한 메모리 누수를 개선하는 방법?

저는 라이언이 말씀해주셔서 Memory 탭의 `Detached-*` 항목을 처음 봤어요 관련하여 개선해 본 경험이 없어 큰 도움은 되지 못하겠습니다. 

급격하게 늘어난다고 말씀해주셨는데, 저도 확인해보니 시간이 지나면 대부분 Freed로 잡히는 것으로 확인했어요. 실제로 가비지 컬렉팅이 처리되는 사이에 조회해주셨던 것은 아닐까 싶어요. 

![image](https://github.com/woowacourse/javascript-lunch/assets/60066472/de3d5f7e-2c48-49be-84bd-04c83a735278)

2024-03-18 15:05 UTC, 365kim requested changes
라이언, 2단계 작업해주신 것 잘봤습니다 :)

미션의 주요 요구사항인 컴포넌트 재사용과 E2E 테스트 작성을 잘 소화해주신 것으로 확인했어요. 👍
요구사항에 정의되지 않은 부분도 꼼꼼하게 처리하는 것이 라이언의 강점인 듯해요. 저도 배워갈 수 있는 작업이었어요.

코멘트 몇 가지 남겼는데, 천천히 보시고 확인 완료되시면 리뷰 재요청 부탁드릴게요
수고하셨습니다  👏👏👏

2024-03-19 13:21 UTC, 365kim commented on src/components/FavoriteIcon.ts
> +    this.setAttribute("isActive", String(changesToActive));
커스텀 엘리먼트에 한해서는 attribute를 자유롭게(?) 사용하는 것으로 확인했어요. (굉장히 낯서네요..ㅎㅎ) 아래 코멘트는 넘어가주세요 :)

<details><summary> 수정 전 리뷰 </summary>

사용자 정의 attribute는 `data-*` prefix를 사용하는 것이 일반적이에요. 
그런데 이 경우 `data-*`도 필요해보이지 않아보여요. 스타일 제어는 className을 동적으로 관리하면 충분해 보입니다. (참고 링크에 예제를 보시면 조금 더 감이 오실 것 같습니다.)

- 참고: https://developer.mozilla.org/ko/docs/Learn/HTML/Howto/Use_data_attributes

</details>

2024-03-19 15:08 UTC, Parkhanyoung commented on src/components/FavoriteIcon.ts
> +    this.setAttribute("isActive", String(changesToActive));
생각지 못한 부분을 잘 짚어주셔서 감사드립니다 하루 🙂
앞으로는 이런 부분은 checkbox 구현하겠습니다!

하루의 리뷰를 통해 그간 HTML을 제대로 사용하기 위한 고민이 부족했다는 것을 깨닫게 됐습니다! 
자주 사용했다고 해서 잘 알았던 것 아니었던 것 같네요 😂
HTML의 문법들을 적절하게 사용하기 위한 공부도 게을리 하지 않겠습니다 👍🏻

2024-03-19 16:00 UTC, Parkhanyoung commented on src/abstract/EventComponent.ts
> +      target?.removeEventListener(eventName, handler);
명쾌한 설명 감사합니다~! 바로 이해가 되네요!

selector와 element 둘 다 넣을 수 있는 인터페이스가 조금 이상하다는 데에도 동감합니다. 그런데, 현재 구조 상 element를 즉시 넘길 수 없는 부분이 존재하고, 한편으로는 document를 넘겨주어야 하는 경우가 있습니다. 그래서 selector나 element 중 하나로 통일하기 어려운 상황입니다.

이런 걸 보면, EventListenerRegistration 프로퍼티를 두어 이벤트 로직을 처리하는 구조가 잘못된 설계였을 수 있겠다는 생각도 듭니다.
이번 리뷰에 온전히 반영하지 못한 것과는 별개로, 하루가 짚어주신 부분 명심하도록 하겠습니다!

2024-03-20 04:26 UTC, Parkhanyoung commented on src/components/common/Modal.ts
> +    $(`#${this.getAttribute("modal-id") ?? ""}`)?.classList.remove("close");
> 여기서도, open&closeModal 에서도 동적으로 관리하고 있어 보여요. 하나로 합칠 수 있을까요?

이렇게 이야기해주신 것을 openModal과 closeModal에서 모달의 상태를 같은 값(변수)으로 다루는 게 좋다는 의미로 받아들였습니다.(ex. isOpen이라는 멤버변수를 두어 그것을 공유해 사용하는 방식으로)
그런데 그 방식에서는 상태 값을 바꾸어준 이후에 리렌더를 해주어야 합니다.
그래서 classList에 직접 접근하는 방식을 유지했습니다.

혹시 제가 잘못 짚은 부분이 있거나, 하루의 의도를 잘못 이해했다면 말씀해주시면 감사하겠습니다! :)

2024-03-20 13:53 UTC, 365kim commented on src/components/common/Modal.ts
> +    $(`#${this.getAttribute("modal-id") ?? ""}`)?.classList.remove("close");
아하, 저는 classList로 이미 동적으로 제어하는데, template에서 생략할 수 있을까 해서 말씀드린 거였어요 :)

2024-03-20 14:03 UTC, 365kim approved these changes
![dance](https://github.com/woowacourse/javascript-lunch/assets/60066472/769b4887-d806-4630-bbeb-77259cde224f)

라이언, 점심뭐먹지 미션 완료 축하드려요!

1단계 2단계 내내 친절한 작업 설명 감사했어요. 제가 드린 피드백 하나하나 적극적으로 고민해보고 반영해주신 것도 감사합니다. 제가 피드백 드린 이상으로 얻어가신 것으로 느꼈어요 👍

다음 미션도 응원할게요 고생하셨습니다 👏👏👏

2024-03-20 14:03 UTC, merged