[2단계 - 자주 가는 음식점] 리버(최재희) 미션 제출합니다.
woowacourse/javascript-lunch pull request #157
Opened 2024-03-18 07:15 UTC by 0jenn0

> 안녕하세요 샐리 🍀 
이번에는 innerHTML를 사용하지 않고 컴포넌트들을 HTMLelement로만 구현해보았습니다!
HTMLelement로 구현하면서 샐리가 말씀해주신 innerHTML에 대한 피드백을 실제로 잘 느껴볼 수 있었습니다 😊
이번에도 잘 부탁드립니다 🙇

<h2>0. 배포링크 🔗</h2>

> [리버 | STEP2 점심 뭐먹지 배포 링크](https://0jenn0.github.io/javascript-lunch/dist/)

</br>

<h2>1. STEP1 리뷰 반영 목록</h2>

완료 | 리뷰 내용 | 커밋 ID
-- | -- | --
✅ | 정보 검증에 쓰이는 숫자들(길이제한 숫자) 상수화하기 | de6b57dbeab5fff4053e1a9c5520fcc63964f8b7
✅ | constants/constants.ts -> index.ts로 수정하기 | 374fa42e378b23e8fbedf61632a8d5adfc4580cc
✅ | as HTMLElement;로 타입 확정하지 말고 null일 수 있는 상황에 대한 에러처리를 진행하고 할당하기 | 4ab541460d13ae91aaee465e605d04ab5413331f
✅ | CategoryFilter 에서 인자의 타입을 단언하지 않고 기대하는 타입과 일치하는 경우에만 에러 발생 시키기 | 9829f47bc0e4eeffd97e212de7f14f9d7443f107
✅ | 카테고리 아이콘 button 태그 고치기 | 2b875f531d8d318851b66af2e9b9a7657c7ccd58
✅ | 음식점 정보 저장할 때 중복된 경우 경고창 뒤에 return 붙여서 저장안되게하기 | c9349ac1ebee89af69c74fdaa7b409ab248302f6
✅ | ModalComponent.ts에서 안쓰이고있는 컴포넌트 삭제하기 | 4fe2cf2b5157caeac1465b315ebd4302d2ddfe78
✅ | ModalComponent에서 Form 부분 분리하기 | 82371223f4caf8941562bb9372a4fe19051c3a89

</br>

<h2>2. 개선 사항</h2>
<h3>2 - 1 ) Component 재사용성 강화</h3>
<ul>
<li>기존 ModalComponent(음식점 추가 모달 컴포넌트)를 삭제하고 common의 Modal을 이용하여 새로 AddModal을 만들었습니다.</li>
<li>CategoryFilter 컴포넌트와 SortFilter 컴포넌트가 FilterComponent를 상속하는것으로 구현되어있었는데 FilterComponent를 삭제하고 common의 Select 컴포넌트를 사용하도록 새로 구현했습니다.</li>
<li>모달딤을 클릭하면 모달이 닫히는 기능이 음식점 추가 모달, 상세정보 모달에 중복 구현되어있었는데 이 기능을 common의 Modal 컴포넌트에 위임하여 중복 구현을 제거했습니다.</li>
</ul>
<h3>2 -2 ) UX</h3>
<ul>
<li>이름,설명에 대한 검증이 통과하지 못하면 단순히 추가하기 버튼이 비활성화가 되는 것 뿐만아니라, 해당 폼들 밑에 tooltip으로 메시지가 뜨게하여 사용자가 빠르고 정확한 피드백을 받도록 수정했습니다.</li>
<li>음식점 목록에 마우스 호버시 마우스가 포인터로 바뀌고 목록의 색이 바뀌게 수정하여 클릭 할 수 있는 요소임을 표현해보았습니다.
<ul>
<li>그 외에도 드롭박스, 탭바 버튼에도 마우스를 포인터로 수정하여 클릭 할 수 있는 요소임을 알 수 있게했습니다.</li>
</ul>
</li>
</ul>
<h3>2 - 3) 모든 Component를 createElement로 수정</h3>
<ul>
<li><code>template</code> 태그,<code>innerHTML</code>을 사용했던 이유가 가독성도 있었는데(+ 사실 귀차니즘도 있었던것같습니다..💦) <code>createElement</code>로 구현해도 내부에서 함수로 나눠준다면 가독성에 큰 문제가 없지 않을까 하는 생각이 들었습니다.</li>
<li>컴포넌트를 <code>documentFragment</code>로 다룰 때와 달리 <code>htmlElement</code>로 다루게되니 이벤트 위임 등 이벤트 핸들링측면에서도 훨씬 더 수월해서 좋았습니다.</li>
<li>그리고 샐리가 말씀해주신대로 유지보수와 디버깅(오타 발생 등) 측면해서도 좋아진것을 경험해 볼 수 있었습니다 👍👍👍</li>
</ul>

</br>

<h2>3. e2e 테스트</h2>
<ul>
<li>음식점 정렬,필터링 e2e는 말그대로 잘 정렬,필터링되는지가 중요하다 생각하여 `localStorage`를 사용하지 않고 cypress의 `fixture`을 이용하여 테스트를 구현해보았습니다.</li>
<li>음식점 상세 모달창에서 즐겨찾기 변경은 `localStorage`안에있는 해당 음식점의 즐겨찾기 속성값 변경이 중요하다고 생각하여 `localStorage`를 사용하여 테스트를 구현했습니다.</li>
</ul>

2024-03-19 03:17 UTC, liswktjs requested changes
안녕하세요 리버 
innerHTML을 createElement로 수정해오셨군요 👏
공통 컴포넌트에서 생성한 element를 return해주고 있어서 컴포넌트 단도 훨씬 깔끔해진 것 같습니다
또 Add~ 함수들을 활용해서  관련된 로직을 잘 묶어 주신 것 같아요 
ux 적인 부분들도 많이 신경써 주셔서 유저가 더 사용하기 쉬운 서비스가 만들어진 것 같습니다 💫

몇가지 코멘트 남겼으니 한 번 읽어보시고 반영 부탁드립니다 👍

2024-03-19 03:17 UTC, liswktjs commented on src/domain/restaurantAPI.ts
> +    alert(`${name} 식당의 좋아요 상태가 변경되었습니다.`);
유저에게 좋아요 상태 변경 알려주는 것 유저를 위한 좋은 고려인 것 같습니다 👏
나중에 한 단계 더 나아가서는 Toast message를 활용해보시는 것도 좋을 것 같아요

2024-03-19 03:17 UTC, liswktjs commented on src/domain/restaurantList.ts
> +    return [...data].filter((restaurant) => restaurant.isFavorite === true);
=== true를 해주지 않고 바로 isFavorite만 호출해 주어도 true인 것로 filter가 될 것 같습니다

2024-03-19 03:17 UTC, liswktjs commented on src/components/FavoriteButton.ts
> +    });
자주 가는 음식점에서 기존의 스타를 누른 음식점을 취소하면 바로 자주 가는 음식점 리스트에서 사라지지 않고 있어요 
카테고리 필터 바꿨을 때 바로 렌더링이 되는 것 처럼 바꿔주면 어떨까요?

2024-03-19 13:05 UTC, 0jenn0 commented on src/components/RestaurantDetailModal.ts
> +        text: '닫기',
Button 컴포넌트를 onClick 콜백함수를 인자로 받게 수정하면서 id값 중복이 없어져서 상수화하지 않았습니다!

2024-03-23 07:23 UTC, 0jenn0 commented on src/components/common/Button.ts
> +  }
깃 커밋 반영 주소 : b72663bd9e4dea933fd31a8a990a32b4aa23d0fd

코드가 더 깔끔해지것같습니다 감사합니다

2024-03-23 08:01 UTC, 0jenn0 commented on src/components/common/Modal.ts
> +  if (modalContainerClass) {
깃 커밋 반영 주소 : 4d41d88b66cc04d60c7b76b5aeaa436af8a3962c

typeof를 사용할 경우 undefined와 다른 falsy값들과 구분 할 수 있다는 장점이 있다는것을 알게되었습니다
typeof null이 object라는 놀라운 사실도 알게되었구요..!


```typescript
type Props = {
  modalClass: string;
  modalContainerClass?: string;
  child?: HTMLElement;
  children?: HTMLElement[];
};
```
이번 코드에서는 `modalContainerClass`의 속성이 타입이 undefined 또는 string으로 정해져있기때문에 
```typescript
if (  !modalContainerClass ) {
 // ...
}
```
이렇게 분기처리를 해도 `modalContainerClass`가 undefined인 경우로만 한정되지만,

modalContainerClass 타입이 undefined,string뿐만 아니라 null도 가능했다거나,
타입 설정을 해주지 못하는 바닐라 자바스크립트를 사용하는 경우에는
빈 문자열,0,null 등 다른 falsy값과 명확하게 구분할 수 있어서 undefined인 경우에만 어떤 로직을 실행해야할 때 필수겠다라는 생각이 들었습니다!

좋은 인사이트 감사합니다 👍

2024-03-23 08:05 UTC, 0jenn0 commented on src/components/AddButton.ts
> +
반영 커밋 주소 : 053d3110f90811e784f4908521081d00fbb281b0, 4c243c2bd0c349ecdf780d876c11c259f1b67aee

반영하여 컴포넌트의 유연성을 높였더니 이 컴포넌트가 사용되는 부분의 코드도 많이 간결해졌습니다 👍

2024-03-23 08:10 UTC, 0jenn0 commented on src/components/AddForm.ts
> +      console.log(nameTooltip, descriptionTooltip);
반영 커밋 주소 :  324837da02269c1296a3442a3e5ab46c113dbf8a

제가 console.log 미삭제 실수를 자주하는것 같네요 특히 미션 막바지에서 꼭..!😭
제거했습니다 !

2024-03-23 08:23 UTC, 0jenn0 commented on src/components/RestaurantDetailModal.ts
> +  const createRestaurantDescription = (description?: string): HTMLElement => {
깃 커밋 반영 주소 : bb662fffc70d04e8890ad31cd7716ae86e7d1e78

```typescript
const createRestaurantDescription = (description: string = ''): HTMLElement => {
  const restaurantDescriptionP = document.createElement('p');
  restaurantDescriptionP.textContent = description;
  return restaurantDescriptionP;
};
```
 description의 default 값 ''(빈 문자열)이 falsy 이므로, default 값을 빈 문자열로 할당해주면서
 ```typescript
   restaurantDescriptionP.textContent = description || ''
```
부분도 
 ```typescript
   restaurantDescriptionP.textContent = description 
```
로 수정했습니다!

2024-03-23 09:41 UTC, 0jenn0 commented on src/domain/restaurantAPI.ts
> +    alert(`${name} 식당의 좋아요 상태가 변경되었습니다.`);
좋아요 상태가 성공적으로 변경되었다는 점을 알려줘야할것같아서 alert 창을 사용하게되었는데,
alert창은 확인 버튼을 눌러야하는 번거로움이 있기때문에 좋아요 상태 변경 시도를 연속적으로 하고싶을 때
불편함이 생길 수 밖에 없어서 toast message가 이래서 필요하구나 싶었는데 시간문제상 구현은 나중으로 미뤄었는데요,
샐리도 마침 딱 언급해주시길래 이 때다 싶어서(?) 구현해보았습니다!

[토스트 메시지 컴포넌트](https://github.com/0jenn0/javascript-lunch/blob/step2/src/components/common/ToastMessage.ts)

2024-03-23 09:49 UTC, 0jenn0 commented on src/domain/restaurantList.ts
> +    return [...data].filter((restaurant) => restaurant.isFavorite === true);
반영 깃 커밋 주소 : 31ed8eb43c6138b243f478c211f38e892ea8591b

제가 if문 안에 boolean값이 들어갈 때 별생각없이 바로 저렇게 적는 버릇이 있네요 수정했습니다!

2024-03-23 10:09 UTC, 0jenn0 commented on src/components/FavoriteButton.ts
> +    });
반영 커밋 주소 :
+ 동적 임포트 추가 : 2cff9252235e175cdfb299ebe46d66fea2fd55a4 
+ 동적 임포트 삭제 : 8e0cd03b1ff97b646bc50dfd443be1245e095dc3

**TypeError: Cannot read properties of undefined (reading 'default')** 라는 에러가 생겼었고 
검색해보니 이는 비동기 작업의 결과로 모듈이나 컴포넌트가 제대로 로드되지 않았거나, 해당 컴포넌트에서 기대하는 방식대로 export되지 않은게 원인이었습니다

import문에서 오타가 없는 것은 여러번 확인했기때문에 동적 임포트로 수정해주니 에러가 해결되길래 
> 비동기 작업의 결과로 모듈이나 컴포넌트가 제대로 로드되지 않았거나

이 부분이 에러의 원인이 맞았구나 하고 넘어갔는데,
동적 임포트 말고 다른 해결방법이 없을까 싶어 동적 임포트 코드를 삭제해보았는데 에러 없이 작동이 잘되었습니다

갑자기 에러가 해결된 이유는 더 생각해보아야할것같습니다..! 😭

2024-03-23 11:09 UTC, 0jenn0 commented
안녕하세요 샐리
영화 미션과 맞물려 피드백 반영이 늦었습니다 죄송합니다 

[리버 | 1단계 피드백 반영 - 점심 뭐먹지 배포 링크](https://0jenn0.github.io/javascript-lunch/dist/)

피드백 반영과 함께 토스트 메시지도 구현해서 ux를 더 개선시켜보았습니다.


|     |     |     |
|:---:|:---:|:---:|
| ![이미지1](https://github.com/woowacourse/javascript-lunch/assets/130737187/d1d749e4-6752-4bf4-85d9-e1ea32d9aa6e?width=250px) | ![이미지2](https://github.com/woowacourse/javascript-lunch/assets/130737187/b1856ad6-4053-4d24-bd03-401fcddaf947?width=250px) | ![이미지3](https://github.com/woowacourse/javascript-lunch/assets/130737187/3dec56a4-986b-43ee-8137-21acda62edfd?width=250px) |
| 음식점 추가 할 때 토스트 | 중복된 음식점 등록할 때 | 즐겨찾기 여부를 변경할 때 |

2024-03-24 10:09 UTC, liswktjs approved these changes
안녕하세요 리버 
자주가는 음식점 미션 수고하셨습니다 👏

이번에 리뷰를 반영해주시면서 
toast message로 유저 사용성을 더 챙겨주셨군요 👍👍
toast 메세지를 통해서 더 좋은 사용자 경험이 될 수 있을 것 같아요 

타입에 대해서도 이번 기회에 많이 공부하신 것 같아 좋았습니다 
앞으로도 파이팅입니다 💪

2024-03-24 10:09 UTC, liswktjs commented on src/components/common/Button.ts
> +    button.addEventListener('click', onClick);
👍 onClick을 넘겨 받아서 호출 해주니 재사용하기 쉬운 컴포넌트가 된 것 같아요

2024-03-24 10:09 UTC, liswktjs commented on src/components/common/ToastMessage.ts
> +const ToastMessage = () => {
영화 미션으로 바쁘실텐데 Toast 까지 반영해주셨군요 👍
실제 프로덕트들에서도 구현할 일이 많으니깐 계속해서 챙겨보시면 좋을 것 같아요 👏

2024-03-24 10:09 UTC, merged