[2단계 - 음식점 목록] - 파란(안영훈) 미션 제출합니다.
woowacourse/javascript-lunch pull request #165
Opened 2024-03-18 08:03 UTC by greetings1012

# 🚀 프로젝트 실행 링크 
https://greetings1012.github.io/javascript-lunch/

# 🧪 테스트 실행 방법
npm run start 실행 후 다른 콘솔에서 npm run test 실행

## 📖 신경 쓴 부분들
다시 한번 잘 부탁드립니다, 지크 😄
step2를 진행하면서 노력했던 부분은

✅ 미션 요구 기능 구현
✅ 커스텀 이벤트리스너를 통해 데이터를 전달하고 받는 과정 익히기 
✅ e2e 테스트 구현

## 🧐 놓친 부분들
사실 이번에는 기본 기능 구현도 제대로 하지 못했다고 생각해요.
능력에 맞지 않게 ts 사용과 현재 구조 사용을 고집하다가 시간 부족으로 미션을 잘 마무리하지 못해 많이 아쉽고 분합니다 😡
다음 미션부터는 빠르게 상황을 파악해 포기할 것, 고칠 것은 바로 판단해야 할 것 같아요.
미션 시작부터 구조를 바꾸겠다고 마음먹었으면 조금 더 나은 페이지가 완성되지 않았을까 하는 생각이 머리를 떠나지 않네요.

❌ RestaurantInfoModal에서 favorite 버튼을 누르면 이벤트 호출 스택이 중첩되면서 메모리 누수가 발생해 사이트가 멈춰요.
RestaurantInfoModal에 event.detail을 전달하는 과정에서 이벤트가 중첩되는 것 같긴 한데...
Location.reload()를 통해 임시로 해결하긴 했지만 근본적으로 문제를 해결할 방법은 찾지 못했어요.

❌ 한 레스토랑의 modal을 띄운 후 바로 닫고 restaurantItemList에서 그 레스토랑의 favorite 버튼을 연달아 클릭하면 이벤트 버블링이 일어나 모달이 띄워짐과 동시에 favorite 버튼이 눌려요. 
event.stopPropagation()을 통해 막아두었지만 RefreshRestaurantList가 동작하면서 이벤트를 다시 달아주는 과정에서 뭔가 잘못되었다고 짐작하지만 명확한 이유를 찾지 못했어요.

❌ Cypress에서 e2e테스트를 진행할 때 마지막 테스트를 눌러보면 이유 불명의 에러가 중첩해서 끝없이 발생해요. 
createRestaurantList에서 빈 restaurants값을 받아올 때 에러를 발생시키는 것 같은데… 빈 값일 경우 값을 할당하지 않도록 함수를 수정했음에도 오류가 발생해요.

❌ validation으로 음식점 추가 모달의 각 항목 값을 검증하는 데 성공했으나, 하나만 조건을 만족하지 못해도 모든 사용자 input을 지워버려요.
어떤 input이 잘못되었는지에 대해 customEvent로 detail을 전달해주어야 할 것 같은데, 먼저 해결해야 할 오류들이 많아 구현에 실패했어요.

❌ 마지막으로, 전체적으로 step1에서 지크에게 리팩터링하겠다고 한 많은 부분들을 시간 문제로 놓쳤어요.(style.css 분리, AppController의 일부 기능 위임 등...)

이번 미션을 하면서 이벤트와 각 컴포넌트가 수행해야 할 역할에 대한 공부가 "많이" 필요하다는 사실을 뼈저리게 느꼈어요.
각 코드에 문제가 예상되는 부분을 다시 한번 남겨놓을게요!

## 프로젝트 구조
📦src
 ┣ 📂@types
 ┃ ┗ 📜import-images.d.ts
 ┣ 📂app
 ┃ ┣ 📂controller
 ┃ ┃ ┗ 📜AppController.ts
 ┃ ┣ 📂modal
 ┃ ┃ ┣ 📂AddRestaurantModal
 ┃ ┃ ┃ ┗ 📜AddRestaurantModal.ts
 ┃ ┃ ┗ 📂RestaurantInfoModal
 ┃ ┃ ┃ ┗ 📜RestaurantInfoModal.ts
 ┃ ┗ 📂root
 ┃ ┃ ┣ 📂FavoriteNavBar
 ┃ ┃ ┃ ┗ 📜FavoriteNavBar.ts
 ┃ ┃ ┣ 📂LunchHeader
 ┃ ┃ ┃ ┗ 📜LunchHeader.ts
 ┃ ┃ ┣ 📂RestaurantItem
 ┃ ┃ ┃ ┗ 📜RestaurantItem.ts
 ┃ ┃ ┣ 📂RestaurantList
 ┃ ┃ ┃ ┗ 📜RestaurantList.ts
 ┃ ┃ ┗ 📂SelectBoxSection
 ┃ ┃ ┃ ┗ 📜SelectBoxSection.ts
 ┣ 📂assets
 ┃ ┣ 📂image
 ┃ ┃ ┣ 📜add-button.png
 ┃ ┃ ┣ 📜category-asian.png
 ┃ ┃ ┣ 📜category-chinese.png
 ┃ ┃ ┣ 📜category-etc.png
 ┃ ┃ ┣ 📜category-japanese.png
 ┃ ┃ ┣ 📜category-korean.png
 ┃ ┃ ┣ 📜category-western.png
 ┃ ┃ ┣ 📜favorite-icon-filled.png
 ┃ ┃ ┗ 📜favorite-icon-lined.png
 ┃ ┗ 📜assets.ts
 ┣ 📂constants
 ┃ ┣ 📜enums.ts
 ┃ ┗ 📜typings.ts
 ┣ 📂css
 ┃ ┗ 📜style.css
 ┣ 📂data
 ┃ ┗ 📜defaultRestaurants.json
 ┣ 📂domain
 ┃ ┗ 📜Restaurant.ts
 ┣ 📂interface
 ┃ ┗ 📜interface.ts
 ┣ 📂service
 ┃ ┗ 📜RestaurantService.ts
 ┣ 📂utils
 ┃ ┗ 📜domSelector.ts
 ┣ 📂validator
 ┃ ┗ 📜RestaurantValidator.ts
 ┗ 📜index.js

2024-03-18 08:22 UTC, greetings1012 commented on src/app/controller/AppController.ts
> +  }
한 레스토랑의 modal을 띄운 후 바로 닫고 restaurantItemList에서 그 레스토랑의 favorite 버튼을 연달아 클릭하면 이벤트 버블링이 일어나 모달이 띄워짐과 동시에 favorite 버튼이 눌려요.
이 함수에서 이벤트를 다시 달아줄 때 뭔가 문제가 발생하는 걸까요?

2024-03-19 08:54 UTC, zigsong requested changes
안녕하세요 파란, 2단계 미션까지 수고하셨습니다.

흠... PR 본문에 남겨주신 이슈들을 같이 해결해보려고 노력했으나 코드의 구성 자체가 너무나도 어려워서 지금 상황에서는 디버깅이 어려울 것 같습니다. 

구조 개선을 먼저 하고, 그 후에 같이 디버깅을 해보면 좋을 것 같습니다. 테스트코드를 고치는 것도 마찬가지고요. 지금은 기능에 버그가 매우 많으므로, 시간이 없더라도 만들어서 꼭 한번 시도해보세요. 

추가로 

> ❌ validation으로 음식점 추가 모달의 각 항목 값을 검증하는 데 성공했으나, 하나만 조건을 만족하지 못해도 모든 사용자 input을 지워버려요.
어떤 input이 잘못되었는지에 대해 customEvent로 detail을 전달해주어야 할 것 같은데, 먼저 해결해야 할 오류들이 많아 구현에 실패했어요.

이 문제는 저에게는 재현되지 않는데요, 확인 부탁드립니다

2024-03-19 08:54 UTC, zigsong commented on src/interface/Interface.ts
> +  referenceUrl?: string | undefined;
`?`을 붙이는 것과 `| undefined`를 쓰는 것의 차이는 무엇일까요? 

우선, 둘 중 하나만 써야 합니다.

2024-03-19 08:54 UTC, zigsong commented on src/interface/Interface.ts
>  interface ILocation {
이 파일의 이름을 interface라고 하지 말고, 도메인과 관련된 이름으로 수정해주세요. 

`LocationInterface.ts` 등으로요. 파일 이름에 언어의 예약어와 같은 네이밍은 적절하지 않습니다.

2024-03-19 08:54 UTC, zigsong commented on src/constants/enums.ts
> +enum Category {
이 파일의 이름도 마찬가지로 도메인과 관련된 이름으로 수정해주세요.

2024-03-19 08:54 UTC, zigsong commented on src/app/controller/AppController.ts
>  class AppController {
`AppController`에 레스토랑 추가, 상세정보, 찜하기 등의 모든 동작이 들어가있는데, 

기능도 컴포넌트에 맞춰 함께 구분해볼 수 있을까요?

2024-03-19 08:54 UTC, zigsong commented on src/app/controller/AppController.ts
>    addEvent() {
`addEvent()` 역시 앱 전체에서 발생하는 모든 이벤트를 이곳에 때려넣어서, 이벤트 콜스택이 쌓이는 문제를 파악하기가 매우 어렵습니다. 컴포넌트 단위로 분리해보면 좋을 것 같아요. 

2단계 미션의 목표 중 하나가 '어플리케이션을 컴포넌트 단위로 모듈화하여 개발'인데, 지금 UI만 분리되어 있고 기능 단위는 전혀 분리되어 있지 않습니다.

2024-03-19 08:54 UTC, zigsong commented on src/service/RestaurantService.ts
> +    location.reload();
> Location.reload()를 통해 임시로 해결하긴 했지만 근본적으로 문제를 해결할 방법은 찾지 못했어요.

이 내용이군요. 임시방편일 뿐더러 모달에서 찜하기를 눌렀는데 reload시킴으로써 갑자기 화면이 홈으로 돌아가는 UX는 매우 좋지 않습니다. 

문제로 추정되는 코드에 대한 코멘트는 또 따로 남겨두었습니다

2024-03-19 08:54 UTC, zigsong commented on src/app/controller/AppController.ts
> +    }
`RestaurantInfoModal` 컴포넌트의 `addEvent`에서 `favoriteButton`에 `toggleFavorite` 이벤트를 붙여주고 있는데, 여기서 또 붙여주고 있나요? 이것이 원인이 아닐까요? 

게다가, 'button'에 붙어야 할 리스너가 `restaurantInfoModal` 전체에 붙고 있는지도 의문입니다.

2024-03-19 08:54 UTC, zigsong commented on src/app/controller/AppController.ts
> +    }
위의 `addRestaurantModal`도 같은 맥락으로, 이상한 곳에 이벤트리스너가 붙어있는걸로 보이네요

2024-03-19 08:54 UTC, zigsong commented on src/app/controller/AppController.ts
> +      restaurantInfoModal.dispatchEvent(customEvent);
다른 곳에 코멘트 남겨두었습니다. 코드가 너무나 복잡하게 얽혀있어 제가 솔루션을 바로 드리지 못하겠네요. 다른 코멘트들을 참고하여 구조를 개선하면 자연스레 해결될지도 모르겠습니다.

2024-03-19 08:54 UTC, zigsong commented on src/app/controller/AppController.ts
> +        dialogElement.showModal();
이 앱에는 `dialog`가 한개뿐이지만, 그것은 임의의 '가정'입니다. 

응당 `dialog` 태그로 작성된 요소가 여러 개 있을 것을 생각하고 작성해야 합니다.

2024-03-19 08:54 UTC, zigsong commented on src/app/controller/AppController.ts
> +  }
애초에 이 두 개의 함수가 나뉘어있었으면 안됐을 것 같아요.

결국 같은 기능을 하는데, 어디있느냐에 따라 함수가 분리되면 추후 버그를 찾기나 리팩토링하기가 매우 어려워집니다.

2024-03-19 08:54 UTC, zigsong commented on src/app/modal/RestaurantInfoModal/RestaurantInfoModal.ts
> +        const restaurantInfoModal = $<HTMLDialogElement>('#restaurant-info-modal');
`event` 값이 함수 본문에서 사용되지 않는다면 명시해줄 필요는 없습니다.

2024-03-19 08:54 UTC, zigsong commented on src/app/root/FavoriteNavBar/FavoriteNavBar.ts
> +import { IMAGE } from '../../../assets/assets';
안 쓰이고 있네요

2024-03-19 08:54 UTC, zigsong commented on src/app/root/FavoriteNavBar/FavoriteNavBar.ts
> +      <section class="favorite-tabnb-container">
`tabnb` 이건 무슨 말인가요?

2024-03-19 08:54 UTC, zigsong commented on src/app/root/FavoriteNavBar/FavoriteNavBar.ts
> +      });
다른 컴포넌트들에서도 느꼈는데, 불필요하게 모든 것에 `CustomEvent`를 붙이고 있는 것 같습니다.

컴포넌트별로 해야 할 기능들을 분리한다면 `CustomEvent`는 전부 제거되어도 무방합니다.

2024-03-19 08:54 UTC, zigsong commented on src/app/root/LunchHeader/LunchHeader.ts
> +      <header class="favorite-nb">
`header`가 2개인가요? 그리고 앱에서 `favorite-nb`는 사용되고 있지 않은 것 같습니다

2024-03-21 13:17 UTC, zigsong commented
안녕하세요, 제가 금주 3/22(금)~3/24(일) 부재로 리뷰가 어려울 것 같습니다. 리뷰 반영해주시면 월요일에 빠르게 보도록 할게요. 미리 양해 말씀 드립니다 🙇‍♀️

2024-03-22 07:05 UTC, greetings1012 commented on src/interface/Interface.ts
> +  referenceUrl?: string | undefined;
수정했습니다!
왜 이런 코드를 작성했는지 모르겠네요 😭

2024-03-22 07:07 UTC, greetings1012 commented on src/interface/Interface.ts
>  interface ILocation {
수정했습니다!
저번에도 리뷰하면서 지적받았던 내용인데 이번에도 똑같은 실수를 했네요 🥲
다음부터는 잊지 않고 꼭 예악어를 피해 예약하도록 하겠습니다!

2024-03-22 07:13 UTC, greetings1012 commented on src/constants/enums.ts
> +enum Category {
수정했습니다!
식당 카테고리만 담은 enum의 이름인데 굳이 포괄적인 이름일 필요가 없었네요!

2024-03-22 07:16 UTC, greetings1012 commented on src/app/root/FavoriteNavBar/FavoriteNavBar.ts
> +import { IMAGE } from '../../../assets/assets';
수정했습니다!

2024-03-22 07:17 UTC, greetings1012 commented on src/app/root/FavoriteNavBar/FavoriteNavBar.ts
> +      <section class="favorite-tabnb-container">
Tab Navigation Bar를 축약해 tabnb라고 표현했어요!

2024-03-22 07:21 UTC, greetings1012 commented on src/app/root/LunchHeader/LunchHeader.ts
> +      <header class="favorite-nb">
제거했습니다!
설계 초기에 '이 부분에 즐겨찾기 네비게이션 바를 만들어야지' 라는 생각을 했다가 노선을 바꾸면서 놓쳤네요 😥

2024-03-22 07:23 UTC, greetings1012 commented on src/app/modal/RestaurantInfoModal/RestaurantInfoModal.ts
> +        const restaurantInfoModal = $<HTMLDialogElement>('#restaurant-info-modal');
수정했습니다!

2024-03-22 07:32 UTC, greetings1012 commented on src/app/controller/AppController.ts
> +        dialogElement.showModal();
클래스로 불러오도록 수정했습니다.

자칫 잘못하면 addRestaurantModal의 dialog와 충돌해 이슈를 일으킬 뻔했네요!

2024-03-24 17:57 UTC, greetings1012 commented
리팩터링을 진행하던 중, 제 자신이 다시 봐도 이해가 가지 않는 코드들이 너무 많고 부분만을 고치기에는 더 상황이 악화될 것 같았어요.
그래서 처음부터 다시 코드를 작성해 step1 정도의 진도까지는 다시 만들어 두었습니다.
npm run start를 통해 한번 확인해주시면 감사하겠습니다.

2024-03-25 12:41 UTC, zigsong requested changes
안녕하세요 파란, 리뷰를 반영하시면서 처음보다 구조적인 개선이 많이 이뤄진 것 같습니다. 👍

원하신 대로 문제가 많이 해결되었으면 좋겠네요. 

코드 내용 상으로 구현되지 않은 부분이 있어, 코멘트 남겼습니다. 

미션의 기한이 꽤 지나 파란이 원하시는 대로 진행하도록 하겠습니다 :)

2024-03-25 12:41 UTC, zigsong commented on src/components/RestaurantItem/RestaurantItem.ts
> +  // TODO: 이벤트 추가
이곳에 이벤트가 추가되지 않아서인지 레스토랑 아이템 클릭 시 상세정보 모달이 나오지 않네요 👀 

혹시 구현하실 계획인가요? 

해당 미션의 기한이 많이 지나, 원하시면 머지하겠습니다. 구현하실 계획이라면 기다려드리겠습니다.

2024-03-26 08:43 UTC, greetings1012 commented on src/components/RestaurantItem/RestaurantItem.ts
> +  // TODO: 이벤트 추가
머지해주셨으면 합니다 😁

이번 미션의 목표가 '컴포넌트 분리'였던 만큼, 코드를 처음부터 다시 작성하면서 이전보다 컴포넌트를 분리하는 것에 대해 많이 알게 되었습니다.
또한 다음 미션과 중복되는 부분(modal 띄우기, 점수를 localstorage에 저장하기)이 많아 이 미션을 완성하는 것은 개인적인 방학 과제로 남겨두려고 합니다.

미션이 너무나도 늦게 끝나게 되었는데, 끝까지 피드백 남겨주셔서 진심으로 감사합니다!

2024-03-28 01:02 UTC, zigsong commented
안녕하세요 파란, 2단계 끝까지 고생하셨습니다! 말씀주신 대로 어프루브하겠습니다. 

다음 미션도 화이팅입니다! 💪

2024-03-28 01:02 UTC, zigsong approved these changes

2024-03-28 01:03 UTC, merged