[2단계 - 자주 가는 음식점] 올리(이예진) 미션 제출합니다.
woowacourse/javascript-lunch pull request #169
Opened 2024-03-18 08:32 UTC by ImxYJL

## To Reviewer

안녕하세요 블링! 우여곡절 끝에 구현 완료해서 리뷰 요청 드립니다.

우여곡절이 코드에 너무 잘 드러나 있어서 죄송스럽지만😂 이번에도 잘 부탁드립니다!

## 컴포넌트 분리

- 모달 재사용
    - 기존에 만들었던 모달 컴포넌트를 음식점 정보를 띄워 주는 컴포넌트를 만들 때 이용했습니다.
- `ImageButton`
    - 즐겨찾기 버튼의 동작을 추후 ‘좋아요’등의 하트 이미지 버튼에서도 사용할 수 있을 것 같아 재사용 가능하게 만들었습니다.
- `TabContainer`
    - 탭 요소 또한 범용적으로 사용되는 요소라 생각해서 추후에 사용할 수 있게끔 분리했습니다.

## 커스텀 이벤트 사용

웹 컴포넌트를 사용해서 요소를 렌더링하면 컴포넌트 간에 데이터를 주고받기가 어려워서 커스텀 이벤트를 사용했습니다.

- 예시: `FavoriteButton.ts`
    
    즐겨찾기 등록/해제에 대한 처리를 하려면 클릭 이벤트가 발생한 요소에서 도메인(로컬 스토리지 처리 담당)으로 음식점 정보가 수정됐음을 알려줘야 하는데, 일반적인 방법으로는 직관적으로 정보를 전달하기 어려워서 사용했습니다.
    

```tsx
private handleFavoriteButtonClick(event: Event) {
    const targetElement = event?.target;

    // toggle 이벤트를 발생시키며 음식점 이름 전달
    this.emit(CUSTOM_EVENT_TYPE.toggleFavoriteButton, { 
      restaurantName: this.favoriteButtonConfig.id,
    });
} 
```

- `RestaurantList.ts`

```tsx
// 도메인(restaurant)에 변경이 발생한 음식점 이름 전달
private handleToggleFavoriteButton(event: Event) {
    const customEvent = event as CustomEvent;
    this.restaurant.toggleFavoriteStatus(customEvent.detail.restaurantName);
}
```

## 동적 렌더링

- `RestaurantList` 이하의 요소들은 활발하게 추가, 삭제, 수정이 이루어지므로 동적으로 렌더링했고, GNB, 드롭다운 요소들, 모달의 뼈대는 정적으로 처음에만 렌더링했습니다.
    - 모달 내용은 동적으로 결정됩니다.

## E2E 테스트

- 일차적인 동작 일부만 테스트했고, 복합적인 동작은 테스트하지 못했습니다.
    - 예) 음식점 추가 모달에서 음식점 정보를 추가하면 레스토랑 리스트에 렌더링되는지 확인 (o)
        
        전체 음식점 리스트에서 어떤 음식점을 클릭해서 모달을 띄운 뒤 즐겨찾기를 누른 경우, 모달을 닫았을 때(새로고침 없이) 전체 음식점 리스트에서 그 음식점의 즐겨찾기가 활성화됨을 확인 (x)
        

## 아쉬운 점

- 전반적으로 시간에 쫓겨 보기 좋게 리팩토링하지 못했습니다.
- 버튼이나 List 요소도 재활용 가능할 것 같지만 만들지 못했습니다.
- 컴포넌트를 깔끔하게 만들어 보기 위해 웹 컴포넌트를 도입했는데, 사용이 미숙해서인지 오히려 사용하지 않았을 때보다 더 알아보기 힘든 느낌이라 아쉬웠습니다.
- 이번 미션의 주요 학습 목표는 아니지만 UI를 만들 때 TS를 TS답게 사용하지 못한 것 같아 아쉽습니다.

2024-03-18 14:31 UTC, uk960214 requested changes
수고 많으셨습니다 올리! 웹 컴포넌트를 활용해서 컴포넌트를 알기 쉽게 잘 구성해주신 것 같아요.
로직에서 조금 복잡한 부분들이 있었는데 질문은 코멘트로 남겼습니다.

다만 제가 지금 크롬의 개발자 도구로 보고 있는데 화면이 깨져서 보이더라구요
<img width="300" alt="image" src="https://github.com/woowacourse/javascript-lunch/assets/43166681/eb52c4e2-0533-4a19-9fb9-fcb98f71efd4">

1. 전체적으로 깨져서 보입니다.
2. 탭 중간 부분을 클릭하면 선택된 탭이 없는 케이스가 발생합니다!
3. 셀렉트도 이상한 위치에 뜨는 것 같아요.
제가 무언가 잘못보고 있는걸까요..? 로컬에서 실행해도 동일하게 나오네요. 확인 부탁드립니다!

2024-03-18 14:31 UTC, uk960214 commented on src/utils/createLiElements.ts
> +    const tabClass = index === 0 ? "tab-item tab-item-selected" : "tab-item";
함수명으로 추측할 수 있는 것은 li 요소를 만드는 것인데요,
실제 내부 구현에는 tab이 아니면 활용하기 힘들 것 같은 느낌이 드네요!
조금 더 공용으로 사용할 수 있게 변경하거나, 함수명을 변경해보는 것이 어떨까요?

2024-03-18 14:31 UTC, uk960214 commented on src/utils/TabContainer/TabContainer.ts
> +        );
오호 toggle에 두번째 인자가 있는 줄은 몰랐네요! 멋집니다 👍

2024-03-18 14:31 UTC, uk960214 commented on src/utils/ImageButton.ts
> +class ImageButton extends BaseComponent {
이름 자체는 ImageButton인데, 실제로 인터페이스와 구현은 두가지 이미지를 받고 둘 사이를 toggle하는 로직으로 구현되어있어서 오해의 소지가 있어 보입니다. 이것도 조금 더 포괄적으로 바꾸는 것이 어떨까요?

2024-03-18 14:31 UTC, uk960214 commented on src/domain/Restaurant/Restaurant.test.ts
이 테스트는 왜 주석처리가 되어야 했나요?

2024-03-18 14:31 UTC, uk960214 commented on src/domain/Restaurant/Restaurant.ts
> +    }
이 클래스에서는 restaurantDetails를 너무 복잡하게 변경하고 있는 것이 아닌가 생각이 들었습니다.
this.restaurantDetails를 너무 다양한 곳에서 직접 변경 시켜주면서 그 데이터의 흐름을 파악하기가 어려운 것 같아요.
후에 만약에 기능에 오류가 생긴다면 수정하기 위해서 코드를 파악하는데 분명 시간이 오래 걸릴 것 같습니다.
이 흐름을 더 단순하게 수정할 수 있을까요?

2024-03-18 14:31 UTC, uk960214 commented on src/components/RestaurantList/RestaurantList.ts
> +    if (!restaurantName) return;
이 얼리 리턴은 두 가지를 합할수는 없을까요?

2024-03-18 14:31 UTC, uk960214 commented on src/components/LunchApp/LunchApp.ts
> +      }
타입을 좁혀주는 것 좋습니다!

2024-03-18 14:31 UTC, uk960214 commented on cypress/e2e/restaurant.cy.js
> +  });
1. 테스트 명세가 명확하지 않아서 무엇을 테스트하고자 하는지 확실히 알기가 어렵습니다.
2. 테스트 로직이 복잡해서 어떤 방식으로 무엇을 테스트하는지 파악하기가 어렵습니다.
3. 불필요한 주석은 제거해도 좋을 것 같습니다.

2024-03-19 02:43 UTC, ImxYJL commented on src/domain/Restaurant/Restaurant.test.ts
음식점 정보를 저장하는 `RestaurantDetail` 인터페이스에 `favorite`을 필수 속성으로 추가했더니 기존 도메인 테스트에서 타입 오류가 나서 일시적으로 주석처리를 했습니다.
```ts
export interface RestaurantDetail {
  category: MenuCategoryWithoutAll;
  name: string;
  distance: Distance;
  favorite: boolean;
  description?: string;
  url?: string;
}
```

2024-03-19 02:52 UTC, ImxYJL commented
@uk960214 레이아웃 관련해서 코멘트 드립니다!

1. 전체적으로 깨지는 현상: 이번 미션에서는 반응형 웹을 구현하라는 요구사항이 없었고, 기본적으로 주어졌던 템플릿도 px 단위를 사용하고 있어서 그에 맞춰 작업해서 그런 것 같습니다. 일단 화면이 작은 모바일 환경에서는 깨져 보일 것 같습니다..! 다른 크루들의 노트북 화면에서는 크게 깨지는 부분이 없었는데, 다른 문제라면 다시 코멘트 부탁드릴게요!
2. 탭에서 어중간한 위치를 누르면 둘 중 어느 것도 선택되지 않는 것처럼 보이는 문제는 버그가 맞습니다 😅 추후 수정해서 반영하겠습니다.

2024-03-25 01:19 UTC, ImxYJL commented on cypress/support/commands.ts
테스트에 딸린 파일들은 cypress를 처음 실행했을 때 만들어진 파일들인데 혹시 나중에 필요한가? 싶어서 제거하지 않았다가 같이 올라갔습니다 지금은 필요하지 않은 것 같아 삭제하도록 하겠습니다!

2024-03-25 01:21 UTC, ImxYJL commented on src/components/CategoryDropdown/CategoryDropdown.ts
> -  }
원래 어떤 컴포넌트가 사라질 때 그에 딸린 이벤트 리스너들을 지우기 위해 만든 메서드였습니다. 그런데 렌더링 방식을 `innerHTML`을 완전히 갈아끼우는 방식으로 진행했더니 컴포넌트가 너무 빨리 지워져서 `removeEvent`에서 대상 요소를 찾을 수 없다(NULL)는 에러가 나서 삭제한 코드입니다 😅

2024-03-25 01:24 UTC, ImxYJL commented on src/utils/ImageButton.ts
utils에 있는 컴포넌트들은 직접적으로 사용되지 않고 특정 컴포넌트의 뼈대가 되는 컴포넌트들입니다. `ImageButton`은 어플리케이션 안에서 `<ImageButton>`으로 바로 사용되지 않고 `FavoriteButton`과 같은 요소들이 그것을 이용하기 때문에 utils에 넣었습니다!

2024-03-25 01:26 UTC, ImxYJL commented on src/utils/ImageButton.ts
> +class ImageButton extends BaseComponent {
제가 제안을 잘 이해하지 못했는데, `ImageButton` 이라는 이름이 역할에 비해 너무 좁은 영역만 커버하는 이름인지, 아니면 역할 자체를 잘 반영하지 못하고 있다는 말씀이신지 잘 모르겠습니다.

2024-03-25 01:41 UTC, ImxYJL commented
안녕하세요 블링! 리뷰 반영이 늦어 너무 기다리시게 만든 건 아닌가 싶네요 😓  

다음에는 pr이 늦을 것 같으면 미리 리뷰어님께 연락 드리도록 하겠습니다.

늦었지만 잘 부탁드립니다..!!!                                                                                              

## Main Changes

- 도메인 로직을 보다 명확하게 수정
    - 내용이 겹치는 메서드 통폐합, 동작이 모호한 메서드 이름을 변경
        - ex) 로컬 스토리지의 모든 내용을 가져오는 함수의 이름을 `get` → `getAll`로 변경
        - 어디에 있는 레스토랑 정보를 업데이트하는 것인지 불분명한 `updateRestaurant` → `updateLocalStorage`
    - `Restaurant` 도메인에서 `RestaurantStorage`에서 담당하는 로컬 스토리지 직접 접근을 했던 문제 수정
- Tab에서 어중간한 위치를 누르면 아무 것도 선택되지 않은 것처럼 보이는 버그 수정

## Questions

- 테스트 코드에서 폼 제출이 기본 동작으로 필요할 때, 폼을 실제로 작성하기 위한 코드가 길어지는 것 같습니다. 이런 동작은 실제로 제출하지 않고 모킹을 통해서 진행하는지 궁금합니다.
- 기존 코드도 도메인 로직에 대한 캡슐화 정도가 강하지는 않았지만, 리팩토링을 거치면서 모든 메서드를 `public`으로 풀어 놓게 되었습니다. 단순 콘솔에서만 동작하는 어플리케이션을 넘어 웹 UI와 연결되면서 getter를 어디까지 사용해야 하는지, 캡슐화는 어디까지 필요한지에 대한 고민이 항상 듭니다.
    
    도메인 로직은 항상 어느 정도의 캡슐화는 필요하다고 보시는지 궁금합니다.

2024-03-25 11:40 UTC, uk960214 approved these changes
안녕하세요 올리! 다음 미션을 진행하면서 마무리 해주시느라고 고생많으셨습니다!

> 폼 테스트

- 폼을 작성하기 위한 코드가 길어지더라도, 해당 폼을 검증하기 위한 테스트라면 다 작성해주어야 하지 않을까요? 코드가 길어지는 부분은 충분히 리팩토링을 통해서 해소될 수 있을 것이라고 보입니다. cypress command를 사용해서 반복적인 액션을 계속 작성하는 것을 방지할 수도 있구요. 모킹의 대상은 될 수 없다고 생각합니다. 테스트에서 어떤 부분을 모킹할지 말지는 기준이 있어야 할텐데 이 부분에 대해서 고민해보면 좋을 것 같습니다.

> 도메인 로직 캡슐화

- 아무래도 UI에서 호출해서 실행되어야 하는 도메인 로직은 외부로 노출될 수 밖에 없을 것 같아요. 캡슐화라는 것이 단순히 어떤 값을 private으로 설정한다는 관점이 아니라 '객체의 값을 직접 변경시키는 것이 아니라 메시지를 보내는 것'의 관점에서 접근하는 것이 더 좋지 않을까 생각합니다. 지금도 충분히 잘 캡슐화 되어있다고 보입니다! 만약에 지금 도메인의 로직이 더 복잡해진다면 (ex. 필터와 정렬을 하기 위해 몇 단계의 복잡한 알고리즘이 추가된다거나) 그런 로직들은 매서드가 분리되어서 은닉되게 되지 않을까요? 노출되는 부분은 지금과 동일할 것이구요!

이런 부분들은 앞으로도 다른 미션들을 진행하면서 계속 고민해보시면 좋을 것 같아요!
수고 많으셨고 앞으로 미션들도 화이팅입니다!!

2024-03-25 11:41 UTC, merged