[2단계 - 자주 가는 음식점] - 제이드(전세영) 미션 제출합니다.
woowacourse/javascript-lunch pull request #177
Opened 2024-03-18 08:56 UTC by skiende74

### 구현의도 및 신경쓴 점

### innerHTML(가독성) vs XSS(보안성) 문제
보안성은 포기할수 없는 문제인데
태그를 템플릿으로 넣어주는 가독성도 포기하고싶지않았습니다.

### 아쉬운점

###

2024-03-18 16:17 UTC, moonheekim0118 requested changes
안녕하세요 제이드~! 2단계 미션 구현해주신 것 잘봤습니다. 👏 

여러 `Headless`컴포넌트를 만들어주셨다고 적어주셨는데요, 구현해주신 사항이 실제로 프론트엔드에서 사용되는 Headless의 개념과는 다르니 이 점 참고부탁드려요!
어떤 기준으로 Headless라고 분리해주셨는지도 궁금하네용.

간략하게 말씀드려보자면...Headless 컴포넌트는 UI에 대한 제어권은 사용처에 위임한채 로직만 가지고 있는 컴포넌트를 말하곤 합니다. 이 관점으로 이게 왜 필요한지, 어떻게 만들지 다시 한번 생각해봐주세요ㅎㅎ

headless관련 아래 자료들 추천드립니다. :) 
- https://www.youtube.com/watch?v=fR8tsJ2r7Eg&t=218s
- https://so-so.dev/react/make-select/#%EB%B2%88%EC%99%B8-1-%EC%9E%90%EB%8F%99%EC%99%84%EC%84%B1-select


추가로 코드 내에 타입단언+불필요해보이는 코드가 많은데 쫙 정리해봐주시면 좋을 것 같아요 :) 
그럼 고생하셨어요! 👍

2024-03-19 15:41 UTC, skiende74 commented on src/components/AllRestaurantApp.ts
> +    return newRestaurantList;
반영하였습니다.

2024-03-19 15:41 UTC, skiende74 commented on src/components/Basic/FavoriteIcon.ts
> +    }
반영하였습니다.

2024-03-21 15:29 UTC, skiende74 commented on src/components/OnOffButton.ts
> +      }
else를 피하는 측면에서 도움이될거같네요..!

2024-03-21 15:32 UTC, skiende74 commented on src/components/RestaurantList/RestaurantItem.ts
> +    this.#favoriteIcon.set(this.#isFavorite);
네.!  생각해보니 제너레이터와 널체크를 해주면 좋을거같고
계속사용되기때문에 이를 유틸함수로 만들어줬습니다. !

2024-03-24 13:23 UTC, skiende74 commented on src/components/Basic/VerticalInputBox.ts
> +    }
그런거같습니다.

2024-03-24 17:34 UTC, skiende74 commented
### 불필요한 타입단언 제거
- querySelector사용시  타입 검사를 실행하고 타입단언을 제거하였습니다.
 - dom.js파일의 dom.getElement 제네릭에서 일괄 처리
- 그 외 필요시 타입가드를 사용하여 타입단언을 줄였습니다.

#### Vertical Inputbox를 styleVariant 로 주입받는 것이
좋을 것 같다는 말씀에 저도 공감을하여 horizontal, vertical을 주입받게하여 바꾸었습니다.

### NewRestaurant 모달의 상속패턴 제거 (조합패턴으로 수정)
NewRestaurantModal는 여전히 BasicModal을 상속하고있었어서 
이녀석도 상속->조합패턴으로 변경하였습니다.

### NavTab, BasicModal, OnOffButton은 Headless했나에 대한 생각

UI없이 기능만 가진 컴포넌트라는 측면에서 다시생각해본결과

각 컴포넌트들이 현재 외부로부터 주입받은 children들을 이용하여 기능을 추가해주지만,
해당 컴포넌트들(NavTab, BasicModal)이 여전히 자신들의 .css를 가지고있어
기본 UI를 가지고있기에 headless로 보기 어려운 게 맞는 것 같습니다.

OnOffButton은 UI가 없고, (css도 없고)
실제버튼이아니라 Div태그이며 클릭시마다 버튼토글기능을 추가해주는 요소이기떄문에
headless가 맞는거같습니다.

NavTab은 현재 OnOffButton의 컨테이너로서,
On 되어있는 요소 하나만 알려주고,
내부의 다른 버튼 클릭시 나머지버튼을 전부 꺼주는 역할인데,
현재 css가 붙어있어 headless라고 보긴 어려운거같습니다.

이 NavTab을 headless로 만들어서 잘 활용하면, 
현재 모달 컨테이너 내의 요소를 hidden을 끄고켜는것에도 활용할수있을 것은 같은데
우선은 현재상태 대로 두었습니다.


### 질문드리고 싶은 것

domains/entities/RestaurantCollection.ts에서 
sort대신 불변성을 유지하는 toSorted를 사용하고싶어서 toSorted로 하였는데

toSorted를 썼더니 Property 'toSorted' does not exist on type 'IRestaurant[]' ts(2339) 에러가 발생
에러가 발생하였고, 이에대한 일반적 조치들을 해보아도 고쳐지질 않아 질문드리고싶습니다.

#### 질문드리기 전에 해본것
- tsconfig.json을 target: ESNext로 하고, lib에 ESNext, ES2023로 고쳐 봄.

- 생각&조사: 분명 toSorted는 ES2023 규격이라 될 것으로 기대했는데.
조사해보니 현재환경은  tsc(ts컴파일) -> babel(es5버전으로 바꿔줌) -> webpack(번들링)

현재 환경을 분석해본결과
tsc는 ESNext를 받아서, ESNext로 나가게하고 (ESNext는 ES2023을 포함하고 있다고 생각했습니다..)
babel에서 es5로 바꿔주게하면 되는게 맞는 것 같은데
현재 저 에러가 계속 보이고있는 상태입니다.

(우선은 불변성이있는 map을 통과한후 sort를 통과하게해둬서 불변성역할은 하게 해두었습니다.)

2024-03-24 17:35 UTC, skiende74 reviewed
안녕하세요 호프!
전체적인 구조를 고민하고 수정하느라 시간이 조금 걸렸습니다.
이번에 말씀해주신 개선점들도 더 생각해보고 반영해보았습니다.

배포링크 : [링크](https://skiende74.github.io/javascript-lunch/dist)


## 🔧 수정사항

### 불필요한 타입단언을 제거
- querySelector사용시  타입 검사를 실행하고 타입 단언을 제거해보았습니다.
 - 위 타입검사를 dom.js파일의 dom.getElement 제네릭함수에서 일괄 처리
- 그 외 필요할 때 타입가드를 사용하여 타입단언을 줄였습니다.

### Vertical Inputbox를 styleVariant 로 주입
styleVariant를 주입받는것이 좋을 것 같다는 말씀에
공감을하여 horizontal, vertical을 주입받게 바꾸었습니다.

### NewRestaurant 모달의 상속패턴 제거 (조합패턴으로 수정)
Detail모달은 조합패턴을 사용하고있었지만
NewRestaurantModal는 여전히 BasicModal을 상속하고있었어서 
이녀석도 상속->조합패턴으로 변경하였습니다.

### 불필요한 컴포넌트를 제거
CategoryIcon의 기능을 RestaurantCategoryIcon에 합쳐도 충분히 괜찮을 거같아서 제거하였습니다.
BaseComponent도 Base로 상속하려고만들었었으나, 현재 필요 없어져서 제거하였습니다.

## 📖 학습한 내용

### NavTab, BasicModal, OnOffButton가 Headless하지 않다는 말씀에 대해 생각해보았습니다

올려주신 자료를 보고 ,말씀해주신 내용을 생각해본결과
Headless는 UI(외형)없이 기능만 가진 컴포넌트 인것같다고 생각을 하였습니다.

지금은 각 컴포넌트들이 현재 외부로부터 주입받은 children들을 이용하여 기능을 추가해주기는 하지만,
(NavTab, BasicModal)컴포넌트들은 여전히 자신들의 .css를 가지고 있어
기본 UI를 가지고 있기에 headless로 보기 어려운 게 맞는 것 같습니다.


또, OnOffButton은 UI가 없고, (css도 없고)
실제버튼이아니라 Div태그이며 클릭시마다 버튼토글기능을 추가해주는 요소이기때문에 headless가 맞는 거 같다고 생각했습니다.

NavTab은 현재 OnOffButton의 컨테이너로서,
On 되어있는 요소 하나만 알려주고,
내부의 다른 버튼 클릭시 나머지버튼을 전부 꺼주는 역할인데,
현재 css가 붙어있어 headless라고 보긴 어려운거같습니다.

이 NavTab을 headless로 만들어서 잘 활용하면, 
현재 모달 컨테이너 내의 요소를 hidden을 끄고켜는것에도 활용할수있을 것은 같은데
우선은 현재상태 대로 두었습니다.


## ❓질문드리고 싶은 것

domains/entities/RestaurantCollection.ts에서 
sort대신 불변성을 유지하는 toSorted를 사용하고싶어서 toSorted로 하였는데

toSorted를 썼더니 Property 'toSorted' does not exist on type 'IRestaurant[]' ts(2339) 에러가 발생
에러가 발생하였고, 이에대한 일반적 조치들을 해보아도 고쳐지질 않아 질문드리고싶습니다.

#### 질문 드리기 전에 시도 해본 것
- tsconfig.json에서 target: ESNext로 하고, lib에 ESNext, ES2023를 추가해 봄.
- babel.config.js에서 @babel/preset-typescript 프리셋을 확인함

- 생각&조사: 분명 toSorted는 ES2023 규격이라 될 것으로 기대했는데.
되지않아서 우선 현재환경을 조사해보았고
그 결과 현재환경이
tsc(ts컴파일 TS->JS) -> babel(JS esnext-> JS es5) -> webpack(bundle.js로 번들링)

상태인 것 같다고 분석했습니다.

그러니
tsc는 ESNext를 받아서, ESNext(JS)로 나가게하고 (ESNext는 ES2023을 포함하고 있다고 생각했습니다..)
babel에서 es5로 바꿔주게 하면 되는 게 맞는 것 같은데
현재 저 에러가 계속 보이고있는 상태입니다.

(우선은 불변성이있는 map을 통과한후 sort를 통과하게해둬서 불변성역할은 하게 해두었습니다.)

2024-03-24 17:35 UTC, skiende74 commented on src/components/MainApp.ts
모달은 하나만 사용하고, 
내부에 여러개를 담아서 필요할때 원하는것만 visibility:visible을 해주는 식으로 변경하였습니다.

[d0ca3b1](https://github.com/skiende74/javascript-lunch/commit/d0ca3b1fde69d60b36df72635ea7c8087f290000)


----
(추가로 basic-modal을 상속하던 new restaurant modal 컴포넌트를
제거하였습니다.
basic-modal을 상속하는 컴포넌트 없이, 
children을 넣어주면 알아서 작동하게
상속대신 조합패턴이 되게끔 수정하였습니다.)

2024-03-25 14:08 UTC, moonheekim0118 approved these changes
안녕하세요 제이드! 다른 미션과 병행해서 진행해주시느라 정말 고생많으셨습니다ㅎㅎ
변경사항과 headless 컴포넌트에 대해 남겨주신 생각도 잘 읽었어요. 공유해주셔서 감사해요 :)

>  'toSorted' does not exist on type 문제

제가 제이드의 코드를 클론 받아서 실행해 본 결과 제 환경에서는 해당 에러가 발생하지 않고 있습니다 ...😮 
<img width="692" alt="스크린샷 2024-03-25 오후 10 53 10" src="https://github.com/woowacourse/javascript-lunch/assets/61469664/8f3493d5-bb02-49c5-a5df-7a0f18da87f7">

추측컨데 node 버전 문제일 수도 있을 것 같은데요, 혹시 node 몇버전 쓰시나요? toSorted 는 node 20 버전 이상부터 지원한다고 하네요ㅎㅎ한번 참고해봐주세요!

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted

그럼 고생하셨습니다 :) 리팩토링도 전반적으로 잘 해주셔서 이만 점심뭐먹지는 마무리 지을게요~
다음에 또 뵈어요~ 🍀

2024-03-25 14:09 UTC, merged