[1단계 - 음식점 목록] 라잇(강영민) 미션 제출합니다.
woowacourse/javascript-lunch pull request #20
Opened 2023-03-03 08:26 UTC by kangyeongmin

2023-03-04 09:44 UTC, Tanney-102 requested changes
안녕하세요 라잇~ 리뷰어 브콜입니다.
전반적으로 깔끔하게 잘 구현해주신 것 같습니다!
크게 지적할만한 점은 없었고 자잘한 코멘트만 남겨두었어요.

> 현재 괄호 표기법(객체명 우측에 대괄호[] 안에 키 값을 문자열로 작성)을 사용하는 코드에서 type 정의가 어려워 any로서 구현을 하였습니다. 혹시 typescript에서는 괄호 표기법을 잘 사용하지 않는지 혹은 현재의 any들을 다른 타입으로 지정할 수 있는지에 대해 궁금합니다.

어려웠던 타이핑 예시를 알려주시면 답변드리기 좋을 것 같습니다.

> 현재 domain 안의 model이 restaurant 하나인데, 해당 클래스는 생성 이외에는 다른 일(메소드)을 하지 않습니다. 이러한 경우에 단위테스트를 하지 않아도 되는 것이 옳은지 궁금합니다.

관련해서 코멘트 드렸습니다!

2023-03-04 09:44 UTC, Tanney-102 commented on src/domain/Controller.ts
> +    );
restaurants의 타입을 알고 있지 않나요? a, b가 왜 any가 되어야 하나요?

2023-03-04 09:44 UTC, Tanney-102 commented on src/domain/Controller.ts
> +    if (key !== "전체") {
가능하면 상수화를 해주세요

2023-03-04 09:44 UTC, Tanney-102 commented on src/domain/model/Restaurant.ts
> +export default Restaurant;
RestaurantType을 인자로 받아서 RastaurantType의 단순 객체로 생성한 하는 건 크게 의미 없는 행동인 것 같습니다.
이 클래스가 왜 존재해야하는 지 모르겠어요~

2023-03-04 09:44 UTC, Tanney-102 commented on src/index.js
> +globalThis.controller = controller;
controller가 꼭 global 하게 공개되어 있어야 할까요?
모듈에서 싱글턴으로 export 하고 필요한 사용처마다 import 하는 방법도 있을 것 같아요

2023-03-04 09:44 UTC, Tanney-102 commented on src/components/AddRestaurant.ts
> +    const cancelButton = document.getElementById("cancelButton");
document 수준에서 query를 하면 이 컴포넌트가 하나만 더 렌더되어 있어도 정확하게 엘리먼트를 가져오기 어렵지 않을까요?
```suggestion
    const cancelButton = this.getElementById("cancelButton");
```

2023-03-04 09:44 UTC, Tanney-102 commented on src/components/AddRestaurant.ts
> +      this.controller.setLocalStorage();
setLocalStorage까지 여기서 해줄 필요는 없어보입니다

2023-03-04 09:44 UTC, Tanney-102 commented on src/components/RestaurantItem.ts
> +  }
깔끔한 분기네요👍

2023-03-04 15:02 UTC, kangyeongmin commented on src/domain/model/Restaurant.ts
> +export default Restaurant;
해당 코드를 구현할 당시에도 "이게 맞나.."라는 의문이 많이 들었었는데, 이제 해결이 되었네요.
앞 전 미션들에서 mvc패턴을 사용하며 model을 class를 통해 정의하다보니, 
이번 미션에서 Restaurant class를 정의하게 된거 같습니다. 
RestaurantType이 존재하면 불필요한 것이네요💡 수정하겠습니다~

2023-03-04 15:41 UTC, kangyeongmin commented on src/domain/Controller.ts
> +    );
이것이 바로 제가 pr 내역에 질문 드렸던 1번 사항입니다!

이름순, 거리순의 정렬을 한번에 처리하고 싶어서 key값을 인자로 받고 잇는데, 인자를 통해 괄호 표기법으로 object의 key값을 참조하다 보니 타입 지정이 어렵게 되어 any로 설정하게 되었습니다. 

정렬함수에서 한번에 distance와 name을 처리하는 것을 포기하고
`(a: RestaurantType, b: RestaurantType) => (a.distance - b.distance)`
이렇게 하는 방식이 나을지는 좀 더 고민해보겠습니다! 브콜의 생각은 어떠신가요?

2023-03-06 05:50 UTC, kangyeongmin commented on src/index.js
> +globalThis.controller = controller;
전역으로 공개되어 있는 것보다 싱글톤 패턴이 적합하겠네요!
수정하겠습니다.

2023-03-06 06:01 UTC, kangyeongmin commented on src/domain/Controller.ts
> +    );
++ 타입 가드를 통해 문제를 해결하였습니다!!

2023-03-06 06:28 UTC, kangyeongmin commented on __tests__/render.test.js
> +    globalThis.controller = controller;
싱글톤으로 수정하여 커밋하였습니다!

2023-03-06 06:36 UTC, kangyeongmin commented on src/components/AddRestaurant.ts
> +    const cancelButton = document.getElementById("cancelButton");
```
const cancelButton = document.querySelector(
      "#restaurantForm > div > #cancelButton"
    );
```
현재 위와 같이, cancelButton이 restaurantForm안의 취소 버튼만 가리키도록 수정하였습니다. 

this로 스코프를 지정하여 하는 방법은 시도해보았지만 타입 관련 에러가 뜨더라구요.. 
suggested change처럼, typescript에서 this로 element를 가리키는 방법에 대해서 좀 더 자세히 말씀해주실 수 있으실까요?

2023-03-06 06:44 UTC, kangyeongmin commented
안녕하세요 브콜~🥦
달아주신 comment들 반영하여 커밋하였습니다!

그 중 의문점이 남아있는 comment 두가지는 다음과 같습니다~

1. 괄호표기법 comment와 관련하여,,
: 남아있던 any들을 타입가드 지정을 통해 해결하였는데, 괜찮은 해결법인지 궁금하네요~
2. 'document 수준에서 query를 하면 이 컴포넌트가 ..'와 관련하여,,
: 대댓글 확인해주시면 감사하겠습니다!

2023-03-06 15:02 UTC, Tanney-102 requested changes
안녕하세요 라잇~
리뷰 반영해주신 것 확인했습니다.
질문 주신 것 코멘트로 남겼으니 확인 부탁드려요!
그리고 지난 리뷰에서 놓친 것인지 조금 의아한 부분이 있었어요~
controller라는 이름의 모듈은 위치도 domain 하위이고 실제 역할도 domain에 가까운 것 같은데 view를 담당하는 컴포넌트를 너무 잘 알고 있는 것 같아요.
컨트롤러가 컴포넌트를 몰라도 되도록 개선해보시기를 권장드립니다!

2023-03-06 15:02 UTC, Tanney-102 commented on src/components/AddRestaurant.ts
> +  }
this에 getElementById 가 없는 게 맞네요~
getElementById는 document객체에만 있는 속성이라 HTMLElement에는 없는 게 맞습니다.
querySelector를 사용하시면 될 것 같습니다. (`this.querySelector(...)`)
아마 this에 getElementById가 없다는 식으로 에러 메시지가 나왔을 것 같은데 그럴 때는 직접 타입 정의를 살펴보시면 좋습니다.
this는 HTMLElement를 상속하므로 HTMLElement의 타입 정의를 살펴보면 되겠죠~
(vscode에 경우 cmd + 클릭으로 특정 타입의 정의를 확인할 수 있습니다.)

2023-03-07 04:40 UTC, kangyeongmin commented on src/components/AddRestaurant.ts
> +  }
아하 그런 방법이 있군요~ 다음부터 타입정의에 유의하겠습니다!

2023-03-07 05:20 UTC, kangyeongmin commented
> 안녕하세요 라잇~ 리뷰 반영해주신 것 확인했습니다. 질문 주신 것 코멘트로 남겼으니 확인 부탁드려요! 
네~ 브콜!
질문에 대한 답변 감사드립니다! 앞으로 document말고 this를 통해 element를 지정하도록 유의해야겠어요!

> 그리고 지난 리뷰에서 놓친 것인지 조금 의아한 부분이 있었어요~ controller라는 이름의 모듈은 위치도 domain 하위이고 실제 역할도 domain에 가까운 것 같은데 view를 담당하는 컴포넌트를 너무 잘 알고 있는 것 같아요. 컨트롤러가 컴포넌트를 몰라도 되도록 개선해보시기를 권장드립니다!

리뷰 달아 주신 이후에, 새로운 식당 아이템을 추가할 때마다 필터링과 정렬기능이 유동적으로 작동하지 않는 버그를 해결하기 위해,
controller상에서 SortingSelectBox, CategorySelectBox component의 select option 값을 읽어와 메소드를 곳곳에서 호출하는 로직을 추가하였는데요,, 
브콜의 리뷰처럼, 현재 component상에서도 controller를 가지고 있고 controller상에서도 component를 참조하고 있는 것이 바람직하지 않은 것 같네요.. 
따라서! 현재 component에서 controller의 sortRestaurants, filterRestaurants 메소드를 호출하는 방식으로 수정하여 커밋하였습니다!
감사합니다😊

2023-03-08 16:33 UTC, Tanney-102 approved these changes
안녕하세요 라잇!!
반영해주신 것 확인했습니다~
코멘트 하나 더 남겼는데 요건 다음 스텝에서 고민해주세요.
고생많으셨습니다!

2023-03-08 16:33 UTC, Tanney-102 commented on src/domain/Controller.ts
> +  }
여전히 도메인이 view를 알고 있군요~
요것도 개선해볼 여지가 없을지 고민해보시면 좋겠습니다!

2023-03-08 16:33 UTC, merged