[1단계 - 음식점 목록] 수아(최수현) 미션 제출합니다.
woowacourse/javascript-lunch pull request #29
Opened 2023-03-03 08:43 UTC by chsua

### 0. **[웹사이트 바로가기](https://github.com/woowacourse/javascript-lunch/pull/10)**

### 1. 구상
 - **컴포넌트 분리:** 컴포넌트를 처음 접했습니다. 때문에 컴포넌트가 무엇인지를 익히는 것이 가장 우선이었습니다. 페어와 이야기한 끝에 컴포넌트를 html 태그 중 기능을 가지는 것으로 정의하고 이를 하나의 파일로 만들었습니다. 해당 컴포넌트 파일은 컴포넌트를 랜더링할 수 있게 템플릿을 가지고 있고, 이벤트-모달창을 키거나, 필터를 하는 등-를 가지고 있는 경우 이벤트를 부여하는 함수를 포함했습니다.
 - **레스토랑 리스트 = 도메인**: 도메인을 분리해야 하지만 하지못했습니다. 대신 필터, 정렬, 추가 등의 기능이 최종적으로 레스토랑 리스트를 변형 시키는 것이기 때문에 이 파일에서 도메인을 많이 수행하고 있습니다. 더불어 각 이벤트가 부여되는 과정에서 도메인이 산발적으로 흩어져 있습니다.
 - **최종적으로** 인덱스를 호출하면 앱이 호출되고, 앱은 처음 화면을 랜더링하고 이벤트를 부여합니다. 이후 이벤트 발생에 따라 진행이 됩니다.
 - **로컬 스토리지**는 미션사항에 있어 적용했습니다. 
<br>

### 2. 생각한 점
 - 최초에 설계할때 레스토랑과 레스토랑 리스트를 클래스로 만들었습니다. 해서 레스토랑 리스트는 레스토랑 클래스를 가지고 있었고, 앱은 레스토랑 클래스를 가지고 있었습니다. 하지만 이 과정에서 필터, 정렬 같은 이벤트리스너에서 레스토랑 모음에 접근할 수 있는 방법이 없었습니다. 해서, 이를 **객체 안 배열로 레스토랑 모음을 저장**하도록 만들었고, 객체는 객체답게에서 외부에서 자칫 객체 안의 정보를 수정할 수 있다는 점을 지적하는 것을 이용해 **밖에서 객체 안 내용을 수정할 수 있도록 만들어 해결**했습니다. 클래스로 모음을 만드는 경우 다른 곳에서 부르기가 어려워 이런 방법을 택했지만, **변형될 수 있는 위험이 굉장히 높다**고 생각합니다. 이보다 더 나은 방법이 무엇일지, 아니면 위험을 낮출 수 있는 방법이 있을지 궁금합니다.
 - 컴포넌트는 무엇일까요. **컴포넌트는 재활용의 의미가 크다**고 합니다. 하지만 저의 코드로는 그런 의미는 살리지 못한 것 같습니다. 컴포넌트가 재활용으로 의미를 가진다면 어디까지 내용을 비워야 하는 걸까요? 모달창을 키는 컴포넌트다 라고 한다면 모달창의 정보를 인수로 받아 인수 모달창을 키는 컴포넌트로 만든다면 재활용성이 높은 컴포넌트일까요? 근본적으로 유틸함수가 UI를 가진다면 그게 컴포넌트일까요? 컴포넌트는 탬플릿을 꼭 가지고 있어야 할까요? 이런 컴포넌트 중심의 개발은 html를 모두 js에서 랜더링하는 걸까요? 컴포넌트와 도메인을 분리하는 것이 가능할까 다른 크루들에게 물어보았을 때 일단 이번 미션에서는 분리하지 못했다, 그게 가능할까? 하는 의견이 많았습니다. 이벤트 리스너를 부여하는 것이 컴포넌트 파일 안에서 일어난다면 도메인과 분리가 가능한지도 잘 모르겠습니다.
<br>

### 3. 아쉬운 점
- 익숙하지 않은 개념이라 초반에 헤맨 시간이 많습니다. 설계를 하면서 이야기를 많이 나누었고, 이해했다고 생각을 했는데 자꾸 길을 잃어 이야기를 하는 시간이 길었습니다. 때문에 기한 내에 기능구현이 가능할지도 의문이었고, 리팩토링, 유틸함수화, 상수화 등 다른 부분을 신경쓸 겨를이 없었습니다. 잘 짜인 돌아가지 않는 코드보다는 돌아가는 쓰레기가 낫다는 말을 위안삼아 일단 기능구현을 목표로 하였습니다. 이번 미션 목표 중 하나였던 UI의 테스트는 물론 도메인 테스트도 작성하지 못했다는 것이 제일 아쉽습니다. 기능구현을 우선 작성했다보니 테스트코드를 만들고자 했을 때 단위테스트를 하기 굉장히 어려운 코드가 되었습니다... 이 부분은 리팩토링을 하며 테스트코드를 만들도록 하겠습니다.
- 앞서 작성한 것처럼 리팩토링, 유틸함수화, 상수화 등을 하지 못했습니다. 특히 탬플릿을 보면 굳이 이렇게 해야 하나? 싶은 부분이 많은데 해당 부분을 분리하고 싶습니다..
- 생각한 점에서 작성한 것처럼 처음에 레스토랑을 클래스로 만들었습니다. 이 부분이 로컬 스토리지를 사용하는 데에 걸림돌이 되었습니다. 시간이 없어 차선책으로 필요한 부분을 다시 객체로 돌려 사용했습니다만 애당초 이를 객체로 사용하고 관련된 함수를 따로 분리했다면 하는 아쉬움이 있습니다.
 
---
### 전하고 싶은 말
지금까지 한 미션 중 가장 새로운 개념이 많았습니다. 그래서 많이 아쉬운 코드입니다. 
큰 맥락, 설계에 대해 조언주시면 제가 개념을 잡고 설계를 할 때 많이 참고할 수 있을 것 같습니다.
감사합니다! 
<br>

2023-03-04 09:32 UTC, pocojang requested changes
@chsua 👋 
반갑습니다
저는 리뷰어 포코라고 합니다.
잘 부탁드려요!

---

## 피드백

### 템플릿이란..?

사람 대 사람 그리고 모든 집단이 형성하는 언어와 단어들이 존재하는데요.
해온님이 생각하는 템플릿, 개발에서의 템플릿, 그 외에 템플릿 등등..
템플릿이 어떻게 불리우는지 고민해보시면 좋겠어요
일단 제 개인적으로 느낀 것은.. 템플릿 역할만 잘 하고 있는 경우도 있고요. 템플릿이 여기까지 한다고..? 그 이상을 하는 경우도 보입니다.

또한 `App/render()` vs `SomeComponent/template()` 하는 역할도 상당히 비슷해보이는데 무슨 차이가 있을까요?

### 함수 내부 변수

함수 네이밍이 이미 적절한데 불필요하게 내부 변수를 만들고 바로 반환하는 경우가 잦은데 어떻게 생각하시나요?

계속 `result`라는 내부 변수를 만들고 반환하는 습관이 있으신 것 같은데 이미 함수 네이밍만으로 설명이 충분한 경우가 있어요.
개인적인 성향이 있을 수 있지만 한번 고려해보세요 :)

```js
// case1
const list = restaurantList.map((item) => {
  const restaurant = new Restaurant(item);
  return restaurant;
});

// case2
const list = restaurantList.map((item) => {
  return new Restaurant(item);
});

// case3
const list = restaurantList.map((item) => new Restaurant(item));
```

### 디렉터리 구조

아쉬운 것은 재사용성이 너무 떨어지고 계층이 구분되지 않는 정말 플랫한 구조라는 것입니다.
물론 디렉터리 구조만으로 앱의 구조와 계층을 설명할 수는 없겠지만.. 조금 아쉬운 마음은 드네요.

누가봐도 내부 로직은 `import`, `export`를 통해 복잡하게 섞여있고 계층이 나뉘어져있답니다.
다만.. 디렉터리 구조는 플랫한.. 1depth로 되어있죠.

즉 누가봐도 상하관계와 계층적인 구조가 나뉜 컴포넌트들인데 같은 계층처럼 한 디렉터리에 모두 담겨져있답니다

### 컴포넌트 구조

일관성을 정말 잘 지켜주셨습니다.
때로는 클래스, 때로는 리터럴 객체로 구분하여 사용하셨던데 그 이유가 아직 잘 이해되는건 아니지만 그래도 일종의 규격을 만들고 잘 지키고 있어 좋네요

다만 `template()`의 존재, `setEvent()`에 너무나 많은 로직이 있다는 것은 더 고민해보고 수정해보셨으면 좋겠습니다.

### 타입

타입 재활용이 잘되고 있지 못해서 그 부분도 한번 고려해보세요 :)


---

구상 => 생각한 점 => 아쉬운 점을 통해 @chsua 의 고민과 미션을 대하는 마음을 알 수 있어 리뷰하는데 큰 도움이 되었답니다.
아쉬움이 많이 남겠지만 동작하는 쓰레기더라도 정해진 시간에 새로운 지식을 대하며 구현한 코드가 정말 찐 내 코드입니다 :) 애정을 가지고 바라봐주세요!
코드가 주는 가치는 앞으로 만들어나가면 됩니다.
다만 포기하지 않고 계속 수련해야 짧은 시간에 더 많은 가치를 생산하실 수 있을겁니다.

그럼 이만..!
리뷰 반영 후 다시 리뷰요청해주세요!

2023-03-04 09:32 UTC, pocojang commented on src/components/SortButton.ts
> +      const select = sortingFilter.options[sortingFilter.selectedIndex].value;
`sortingFilter.options[무효한 index].value` 일 경우 어떻게 할까요?

2023-03-04 09:32 UTC, pocojang commented on src/components/Restaurant.ts
> +      <img src="${category[this.#restaurant.category]}" alt="${
src="${category[무효한 index]}" 일 경우 어떻게 할까요?

2023-03-04 09:32 UTC, pocojang commented on src/App.ts
> +        </div>
- https://github.com/woowacourse/javascript-lunch/pull/13#discussion_r1125208418

2023-03-04 09:32 UTC, pocojang commented on src/components/RestaurantList.ts
> +const RestaurantList: listInterface = {
클래스인 컴포넌트와 싱글 리터럴 객체인 컴포넌트는 어떤 구분으로 나눠서 선언하시는걸까요?

2023-03-06 11:39 UTC, chsua commented on src/components/FilterButton.ts
> +      const result = RestaurantList.listUp(select, RestaurantList.sortState);
select는 사용자가 선택한 값, result는 선택에 따른 레스토랑 리스트입니다.
해당 부분은 리팩토링 과정에서 수정했습니다!

2023-03-06 11:47 UTC, chsua commented on src/components/LinkInput.ts
> +<input type="text" name="link" id="link">
해당 부분은 미션으로 주어진 html에서 기본값으로 되어 있던 부분입니다.
기능을 구현하는 데에 시간이 없어 따로 변경하지는 않았습니다.
아직 name과 id를 같은 이름을 짓는 것이 어려운데, 이런 경우 **inputLink** 나 **input-link** 정도가 적당할까요?
늘 변수명, 함수명이 고민입니다.

2023-03-08 14:52 UTC, pocojang approved these changes
@chsua

빠른 리뷰 요청 좋네요!

## 피드백

### 구조

의미 있는 고민보다는 실행이라 생각하는데 그래도 이런 저런 분리해보면서 어떤 생각을 가졌고 어떻게 수정했는지 확실히 코드만봐도 그 의도를 알 수 있었어요.

물론 여전히 아쉽고 애매한 부분들이 간간히 존재하기때문에 그 부분은 코멘트 리뷰 확인해주세요!

### 고민점

컴포넌트 A,B 그리고 C 기능에 대한 이야기는 잘봤지만 아직.. @chsua 의 생각도 어지러운건지 질문을 잘 이해하지 못했어요 😢 
다만 지금 고민에 대한 해결 방법을 찾기보다는 더 많은 시도를 해보셨으면 좋겠어요
충분히 잘 하고 계시기때문에 금방 더 성장하실 수 있을 것 같고요.

다시 한번 생각해보실 부분은..! 어떻게 해결하면 좋을까에서 잠깐 벗어나셔서 내가 지금 이걸 왜 고민하고 있지? 내가 이걸 왜 해결해야하지? 이 포인트도 한번 추천드려봅니다 :)

---

이만 머지합니다!
아쉽지만 우리 1단계는 놓아주고 2단계에서 다시 뵙도록해요 👋

2023-03-08 14:52 UTC, pocojang commented on docs/REQUIREMENTS.md
> +인터페이스를 기준으로 유사한 형태의 요소를 하나의 컴포넌트라고 보고 구조를 작성
굿굿 너무 좋아요
다음에는 도식화로 그려보는 연습을 해보세요.
간단히 이면지를 구해서 쓱싹 그려보거나 화이트보드에 그려보셔도 좋습니다!

2023-03-08 14:52 UTC, pocojang commented on src/App.ts
> +    FilterSortButton.FilterSort();
이전보다는 확실히 정갈해졌네요!
근데 조금 아쉬운건 음.. 이벤트를 등록하기보다는 함수를 호출하는 게 아닐까? 묘사되는 네이밍이네요

2023-03-08 14:52 UTC, pocojang commented on src/Template.ts
> +      description &&
그려질지 말지에 대한 판단은 호출하는 측에서 해야하지 않을까요?
물론 텍스트 내용 뿐이지만 그런 관점도 생각해보세요 ㅎㅎ

2023-03-08 14:52 UTC, pocojang commented on templates/style.css
>  /* Colors *****************************************/
불필요한 주석은 제거해봅시다 :)

2023-03-08 14:52 UTC, pocojang commented on src/Template.ts
> +  기타: categoryEtc,
음 오로지 키만 한글로 관리하게 된 계기가 있을까요?

2023-03-08 14:52 UTC, pocojang commented on src/Template.ts
> +  mainHeader(BottomSheetButton: string) {
`Header`가 아닌 `mainHeader`인 이유가 있을까요?

2023-03-08 14:53 UTC, merged