[1단계 - 음식점 목록] 도리(강영민) 미션 제출합니다.
woowacourse/javascript-lunch pull request #45
Opened 2023-03-03 08:54 UTC by tkdrb12

안녕하세요 헤인티!
이번 점심 뭐 먹지 미션 리뷰를 받게 된 크루 도리입니다
잘 부탁드립니다!!

## 배포 페이지
https://tkdrb12.github.io/javascript-lunch/

## 질문
![image](https://user-images.githubusercontent.com/103256030/222671222-fa603917-07f3-4898-8011-a2e1ed197425.png)
1. 이번 미션의 목표는 컴포넌트의 분리이기 때문에 컴포넌트를 다음 사진과 같이 Header, RestaurnantFilter, RestaurnantList, RestaurnantItem, Modal로 분리했습니다.  하지만 다른 사람들의 코드에서 더 세세하게 컴포넌트를 분할한 코드들이 많이 보였습니다. 혹시 컴포넌트를 나눈다면 어느 정도로 잘게 나눠야 할까요? 혹시 현업에서 사용하는 기준이있나요??

2.  이번 미션에서 html파일을 관리할 때 컴포넌트 단위로 나누어 컴포넌트 js파일의 template메서드가 html파일 문자열을 가지고 있는 방식으로 코드를 구현했습니다. 하지만 다음과 같은 방식은 html파일을 유지 보수할 때 불편할 수 있다고 생각하는데 html파일을 더 재사용성 높게 관리할 수 있는 더 나은 방식을 추천해 주실 있을까요?

2023-03-04 18:44 UTC, HyeonaKwon requested changes
안녕하세요 도리! 저도 반나뵙게 되어 반갑습니다 :) 

음 일단 도리의 컴포넌트를 보면서 느낀 점은 독립적이지 않다는 것이었어요! 컴포넌트들이 서로 얽혀있고 관여를 많이 하는 느낌입니다. 자세한건 코멘트를 참고해주세요!

#### 질문 답변
1. 컴포넌트 분리 기준이야 당연히 사람마다 다르고 프로젝트마다 다릅니다! 예를 들어 디자인 시스템이라면 버튼 하나하나, 뱃지 하나하나 다 컴포넌트로 분리하겠지만, 실제 서비스에서는 그렇게까지 분리하기 쉽지 않곘죠? 도리가 생각하는 컴포넌트가 뭔지, 이 서비스에서 컴포넌트 단위로 어떤게 적합한지를 고민해보면 좋을 것 같아요! 틀린건 없습니다! 😃

2. [쿠마 코드 예시](https://github.com/woowacourse/javascript-lunch/pull/44) 보내드립니다!

#### 리뷰
1. 컴포넌트들의 render 에서 이벤트 리스너를 붙이는게 좋지 않아보입니다. 이벤트는 한 번만 추가해야하는데 렌더링할 때마다 동일한 이벤트 리스너를 계속 붙일거라는 의미가 되니까요!

2. 클래스 멤버변수는 상위에 정의해주시면 코드를 이해하는데 더 좋을 것 같아요!

2023-03-04 18:44 UTC, HyeonaKwon commented on src/components/Header.js
> +      <h1 class="gnb__title text-title">점심 뭐 먹지</h1>
보통 웹페이지에서 헤더의 타이틀을 눌렀을 때 어떤 일이 일어나는지 알아보면 좋을 것 같아요!

2023-03-04 18:44 UTC, HyeonaKwon commented on src/components/Header.js
> +    this.setEvent(modal);
렌더링될 때마다 이벤트 리스너를 계속 추가하는게 맞을까요? 이벤트리스너는 처음 한 번만 추가해놔도 될 것 같은데요!

그리고 modal 을 받는게 아니라 onClickAddButtonCallback 을 받는게 좋을 것 같아요! 생성자에서 받으면 어떨까요?
한 컴포넌트가 다른 컴포넌트가 뭐가 있는지를 알 필요는 없습니다. 다른 누군가의 일을 대신 해주는거라면 콜백으로 받는게 좋을 것 같아요!

2023-03-04 18:44 UTC, HyeonaKwon commented on src/components/Header.js
> +  }
왜 element 를 받는지 알 수 있을까요? 생성자 내에서 .gnb 엘리먼트를 찾아도 될 것 같아서요!

2023-03-04 18:44 UTC, HyeonaKwon commented on src/components/Modal.js
> +    this.restaurantsList.restaurants.add(restaurant);
restaurantsList 의 restaurants 인게 뭔가 좀 중복인 것 같아요! list.list 이니까..?
`this.restaurantsList.add()` 가 되어야하지 않나 싶습니다.

2023-03-04 18:44 UTC, HyeonaKwon commented on src/components/Modal.js
> +    this.restaurantsList.setState(restaurant);
97라인이랑 동일한 일 아닌가요..?

2023-03-04 18:44 UTC, HyeonaKwon commented on src/components/RestaurantFilter.js
> +    restaurantList.render();
아래 setEvent 에서 `restaurantList.render()` 코드가 있는데 여기서 또 하는 이유가 있나요?

2023-03-04 18:44 UTC, HyeonaKwon commented on src/components/RestaurantItem.js
> +  }
item 이 list 를 왜 알아야할까요? list 가 item 을 알아야하지 않을까요?

2023-03-04 18:44 UTC, HyeonaKwon commented on src/components/RestaurantsList.js
> +    this.state = restaurants.restaurants;
중복으로 레스토랑 리스트를 저장하는 이유가 있나요?

2023-03-04 18:44 UTC, HyeonaKwon commented on src/components/RestaurantsList.js
> +    restaurantItem.render($rastaurantList);
list 가 반복문을 돌려 item 을 set 해야지 item 이 list 를 받아가서 전체 리스트를 돌려주는건 아닌 것 같아요!

2023-03-04 18:44 UTC, HyeonaKwon commented on src/constants/constants.ts
> +};
타입스크립트 적용해볼까요?

2023-03-04 18:44 UTC, HyeonaKwon commented on src/domain/Restaurants.ts
> +  }
```suggestion
  add({description = '', link = '', ...rest}: Restaurant): void {
    this.#restaurants.push({ ...rest, description, link });
  }
```

2023-03-04 18:44 UTC, HyeonaKwon commented on src/domain/Restaurants.ts
> +  }
rest 는 임시 네이밍이고 원하시는 네이밍 사용하시면 됩니다!

2023-03-04 18:44 UTC, HyeonaKwon commented on src/domain/Restaurants.ts
> +  }
```suggestion
  filterByCategory(category: string): Restaurant[] {
    if (category === VALUE.catgory.all) return this.restaurants;

    return this.restaurants.filter(restaurant => restaurant.category === category);
  }
```

2023-03-04 18:44 UTC, HyeonaKwon commented on src/domain/Restaurants.ts
> +  }
```suggestion
  sortByType(sortType: string): Restaurant[] {
    ...
```

2023-03-04 18:44 UTC, HyeonaKwon commented on src/components/RestaurantFilter.js
> +  setEvent(restaurantList) {
요것도 리스트 객체를 받는게 아닌 콜백으로 받아주세요!

2023-03-06 08:34 UTC, tkdrb12 commented on src/components/Header.js
> +      <h1 class="gnb__title text-title">점심 뭐 먹지</h1>
헤더 타이틀을 클릭 했을 때  새로고침 되도록 기능을 추가해봤습니다. UX적으로도 고려를 많이 해야겠군요!

2023-03-06 08:34 UTC, tkdrb12 commented on src/components/Header.js
> +    this.setEvent(modal);
```
// Header.js

  render() {
    ...
  }

  setEvent(renderModal) {
    ...
  }

// index.js

header.setEvent(modal.render.bind(modal));
```

다음과 같이 변경해서 이벤트 리스너와 렌더링 기능을 분리했습니다!

2023-03-06 08:34 UTC, tkdrb12 commented on src/components/Header.js
> +  }
각 컴포넌트를 선언하는 index.js에서 코드를 읽을 때 컴포넌트의 위치를 명시적으로 드러내기 위해서 다음과 같이 element를 받도록 작성했습니다. 하지만 다시 생각해보니 굳이 이렇게 생성자에서 받을 필요가 없네요 ㅜㅠ
`this.$target = document.querySelector('header');`와 같이 수정했습니다.

2023-03-06 08:34 UTC, tkdrb12 commented on src/components/Modal.js
> +    this.restaurantsList.restaurants.add(restaurant);
setSubmitEvent(renderRestaurantList) {
    const $modalForm = document.querySelector('.modal form');

    $modalForm.addEventListener('submit', e => {
      e.preventDefault();

      const restaurant = this.getmodalFormValue();

      this.restaurants.add(restaurant); //수정
      localStorage.setItem('restaurants', JSON.stringify(this.restaurants.restaurants));
      renderRestaurantList();

      this.toggleModal();
    });
  }

 컴포넌트 객체 내부 list를 가져오기 위해서 restaurantsList.restauran와 같이 작성했는데 의미가 구체적으로 드러나지 않네요...  restaurantsList 컴포넌트 객체가 아닌 콜백함수를 받아오도록 코드를 수정하면서 다음과 같이 변경했습니다!

2023-03-06 08:34 UTC, tkdrb12 commented on src/components/RestaurantFilter.js
> +    restaurantList.render();
렌더링 함수에서 리스너 함수를 실행하면서 코드가 불필요한 부분을 실행시키는 부분이 많아졌었네요
렌더링함수와 이벤트 리스너 함수를 분리하면서 렌더링 함수는 컴포넌트를 화면에 띄워주는 역할만 하도록 변경했습니다!
```
  render() {
    if (!document.querySelector('.restaurant-filter-containe')) {
      this.$target.insertAdjacentHTML('afterbegin', this.template());
    }
  }
```

2023-03-06 08:34 UTC, tkdrb12 commented on src/components/RestaurantItem.js
> +  }
RestaurantItem에서 복수의 레스토랑 정보를 받아 한번에 레스토랑 아이템을 생성하려고 해서 코드가 이상하게 작성이 됐네요  

```
    restaurants.forEach(restaurant => {
      const restaurantItem = new RestaurantItem(restaurant);
      this.restaurantItems.push(restaurantItem);
    });
```

와 같이 restaurantList의 메서드를 수정해 RestaurantItem은 하나의 레스토랑 정보만 가지도록 변경했습니다.

2023-03-06 08:35 UTC, tkdrb12 commented on src/components/RestaurantsList.js
> +    this.state = restaurants.restaurants;
굳이 필요없는 구문이네요 `this.state = restaurants.restaurants;`코드는 제거했습니다!

2023-03-06 08:35 UTC, tkdrb12 commented on src/components/RestaurantsList.js
> +    restaurantItem.render($rastaurantList);
```
    restaurants.forEach(restaurant => {
      const restaurantItem = new RestaurantItem(restaurant);
      this.restaurantItems.push(restaurantItem);
    });
```

다음과 같이 List에서 반복문으로 item을 생성하도록 했습니다!

2023-03-06 08:35 UTC, tkdrb12 commented on src/constants/constants.ts
> +};
```
export interface CategoryFilter {
  value: '전체' | '한식' | '중식' | '일식' | '아시안' | '양식' | '기타';
}

export interface SortTypeFilter {
  value: 'name' | 'distance';
}

```

상수 파일은 다른 파일에서 참조하고 있어서 interface로 정의할 경우 오류가 발생해서 수정하지 않고 다음과 같이 필터 값을 타입스크립트로 따로 정의해봤어요!

2023-03-06 08:35 UTC, tkdrb12 commented on src/domain/Restaurants.ts
> +  }
디폴트 파라미터를 이렇게도 활용할 수 있군요! 감탄했습니다!!!!🤩

2023-03-06 08:35 UTC, tkdrb12 commented on src/domain/Restaurants.ts
> +  }
다음과 같은 코드를 추천해주신 이유가 혹시 함수가 객체 메서드가 아니라도 사용할 수 있는 순수 함수로 작성되었기 때문인가요? 
```
  getRestaurant(category, sortType) {
    return this.sortByType(sortType, this.filterByCategory(category, this.#restaurants));
  }
```

제가 위와 같이 코드를 작성한 이유는 복수 레스토랑 정보를 받아올 때 필터링과 정렬을 모두 하고 난 뒤 정보를 가져오기 위해서 다음과 같이 코드를 작성했었습니다. this키워드로 객체 내부의 배열을 가져오면 필터링과 정렬을 모두 하기가 까다롭더라고요ㅜㅠ
```
 static filterByCategory(category: string, restaurants: Restaurant[]) { }
```
그래서 리뷰어 님이 코드 수정을 추천해주신 이유가 객체의 메서드 내부에서만 사용하는데 굳이 순수 함수처럼 사용할 이유가 없다라고 추측해 다음과 같이 static키워드를 붙여 객체 외부에서도 사용할 수 있게 수정해봤습니다

2023-03-06 08:35 UTC, tkdrb12 commented on src/domain/Restaurants.ts
> +  }
위와 같이 static키워드를 붙여 수정했습니다!

2023-03-06 08:35 UTC, tkdrb12 commented on src/components/RestaurantFilter.js
> +  setEvent(restaurantList) {
콜백으로 받도록 수정완료했습니다! 😀

2023-03-06 16:04 UTC, HyeonaKwon commented on src/components/Header.js
> +    this.setEvent(modal);
외부에서 함수를 호출해주는 것도 좋지만! 컴포넌트 내부의 라이프 사이클을 더 활용해볼 수 있으면 좋겠습니다! Header 에서 처음 딱 한번만 호출되는 라이프사이클 함수는 무엇일까요?

2023-03-06 16:07 UTC, HyeonaKwon commented on src/components/Header.js
> +  }
ㅋㅋㅋㅋㅋ 도리! 제 말을 무조건적으로 받아들이지 않아도 되어요! 예전 다른 크루는 제가 이런 질문 드리면 `컴포넌트 재사용성 관점에서 element id 가 다른 컴포넌트가 여러개를 생성할 때에도 재사용 가능하도록 구현하고 싶었습니다!` 라고 말하는 크루도 있었습니다 ㅎㅎ  

다양한 질문들 속에서 도리의 기준을 잡아보는 시간을 가져봅시다!

2023-03-06 16:14 UTC, HyeonaKwon commented on src/domain/Restaurants.ts
> +  }
음 그런건 아니구 this.filterByCategory() 호출할 때에도 this.#restaurants 를 넘기는데 굳이 왜 파라미터로 넘기는지 이해가 되지 않았어요!
`복수 레스토랑 정보를 받아올 때 필터링과 정렬을 모두 하고 난 뒤 정보를 가져오기 위해서 다음과 같이 코드를 작성했었습니다. this키워드로 객체 내부의 배열을 가져오면 필터링과 정렬을 모두 하기가 까다롭더라고요ㅜㅠ` 이게 무슨 말인지 이해가 잘 안되네요ㅠ!

2023-03-06 16:15 UTC, HyeonaKwon commented on src/domain/Restaurants.ts
> +  }
아 혹시 sortByType 이 filterByCategory() 된 배열을 넘기기 위해서 파라미터로 넘겼다는 말씀이실까요?!

2023-03-06 16:40 UTC, HyeonaKwon approved these changes
도리 안녕하세요! 금방 피드백을 반영하고 오셨군요! 👍 주말에 고생 많으셨습니다.
코멘트들에 다시 리뷰를 남겼는데요! 1단계는 여기에서 머지하지만 코멘트에 남긴 내용들 반영해서 2단계에 알려주셨으면 좋겠습니다. 제가 남긴 피드백 링크를 반영하신 코드에 코멘트로 남겨주세요!  

컴포넌트를 구현할 때에는 `생명주기`를 사용하는게 굉장히 중요해요~ 컴포넌트의 어떤 생명주기에 수행해야하는 로직인지를 판단하는게 FE 개발자로서 당연히 가져야할 능력이니까요!
웹 컴포넌트의 생명주기는 어떻게 되는지, 어떤 일들이 어떤 생명주기에 일어나야 하는지 등등을 공부해보시면 좋겠습니다! 공부해보시고 정리해서 알려주세요~!

1단계는 여기서 마무리하겠습니다. 짧은 기간에 구현하시느라, 학습하시느라 고생 많으십니당 :)

2023-03-06 16:40 UTC, HyeonaKwon commented on src/components/RestaurantFilter.js
> +    if (!document.querySelector('.restaurant-filter-containe')) {
그리고 여기서 느껴야하는건! 똑같은 값(restaurant-filter-container)을 여러 번 사용하는데 이렇게 오타(휴먼 에러)가 발생한다는건 상수화가 중요하다는 것입니다!

2023-03-06 16:40 UTC, HyeonaKwon commented on src/components/RestaurantFilter.js
> +  setEvent(renderRestaurantsList) {
콜백을 받는 이유는 이 함수를 사용하는 쪽에서 어떤 일을 할지 알고 싶지 않아서예요!
사용처 쪽에서 생각해서 함수명을 짓는게 아니라 RestaurantFilter 입장에서 함수명을 지어야겠죠?
filter select 의 option 이 바뀔 때 수행할 함수이니 onChangeFilterOption() 라던지 changeFilterOptionCallback() 등등 사용처에서나 생각해볼만한 `레스토랑 리스트를 렌더링하자!` 의 의미를 담지는 않았으면 좋겠습니다!  

요렇게 해야 다양한 곳에서 재사용할 수 있는 컴포넌트가 되겠죠? 다른 곳에서 RestaurantFilter 를 사용할 때는 옵션 값이 바뀔 때마다 레스토랑 리스트를 렌더링하지 않을 수도 있으니까요!

2023-03-06 16:40 UTC, HyeonaKwon commented on src/components/Header.js
> +  }
👍 지금은 페이지가 하나라서 리로드로 가능하겠지만, 페이지가 여러개되는 서비스에서는 메인홈 (루트페이지, /) 로 리다이렉트 처리하기도 한답니다!

2023-03-06 16:40 UTC, HyeonaKwon commented on src/constants/constants.ts
> +};
제가 말씀드린건 이걸 interface 나 type 으로 변경하는게 아니라, key-value 값이 무엇인지를 타입 정의를 해달라는 말이었습니다!

```suggestion
export const VALUE = {
  catgory: {
    all: '전체',
  },

  sortType: {
    nameOrder: 'name',
  },
};

export const CATEGORY_TO_FILENAME: Readonly<Record<CategoryValue , string>> = {
  한식: 'category-korean',
  중식: 'category-chinese',
  일식: 'category-japanese',
  양식: 'category-western',
  아시안: 'category-asian',
  기타: 'category-etc',
};
```

VALUE 는 어떻게 타입 정의를 해야하는지 모르겠네요..! 타입 정의를 못하겠다면 객체가 의미있는 단위로 묶인게 맞을까요?! 그리고 네이밍도 의미있게 지어주세요! 서로 다른 관심사를 모아놓으니 변수명을 짓기 힘들어 VALUE 로 지은게 아닐까 추측해봅니당 🧐

2023-03-07 04:46 UTC, tkdrb12 commented on src/components/Header.js
> +    this.setEvent(modal);
생성자에서 콜백함수를 받아와서 이벤트 리스너 함수를 호출해주도록 하는 걸 말씀하시는 건가요??

```
const header = new Header(modal.render);
const modal= new Modal(header.render);
```
와 같이 객체가 서로의 메서드를 생성자로 받는 경우가 있어서 이런 방식으로 구현했어요!!

---

추가해서 설명드리면 다른 객체의 메서드를 콜백 함수로 받을 때는
```
header.setEvent(modal.render.bind(modal));
```
와 같이 index.js파일에서 따로 호출하는 방식으로 코드를 짰으며

콜백함수를 인자로 받지 않는 경우에만 
```
  constructor() {
    this.render();
    this.setHeaderClickEvent();
  }
```
다음 코드와 같이 생성자에서 리스너 함수를 호출하는 방식으로 구현했습니다

2023-03-07 04:47 UTC, tkdrb12 commented on src/components/Header.js
> +  }
꼭 리뷰어님이 리뷰해주신 내용을 코드에 반영하지 않아도 되는군요! 앞으로는 제 자아를 찾도록 해보겠습니다ㅜㅠ

2023-03-07 04:50 UTC, tkdrb12 commented on src/domain/Restaurants.ts
> +  }
네 맞아요!! sortByType()에서 인자로 filterByCategory()에서 필터링 된 배열을 받기 위해서 다음과 같이 코드를 짰습니다!

2023-03-07 05:47 UTC, tkdrb12 commented on src/components/RestaurantFilter.js
> +    if (!document.querySelector('.restaurant-filter-containe')) {
restaurantFilter 컴포넌트가 재렌더링 될 시 
restaurant-filter-containe 클래스 값을 가진 엘리먼트가 이미 document내에 존재할 경우 다시 한번  엘리먼트를 추가하지 않기 위해서 `if (!document.querySelector('.restaurant-filter-container'))` 조건식을 추가로 사용했었어요!

하지만 1단계에서는 restaurantFilter 컴포넌트 렌더링은 단 한번만 되기 때문에 오타가 있어도 코드가 정상적으로 작동하고 있었네요 분명 제대로 돌아가는 지 확인하고 PR했는데 오타가 있길래 엄청 당황했습니다😥 

 --- 

여러번 사용되는 class이나 id 값은 상수로 따로 정의하는 게 좋겠네요

2023-03-08 02:14 UTC, merged