[2단계 - 음식점 목록] 애슐리(허서영) 미션 제출합니다.
woowacourse/javascript-lunch pull request #55
Opened 2023-03-10 05:43 UTC by ashleysyheo

안녕하세요 카일! 
벌써 금요일이네요!! 내일 즐거운 주말 보내시길 바라요 😄

이번 2단계 미션 배포 페이지 입니다:  **[링크](https://ashleysyheo.github.io/javascript-lunch/)**

---

### 폴더 구조

📦src
 ┣ 📂components
 ┃ ┣ 📜Header.ts
 ┃ ┣ 📜Input.ts
 ┃ ┣ 📜Modal.ts
 ┃ ┣ 📜RestaurantAddForm.ts
 ┃ ┣ 📜RestaurantFilters.ts
 ┃ ┣ 📜RestaurantInformation.ts
 ┃ ┣ 📜RestaurantItem.ts
 ┃ ┣ 📜RestaurantListContainer.ts
 ┃ ┣ 📜RestaurantTabMenu.ts
 ┃ ┣ 📜Select.ts
 ┃ ┗ 📜TabButton.ts
 ┣ 📂constants
 ┃ ┣ 📜constants.ts
 ┃ ┣ 📜data.ts
 ┃ ┣ 📜domAttributes.ts
 ┃ ┗ 📜images.ts
 ┣ 📂domains
 ┃ ┣ 📜RestaurantService.ts
 ┃ ┗ 📜utils.ts
 ┣ 📂types
 ┃ ┗ 📜types.d.ts
 ┣ 📂utils
 ┃ ┣ 📜domSelectors.ts
 ┃ ┗ 📜localStorage.ts
 ┣ 📂validators
 ┃ ┗ 📜restaurantFormValidator.ts
 ┣ 📜App.ts
 ┗ 📜index.js

---
생각보다 기능 요구사항이 복잡했었는데, 일단 돌아는 가도록 만들었습니다...! 
step2 기능 요구사항 구현이랑, cypress e2e 테스트도 진행해 보았습니다. 

이번 step2에서 코드를 좀 갈아엎었습니다... step1에서 한 파일에서 너무 많은 것들을 동시에 하고 있어서, 코드를 읽는 게 좀 힘들기도 했고, 현 구조에서 2단계 기능 요구 사항을 구현하는 것이 더 복잡할 것 같았습니다. 그래서 카일이 제의해 주신 것처럼 컴포넌트를 나눠보려고 했습니다. 재사용 가능한 부분들은 재사용하고, 컴포넌트의 관심사만 해당하는 코드를 응집해 보려고 했습니다. 확실히 관련 코드들이 한 군데 같이 있으니까 이해하고 파악하는 게 더 수월해졌습니다. 그런데 컴포넌트를 잘 나누고 관련 코드 응집을 제대로(?) 했는지 아직은 잘 모르겠습니다. 

그리고 e2e 테스트 코드도 처음 작성해 보는데, 어느 정도까지 작성을 하는 게 좋은가요?

이번 리뷰도 잘 부탁드립니다! 그리고 좋은 리뷰들 감사드립니다!

2023-03-10 12:18 UTC, GwangYeol-Im requested changes
안녕하세요 애슐리~ 2단계 미션도 고생많으셨습니다. 이번 미션은 1단계와 달리 좀 더 적극적으로 컴포넌트를 만들고 코드를 응집시키려는 시도는 좋았다고 생각합니다. 👍 다만 아키텍처와 관심사에 대한 고민보다 '컴포넌트라고 생각하는' 템플릿을 미리 만들어놓고 그 일관성을 맞추는 것에 집중하다보니, 전체적인 앱의 흐름은 부자연스러워 보이고 오히려 1단계 때 작성해주신 코드보다 유지보수가 쉽지 않겠다는 판단이 들었습니다. 🥲 그렇게 생각한 이유로는,

- 컴포넌트 안에서 렌더링과 이벤트 바인딩을 모두 외부로 위임하다보니, 내부에서 들고 있지 않아도 되는 상태를 갖게 되고 `App`의 구조가 앱이 확장함에 따라 비대해지기 쉬운 구조로 바뀐 것 같습니다.
- `RestaurantInformation`처럼 html에 있어도 되는 요소를 관심사 분리 없이 모두 js로 끌고 오니 성능과 유지보수성을 모두 놓치게 되는 선택은 아니었을지? 싶은 고민이 들었습니다.

그럼에도 MVC를 고집하지 않고 새로운 시도를 해본 점은 아주 좋았습니다. 지금 당장 모든 걸 수정하려고 하기보다는 코멘트에 대해 좀 더 고민해보신 뒤 핑퐁 이어나가면 괜찮지 않을까 싶네요 :) 리팩터링 사이즈가 너무 크다고 판단되신다면, 생각하시는 방향을 코드로 작성하여 코멘트에 올려주셔도 좋습니다.

> e2e 테스트 코드도 처음 작성해 보는데, 어느 정도까지 작성을 하는 게 좋은가요?

질문이 포괄적이라는 것은 아직 해당 개념에 대해 거의 알지 못하기 때문이 아닐까 싶네요! e2e 테스트 관련 공식문서나 구글링을 통해 아티클을 통해 여러 use case나 example을 먼저 읽어보시는 게 더 도움 되실 것 같습니다.

2023-03-11 12:44 UTC, ashleysyheo commented on src/validators/restaurantFormValidator.ts
> +  verify(restaurantItem: Omit<Restaurant, 'favorite' | 'id'>) {
이런 게 있는지 몰랐습니다. 알려주셔서 감사합니다!

수정 커밋: https://github.com/woowacourse/javascript-lunch/pull/55/commits/eda2417d0e82180d917b5c071b718a023b4e5999

2023-03-11 12:47 UTC, ashleysyheo commented on src/types/types.d.ts
> +import RestaurantAddForm from '../components/RestaurantAddForm';
타입들이 늘어나면서 서서히 정리가 안된다는 생각이 들기 시작했었는데, 좋은 팁 감사합니다!

* 공용 타입
* 도메인 타입
* UI 타입
* Modal 타입

이렇게 나눠봤습니다.

수정 커밋: https://github.com/woowacourse/javascript-lunch/pull/55/commits/07b9d915e23b87416c7660c5ccfcf35efe5e1525

2023-03-11 13:26 UTC, ashleysyheo commented on src/domains/utils.ts
> +function filter(category: CategoryOptions, restaurantList: Restaurant[]) {
정렬 함수들이랑 이름을 맞춰주려고 `filterByCategory`로 이름 변경해 봤습니다.

수정 커밋: https://github.com/woowacourse/javascript-lunch/pull/55/commits/1796fd58e749ed10a6bb25dabda33d4c13857e07

'전체', '이름순'이랑 다른 변동 가능성 있는 하드코딩된 값들도 상수화했습니다! 그리고 음식점 정렬/필터링 관련 상수들은 파일 분리해 봤습니다.

수정 커밋: https://github.com/woowacourse/javascript-lunch/pull/55/commits/00ebc918e875dbb71fe50ab2d65b672f684e3310, https://github.com/woowacourse/javascript-lunch/pull/55/commits/6b8338d40a169a273ffb608e29770f39077839e7

2023-03-11 13:29 UTC, ashleysyheo commented on src/domains/RestaurantService.ts
> +    return this.restaurantList.find((restaurant) => restaurant.id === restaurantId) as Restaurant;
오! 이런 게 있는지 몰랐습니다. 알려주셔서 감사합니다. 
타입 단언이랑 nullish 단언 중에서 어떤 게 더 좋다(?), 안전한가요? 

수정 커밋: https://github.com/woowacourse/javascript-lunch/pull/55/commits/d3fa1242ad4e92f903aad8f8846992b08d537234

2023-03-11 13:32 UTC, ashleysyheo commented on src/domains/RestaurantService.ts
> +    this.restaurantList.splice(restaurantIndex, 1);
`filter`를 생각하지 못했네요! 필터를 사용하니까 더 간단해지네요

수정커밋: https://github.com/woowacourse/javascript-lunch/pull/55/commits/34f86608a1e7c1d2021817d3237e5bcdd929ebf2

2023-03-11 13:33 UTC, ashleysyheo commented on src/domains/RestaurantService.ts
> +    this.restaurantList[restaurantIndex].favorite = !this.restaurantList[restaurantIndex].favorite;
`map`도 아예 생각하지 못했습니다. 다음부터는 좀 더 효율적으로 고차 함수를 사용할 수 있는지에 대해 고민을 해봐야겠네요..

수정커밋: https://github.com/woowacourse/javascript-lunch/pull/55/commits/beed9d4731d3b6d8c95b40b385e632b7986213b4

2023-03-11 13:36 UTC, ashleysyheo commented on src/components/RestaurantItem.ts
> +  private restaurant: Restaurant;
`RestaurantItem`은 템플릿 생성만 해서 따로 `template` 폴더를 생성해서 거기에 `createRestaurantItem`이라는 함수로 변경했습니다. 

수정커밋: https://github.com/woowacourse/javascript-lunch/pull/55/commits/e3118bfc3ac93a99b3883db3a8da84d1106a0b9f

2023-03-11 14:01 UTC, ashleysyheo commented on src/App.ts
> +  addEvents() {
> 이벤트 호출 순서가 중요한 경우라면 휴먼 에러에 노출되기 쉬운 구조로 보입니다.

이 부분에 대해서 생각해 보지는 못했지만, 말씀하신 것과 같은 상황이라면 각 컴포넌트에서 호출하는 게 더 좋을 듯싶네요. 그래서 컴포넌트에서 렌더링을 하면, `render`함수 안에서 이벤트를 호출하도록 변경했습니다. 렌더링하지 않는 경우에는 그대로 App의 `addEvents`에서 호출하고 있습니다.

그런데 질문이 있습니다!
지금 예를 들어서 음식점 추가 폼 모달을 렌더링 하는 방법은 `Modal`에 `RestaurantForm` 인스턴스를 넘겨준 후 `Modal`에서 모달 컨테이너와 안의 내용을 렌더링하고 있습니다. 그럼 이벤트 호출을 모달의 `render`에서 하면 필요한 콜백 함수를 `render`가 받은 후 `this.content.addEvents`에 넘겨주고, 그다음에는 또 `RestaurantForm.addEvents`가 복수의 이벤트 리스너 등록 함수들에게 그 콜백을 넘겨주고 있습니다. 뭔가 썩 바람직한 방법은 아닌 거 같은데, 다르게 할 방법을 생각 못 하겠습니다... 이럴 때는 어떻게 하는 게 좋나요?

2023-03-11 14:05 UTC, ashleysyheo commented on src/components/TabButton.ts
> +      const tabButtons = document.querySelectorAll('.tab-button');
음식점 목록 변경 탭을 라디오 버튼을 사용하도록 수정하면서, `TabButton`은 함수로 변경 후 `template` 폴더로 이동시켰습니다. 그리고 탭 변경 이벤트는 `RestaurantTabMenu`으로 옮기고 이벤트 위임을 하도록 했습니다. 

수정커밋: https://github.com/woowacourse/javascript-lunch/pull/55/commits/a75b3aa7335e56aef870723288844eb8dd402e21, https://github.com/woowacourse/javascript-lunch/pull/55/commits/e3c0a99b8f336c0d04999a407cc67a92d2c53ae2

2023-03-11 14:18 UTC, ashleysyheo commented on src/utils/domSelectors.ts
>  }
`E | null`을 하면 `$`를 사용한 모든 곳에서 셀렉팅한 요소가 `null`일 수 있다고 하는 에러가 떠서, `if (!element) return`과 같은 식으로 처리할까 하다가, 함수 내부에서 요소 존재 여부를 검사하는 방식으로 변경해 봤습니다.

```javascript
function $<E extends Element>(selector: string): E {
  const element = document.querySelector(selector);

  if (!element) {
    throw new Error(`DOM에 ${selector} 요소가 존재하지 않습니다.`);
  }

  return <E>element;
}
```
이렇게 해도 괜찮은가요?

2023-03-11 14:57 UTC, ashleysyheo commented
정말 이번 미션 하면서 멘붕이 너무 많이 온 것 같아요…ㅎㅎ 다 갑자기 생소하고, 이렇게 하는 게 맞는 건지도 모르겠는데, 일단 기능이 돌아가게는 만들어야겠고… 그래도 카일이 주신 피드백들 덕분에 이리저리 시행착오하면서 그 과정 속에서 많은 깨달음과 배움을 얻고 있습니다!

카일이 말씀하신 것처럼 step2 하면서 템플릿을 만들어 두고 거기에 맞춰서 코딩하려고 한 것 같기도 합니다. 클래스를 굳이 사용하지 않아도 되지 않을까라는 생각이 중간에 하면서도 들기는 했지만, 그냥 계속했습니다… 😅

이번에 리팩토링 하면서, 기존의 `RestaurantItem`이나 `TabButton`과 같이 그냥 템플릿 생성만 필요한 요소들은 `template` 폴더를 새로 생성해서 거기에 템플릿을 만들어주는 함수를 생성했습니다. 

그리고 굳이 js에서 생성할 필요 없는 html은 `index.html`에 다시 뒀습니다. 그래서 `Header`의 html 코드는 `index.html`에 위치하게 되어서, `components`에서 파일을 없애고, 헤더 버튼 누르는 이벤트는 `events` 폴더의`headerEvents.ts`로 옮겼습니다. 

컴포넌트들 사이에서 중복되는 메서드 (i.e. `changeRestaurantFavoriteIcon`)는 `components/utils`로 옮긴 후 그 함수를 사용하도록 변경했습니다. 

기존에 `App`에 있던 `updateRestaurantList`는 음식점 목록을 다시 렌더링 하는 역할을 하기 때문에 음식점 목록이랑 더 가까운 기능이라고 생각해서 `RestaurantListContainer`로 옮겼습니다.

그리고 제가 RestaurantInformation을 js에서 음식점 아이템을 클릭할 때마다 리렌더링하도록 한 이유는 솔직히 템플릿에 정보를 넣어서 insert하는 게 더 편해서 그랬습니다..! 그리고 `Modal`에 정보를 주입(?) 후 그걸 `main`에 insert하기 위함도 있었습니다. 그런데 RestaurantItem같은 경우에는 정보가 계속 변경되어야 하지 않나요? 제가 제대로 이해한 것인지는 모르겠는데, html에 있어도 된다는 것은 음식점 상세 정보가 `index.html`에 있고 안에 정보를 `textContent`로 변경한다는 것인가요?

마지막으로 대망의 `App`은… 저도 정말 이걸 어떻게 해야 할지 잘 모르겠습니다… 이 컴포너트가 다른 컴포넌트랑 연계해서 일을 해야 하고, 또 도메인이랑도 소통해야 하고 해서 그냥 일단 다 `App`에 넣었었습니다. `App`은 많이 건드리지는 못했지만 그래도 한 번 더 살짝 갈아엎으면서 리팩토링해봤습니다!

남은 주말도 즐거운 시간 보내세요! 그리고 리뷰 감사합니다.

2023-03-11 15:42 UTC, GwangYeol-Im commented on src/utils/domSelectors.ts
>  }
넵 적절한 처리라고 생각합니다 :)

2023-03-11 15:53 UTC, GwangYeol-Im commented on src/domains/RestaurantService.ts
> +    return this.restaurantList.find((restaurant) => restaurant.id === restaurantId) as Restaurant;
두 문법의 목적은 컴파일러에서 제공하는 추론의 한계를 보완하고자 적용하는 것이기에 안정성 추구와는 다소 거리가 멉니다.
다만 `as`는 타입 캐스팅, `!`는 non-null assertion이라고 불리기에 의미 상 후자가 더 적절해보여 제안 드렸습니다.

2023-03-11 16:27 UTC, GwangYeol-Im commented on src/App.ts
> +  addEvents() {
form과 modal을 핸들링하는 로직은 이것을 모두 알고 있는 상위 계층에서 수행해주는 것이 적절해보입니다.
아래의 예제는 직접 테스트해보진 않고 코드만 읽은 뒤 작성한 로직이라 보완이 필요할 수 있으나 현재처럼 Form에서 Modal의 관심사까지 알고 있는 강한 결합은 피할 수 있을 것 같습니다.

```ts
// App.ts

modal = new Modal({
  content: new RestaurantForm(this.onSubmit),
})

onSubmit() {
  // logic...
  this.modal.close()
}
```

2023-03-11 16:59 UTC, GwangYeol-Im approved these changes
리뷰 반영하시느라 고생 많으셨습니다 애슐리 :) 좀 더 코멘트 필요한 부분은 남겨두었으니 확인 부탁드리고 이번 미션은 이만 머지하도록 할게요!

> `RestaurantInformation` 관련 코멘트

이 컴포넌트의 코드와 시안을 대조해보니 제가 잘못 파악하고 있었군요..🥲 현재 배포페이지에서 상세 정보 ui가 노출되고 있지 않아 확인을 못한 듯 합니다 ㅠㅠ 애슐리가 작성해주신 구조가 적당하다고 생각하나, modal과 form을 분리하신 것처럼 bottom sheet ui와 내부 콘텐츠를 분리했으면 더 좋았을 것 같습니다!

> App 관련 코멘트

다른 컴포넌트와 마찬가지로 `App`도 하나의 컴포넌트라는 관점으로 봐주시면 좋을 것 같습니다. 이번 미션을 진행하시면서 '도메인, 컴포넌트, document 사이를 핸들링하는 동작은 `App`에서만 수행해야한다'고 생각해서 그런건 아니었을까, 조심스레 추측해 봅니다 ㅎㅎ.. `App` 하위에서도 경우에 따라 여러 레이어를 핸들링하는 컴포넌트와 그저 데이터만 받아서 ui만 그려주는 컴포넌트로 나누는 연습을 해보시면, 관심사에 맞게 로직이 가깝게 모이면서 정말 `App`에 있어야 하는 로직들은 줄어들 수 있지 않을까 생각합니다

2023-03-11 16:59 UTC, merged