[2단계 - 음식점 목록] 노아(김홍동) 미션 제출합니다.
woowacourse/javascript-lunch pull request #63
Opened 2023-03-10 10:06 UTC by nlom0218

유조! 안녕하세요 🙇🏻‍♂️
2단계 미션으로 찾아왔습니다:) 기존 1단계에서 많은 구조가 변하였는데요. 이에 대해 아래에서 설명드리도록 하겠습니다:)

먼저 데모 사이트 입니다.
[점심 뭐 먹지 바로가기](https://nlom0218.github.io/javascript-lunch/)

🚨 restaurant 클래스에 새로운 필드가 추가되었습니다! 로컬스토리지를 한 번 비워주세요:)

---

## 2단계 TODO LIST

### 리팩터링 목록

- [x] refactor: 쉐도우 돔 제거
- [x] refactor: RegisterRestaurantModal 추가
- [x] refactor: SearchRestaurantSection 추가
- [x] refactor: 검색창 윈도우 로드 후 삽입하기
- [x] refactor: 음식점 목록 윈도우 로드 후 삽입하기
- [x] refactor: Header 웹 컴포넌트 추가 및 윈도우 로드 후 삽입하기
- [x] refactor: 음식점 모달 창 렌더링 함수 분리
- [x] refactor: 음식점 목록 리렌더링 함수 분리
- [x] refactor: 초기 화면 랜더링 함수 분리
- [x] refactor: 로컬스토리지 관련 함수 분리
- [x] refactor: css 분리
- [x] refactor: 상수화
- [x] refactor: querySelector 실패 시 에러처리
- [x] refactor: 음식점 즐겨찾기 추가, 제거 로직 정리

### 기능 목록

- [x] feat: 음식점 상세 정보 확인
  - 카테고리, 이름, 거리, 설명, 참고 링크 확인
- [x] feat: 음식점 삭제
- [x] feat: 자주 가는 음식점 추가
  - 음식점 목록, 음식점 상세 정보에서 추가
- [x] feat: 음식점 목록에서 자주 가는 음식점 확인
- [x] feat: 모든 음식점, 자주 가는 음식점 탭에서 생성
- [x] feat: 자주 가는 음식점 탭에서 자주 가는 음식점 목록 확인
- [x] feat: 자주 가는 음식점에서 모든 음식점으로 돌아갈 때 필터링 초기화
- [x] feat: 음식점 중복 이름 유효성 검사 기능

### 기능 수정 목록

- [x] fix: 자주 가는 음식점에서 즐겨찾기를 취소하면 목록 업데이트가 안 되는 부분 수정
- [x] fix: 모바일 환경에서 모달 스크롤 오류 현상 해결

### 테스트 목록

- [x] test: 컴포넌트 단위 테스트
  - 초기 화면 렌더링 테스트
  - 음식점 목록 렌더링 테스트
  - 즐겨찾기 추가, 제거 테스트
  - 음식점 세부정보 모달 창 렌더링 테스트
  - 음식점 등록 모달 창 렌더링 테스트
- [x] test: E2E 테스트
  - 새로운 음식점 등록하기
  - 음식점의 세부정보 모달창 띄우기
  - 음식점 삭제하기
  - 자주 가는 음식점 등록하기
  - 자주 가는 음식점 목록 보이기
  - 카테고리 선택하기

### 2단계 커스튬 기능 목록

- [x] feat: 성공, 실패 메시지 띄우기

---

## 1️⃣ 컴포넌트의 역할

미션을 진행하면서 컴포넌트의 역할에 대해 많은 고민을 하였습니다. 고민하는 과정에서 `컴포넌의 역할`이 무엇인지 정리하였습니다.  예를 들어 모달창인 경우 기본적으로 아래와 같은 역할을 가지고 있어야 합니다.

<모달창의 기본 역할>

1. 배경이 어두워진다.
2. 모달창이 등장한다.
3. 배경을 클릭하면 모달창이 사라진다.
4. aciton이 `closeModal`인 버튼을 클릭하면 모달창이 사라진다.

이중 1,2번은 UI에 관련한 것이고 3,4번은 모달창이 기본적으로 가져야 할 역할입니다. 이러한 역할을 `Modal` 컴포넌트에 구현을 하였습니다.

또 `FavoriteIcon(즐겨찾기 버튼)`을 예시로 들자면 즐겨찾기 버튼의 기본 역할은 아래와 같습니다.

<즐겨찾기 버튼 기본 역할>

1. 별 아이콘을 가지고 있다.
2. 클릭 할 수 있다.
3. 즐겨찾기 버튼을 클릭하면 자주 가는 음식점에 등록된다.
4. 단, 이미 자주 가는 음식점에 등록되었다면 자주 가는 음식점에서 제거된다.

위와 같은 기본 역할을 가지고 있습니다. 

언제든지 재사용할 수 있는 컴포넌트인 `Modal`, `FavoriteIcon`를 사용하여 `RestaurantDetailModal` 컴포넌트를 만들었고 해당 컴포넌트가 화면에 랜더링이 되면 `Modal`과 `FavoirteIcon`의 역할(기능)을 사용할 수 있습니다. 뿐만 아니라 `RestaurantDetailModal` 컴포넌트의 기본 역할인 음식점의 세부 정보도 확인할 수 있습니다.

이렇게 각 컴포넌트들이 가질 수 있는 기본적인 역할을 생각하였고, 컴포넌트에 기본 역할이 있다면 역할을 부여했습니다.

---

## 2️⃣ CustomEvent 사용

이번 미션에서는 `CustomEvent`를 많이 사용했습니다. 컴포넌트에서 이벤트가 실행되고 해당 이벤트를 통해 음식점이 생성되거나 자주 가는 음식점에 등록될 수 있습니다. 또한 모달창을 열고 닫을 수도 있습니다. 

위의 과정을 `CustomEvent`사용없이 바로 컴포넌트에서 진행할 수 있습니다. 하지만 자기 자신에 대한 이벤트(UI 한정)를 제외하고는 모두 `CustomEvent`를 사용하여 `App.ts`에서 해당 이벤트를 받을 수 있도록 하였습니다. 특히! 컴포넌트에서는 도메인에 관한 로직을 작성하지 않도록 주의했습니다.

두가지 예시를 통해 `CustomEvent`를 사용한 이유에 대해 조금더 자세히 설명해 드리겠습니다! 아래에선 불필요한 코드는 삭제했습니다.

1. 모달창 닫기

```javascript
class Modal extends CustomElement {
  close = () => {
    if (!this.parentElement) return errorHandler.doesNotExistElement();

    this.parentElement.remove();
  };

  initEventHandlers = () => {
    const $modalBackdrop = this.querySelector<HTMLDivElement>('.modal-backdrop');
    const $closeModalButton = this.querySelector<HTMLButtonElement>('button[action="closeModal"]');

    if (!$modalBackdrop) return errorHandler.doesNotExistElement();
    if (!$closeModalButton) return errorHandler.doesNotExistElement();

    $modalBackdrop.addEventListener('click', this.close);
    $closeModalButton.addEventListener('click', this.close);
  };
}
```

모달창 밖의 배경과 action 어트리뷰트의 값이 `closeModal`인  버튼을 클릭하면 `close` 함수가 실행됩니다. 이는 자기 자신을 포함한 부모 노드(모달창)를 닫는 이벤트이므로 다른 컴포넌트를 랜더링을 하지 않아도 됩니다. 때문에 이와 같은 경우엔 `CustomEvent`를 사용하지 않았습니다.

2. 자주 가는 음식점 등록

```javascript
class FavoriteIcon extends CustomElement {
  clickFavoriteIcon = () => {
    if (this.isFavorite) {
      this.removeAttribute('favorite');
    } else {
      this.setAttribute('favorite', '');
    }

    this.dispatchEvent(
      new CustomEvent('toggleFavorite', {
        bubbles: true,
        detail: {
          restaurantName: this.restaurantName,
        },
      }),
    );
  };

  initEventHandlers = () => {
    const $favoriteIcon = this.querySelector('.favorite-restaurant-icon');

    if (!$favoriteIcon) return errorHandler.doesNotExistElement();

    $favoriteIcon.addEventListener('click', this.clickFavoriteIcon);
  };
}
```

즐겨 찾기 아이콘을 클릭하게 되면 `clickFavoriteIcon` 함수가 실행됩니다. 여기서 어트리뷰트를 추가, 제거하는 것은 자신의 UI를 변경하는 작업이므로 컴포넌트에서 실행하였습니다. 하지만 `toggleFavoirte`이라는 `CustomEvent`를 발생시켜 `App.ts`에 보냈습니다.

이를 받은 `App.ts`에서는 음식점의 상태를 업데이트를 하게 됩니다. 

또한 모달창 안에서 즐겨 찾기 버튼을 누른 경우, 모달창 밖(바탕)에 있는 음식점 목록에서도 즐겨 찾기가 바뀐 것을 반영할 수 있도록 코드를 작성하였습니다. App.ts의 `toggleRestaurantFavorite` 메서드에서 확인할 수 있습니다!

---

## 3️⃣ render 함수의 분리

이전에는 html에 기본 구조가 있었고, App.ts에서도 화면 렌더링에 필요한 로직이 있었습니다. 하지만 이를 모두 `render` 폴더 내에서 관리를 할 수 있도록 구조를 바꾸었습니다. 

이렇게 구조를 바꾼 이유는 아래와 같습니다.

1. 여러번 반복되고 여러 곳에서 사용되는 렌더링이 있을 수 있다.
   - 예를 들면, 이벤트에 대한 성공 실패 여부를 보여주는 것은 한 곳이 아니라 여러 곳에서 사용될 수 있습니다.
   - 이런 경우 같은 코드를 함수로 만들어 분리해두면 편하다고 생각했습니다. ->  `render.message`
2. App.ts는 화면에서 발생시키는 이벤트에 따라 데이터를 관리한다.
  - 바뀐 데이터에 따른 화면 렌더링은 다른 곳에서 하는 것이 역할 분리라고 생각했습니다.
  - App.ts -> 데이터 관리
  - render.ts -> 데이터에 따른 화면/렌더링 관리

아래와 같은 코드를 통해 2번 이유에 대해 설명을 더 드리도록 하겠습니다.

```javascript
// App.ts
  toggleRestaurantFavorite = ({ detail }: CustomEvent) => {
    const { restaurantName } = detail;

    this.#restaurants.forEach((restaurant) => {
      if (restaurant.getName() === restaurantName) restaurant.toggleFavorite();
    });

    const targetRestaurant = this.#restaurants.filter(
      (restaurant) => restaurant.getName() === restaurantName,
    )[0];

    render.toggleRestaurantFavorite(this.#restaurantListType, targetRestaurant);

    saveRestaurants(this.#restaurants);
  };
```

위 함수는 `toggleFavorite` 이벤트가 발생했을 때 실행되는 함수입니다. `toggleFavorite` 이벤트를 통해 음식점의 이름을 알아내고 해당 음식점의 즐겨 찾기 여부만 바꾸는 역할을 하고 있습니다. 바뀐 결과에 따른 화면 렌더링과 로컬스토리지에 바뀐 음식점 목록을 저장하는 것은 모두 다른 함수에서 진행합니다. 

이렇게 `render `을 통해서만 화면이 랜더링이 되도록 하였습니다.

---

## 4️⃣ querySelector가 실패할 때

이전에 유조가 피드백 해주신 내용인 `querySelector가 실패하면 어떻게 인지할 수 있나요?`에 대해서도 고민해봤습니다. 즉, 이벤트를 발생시키기 위해 element를 찾아야 하는데 이을 못 찾을 경우, 아무런 행동이 없기 때문에 사용자, 개발자 모두에게 단점으로 다가갈 수 있습니다.

이를 해결하기 위해 `errorHandler`를 만들고 element을 찾지 못했을 때, 실행되게 하였습니다. 에러를 반환하기 때문에 콘솔에서 쉽게 어디에서 에러가 발생했는지 확인할 수 있었습니다. 이 덕분에 잘 돌아가고 있었다고 생각한 코드에서 오류를 발견하였고 수정할 수 있었습니다. 

에러난 부분의 코드에 별도로 댓글을 남겼습니다. 😁 아래 커밋을 참고해주세요!

[querySelector의 실패](https://github.com/woowacourse/javascript-lunch/commit/97aaff27b5f32c45ec6a790685336423c976ef7d#diff-236e6401a93b24d3b3ca86328d4c5e8a2b233718f8800f44ef4eddc6553688f0)

---

## 📂 코드 구조도

아래는 [Mermaid](https://mermaid.live/)를 사용하여 만든 코드 구조도 입니다. 제가 봐도 너무 복잡해보입니다ㅠㅠ 올리지 말까 고민을 하였는데, 참고가 될 수 있을 것 같아 올립니다 😢

```mermaid
---
title: 점심 뭐 먹지
---
classDiagram
    CustomElement <|-- CustomFormElement
    CustomFormElement <|-- Button
    CustomElement <|-- FavoriteIcon
    CustomFormElement <|-- FormItem
    CustomFormElement <|-- Input
    CustomElement <|-- Modal
    CustomElement <|-- RestaurantItem
    CustomFormElement <|-- Select
    CustomFormElement <|-- Textarea
    CustomElement <|-- Header
    CustomElement <|-- Message
    CustomElement <|-- RegisterRestaurantModal
    CustomElement <|-- RestaurantDetailModal
    CustomElement <|-- RestaurantList
    CustomElement <|-- RestaurantTypeSection
    CustomElement <|-- SearchRestaurantSection
    RegisterRestaurantModal .. Modal
    RegisterRestaurantModal .. FormItem
    RegisterRestaurantModal .. Select
    RegisterRestaurantModal .. Input
    RegisterRestaurantModal .. Textarea
    RegisterRestaurantModal .. Button
    RestaurantDetailModal .. Modal
    RestaurantDetailModal .. FavoriteIcon
    RestaurantDetailModal .. Button
    RestaurantList .. RestaurantItem
    SearchRestaurantSection .. Select
    render <-- CustomElement
    App <--> render
    App <--> Restaurant
    App <-- Restaurants
    class CustomElement{
        +attributeChangedCallback()
        +renderTemplate()
        +render()
        +connectedCallback()
    }
    class CustomFormElement{
        #internals
        +formAssociated
 [...]

2023-03-11 05:15 UTC, yujo11 requested changes
안녕하세요 노아!

코드가 전체적으로 깔끔하게 작성되어 있어서 코멘트 남길 부분이 많지 않았네요 👍 👍 👍 

그리고 노아가 만든 애플리케이션을 실행해보고 깜짝 놀랐어요!

유저와의 상호작용이 발생할 때 필요한 부분만 다시 render하고 있더라구요.

이렇게 코드를 작성하는게 쉽지 않은 부분이었을텐데 노아가 만든 앱을 보면서 정말 감탄했답니다! 👍 👍 👍  💯 💯 💯 

PR본문을 통해 로직을 설명하고 구조도를 첨부해주신 부분도 정말 좋았어요 덕분에 노아의 코드를 보고 이해하기도 한결 편했네요!!

크게 추가로 남길 코멘트는 없고 소소한 코멘트들 남겼으니 확인해보셨으면 좋겠네요! 

고생 많으셨어요 노아~~ 👍 👍 👍 

---

아 그리고 구조도 관련해서 질문 주셨는데요.

저는 손으로 많이 그려봤던거 같아요 ㅎㅎ... 😅

2023-03-12 13:26 UTC, nlom0218 commented on src/app.ts
> +        Object.setPrototypeOf(restaurant, Restaurant.prototype),
Restaurant 클래스의 메서드를 연결하기 위함입니다!

이름, 카테고리 등 음식점의 정보를 가져오기 위해 메서드를 사용해야 하는데, 로컬스토리지를 한 번 거치고 나니 메서드에 접근을 할 수 없었습니다. 때문에 `Restaurant` 클래스의 프로토타입을 로컬스토리지에 저장된 각각의 음식점의 프로토타입에 추가하였습니다.

물론 아래와 같이 바로 음식점의 이름에 접근을 할 수 있습니다. 

<img width="729" alt="스크린샷 2023-03-12 오후 10 16 31" src="https://user-images.githubusercontent.com/57981252/224547321-66ebbedb-c0bc-499a-9497-cb1adce9edf5.png">

하지만 이는 어찌보면, 클래스에 의해 만들어진 인스턴스(객체)의 상태에 바로 접근하는 것이기 때문에 좋은 방법이 아니라고 생각했습니다. 객체의 어떤 값을 가져오기 위해선 메시지(메서드)를 보내는 것이 좋다고 생각하기에 끊겨진 프로토타입을 연결하는 방법을 사용했습니다.

만약 위와 같은 기능을 이후에 다시 다루게 된다면 그땐, 클래스가 아니라 타입만 정해두려고 합니다. 만약 이렇게 된다면 굳이 값에 접근하기 위해 메서드를 사용하는 것이 아니라 바로 `.name` 과 같은 방법을 써도 괜찮지 않을까 생각합니다:)

2023-03-12 13:38 UTC, nlom0218 commented on src/app.ts
> +    if (restaurants.length !== 0) {
네! 말씀해주신 방법이 더 깔끔해보입니다.

제가 아직까지 숫자가 0일 때 불리언 값이 false라는 것이 확 와닿지 않아서 지금까지 `!== 0` 처럼 명시하면서 사용했습니다. 앞으론 `숫자 0이 불리언으론 false이다.` 라는 특징을 잘 활용하도록 연습을 해봐야겠어요! 감사합니다 😁

그리고, 저는 `!`를 하나 더 붙였어요! 그래야 `restauransts` 가 0이 아닐 때를 `true`로 정할 수 있었습니다!

2023-03-12 13:41 UTC, nlom0218 commented on src/components/message/Message.ts
> +class Message extends CustomElement {
감사합니다! 컴포넌트를 필요할 때 불러와서 사용하는 것을 연습하고 이와 함께 특별한 기능을 추가하고 싶었어요ㅎㅎ 성공, 오류 메시지가 좋아 보여서 시도했습니다 😆

2023-03-12 14:16 UTC, nlom0218 commented on src/components/shared/Input.ts
> +    return `<input>`;
`RegisterRestaurantModal` 컴포넌트 내에서 사용합니다!

2023-03-12 14:24 UTC, nlom0218 commented on src/domain/Validation.ts
> +    if (category === '') throw new Error(ERROR_MESSAGE.restaurantCategory);
```javascript
if (!category.length) throw new Error(ERROR_MESSAGE.restaurantCategory);
```

위와 같이 리팩터링을 했습니다. 의도한 바가 맞을까요? 혹은 아래 처럼 생각도 해보았습니다.

```javascript
if(category.length) return 
throw new Error(ERROR_MESSAGE.restaurantCategory);
```

2023-03-12 14:27 UTC, nlom0218 commented on src/app.ts
> +    )[0];
감사합니다! 적절한 메서드 사용에 대해 앞으로 더 고민하고 적용해보겠습니다! 😀

2023-03-12 14:42 UTC, nlom0218 commented
안녕하세요! 유조! 🙇🏻‍♂️

즐거운 주말 보내셨나요? 어제 리뷰를 확인을 하였지만 개인 일정이 있어 오늘 리팩터링을 마무리했습니다. 남겨주신 댓글에 댓글 남겼습니다. 참고부탁드려요:)

### 코드 리뷰 후 리팩터링 목록

- [x] refactor: 불리언 값 활용
- [x] refactor: Array.prototype.find() 메서드 활용을 활용하여 음식점 찾기
  - 음식점을 찾지 못한 경우 에러를 반환
- [x] refactor: 상수화 추가하기

---

살펴보시고 부족한 부분 코멘트 부탁드립니다 😀 감사합니다!

2023-03-12 14:51 UTC, yujo11 commented on src/domain/Validation.ts
> +    if (category === '') throw new Error(ERROR_MESSAGE.restaurantCategory);
위에 적어주신 방법을 생각하고 남긴 리뷰였습니다! 

덧붙이자면 빈 문자열은 falsy한 값이기 때문에 아래와 같이 작성하는걸 생각했어요!

```ts
if (!category) throw new Error(ERROR_MESSAGE.restaurantCategory);
```

이 문서를 참고해봐도 좋을거 같네요! https://developer.mozilla.org/en-US/docs/Glossary/Falsy

2023-03-12 15:49 UTC, yujo11 approved these changes
안녕하세요 노아~

미션 진행하느라고 고생 많으셨습니다~~

코드 레벨에서 몇 가지 개선했으면 하는 부분들이 있어 간단하게 코멘트를 남겼는데요!

핑퐁을 한번 더 해도 좋을거 같다는 생각이 들었지만 오늘 18시가 마지막 리뷰 요청 시간이라 여기서 이만 merge를 하려고 합니다!

추가로 남긴 코멘트들은 다음 미션을 진행하실 때 참고해서 진행해보시면 좋을거 같아요~ 

이전 코멘트에 댓글로 남겨주신 내용에도 코멘트 남겼으니 같이 확인 부탁드릴게요!

미션 진행하느라고 고생 많으셨습니다! 이제 하나 남은 레벨 1 마지막 미션도 화이팅입니다~~~ 👍 👍 👍

2023-03-12 15:49 UTC, yujo11 commented on src/app.ts
>    };
이렇게 작성하는 방법도 있을거 같네요
```ts
createRestaurant = (params: RestaurantProps) => {
  return new Restaurant({
    ...params,
    existRestaurantsName: this.#restaurants.map((restaurant) => restaurant.getName()),
  });
};
```

2023-03-12 15:49 UTC, yujo11 commented on src/app.ts
> +    });
`restaurantName`과 같은 이름의 restaurant를 찾아서 변경해주는거라면 `forEach()`보다는 `find()`를 사용하는 게 더 자연스러울거 같아요
```suggestion
    this.#restaurants
        .find((restaurant) => (restaurant.getName() === restaurantName))
        .toggleFavorite()
    });
```

2023-03-12 15:49 UTC, yujo11 commented on src/app.ts
> +  };
`forEach`구문과 `targetRestaurant`를 찾는 구문에서 로직에 중복이 보이는데요.

순서를 바꿔 아래처럼 작성해보시는 것도 좋을거 같네요!

```suggestion
toggleRestaurantFavorite = ({ detail }: CustomEvent) => {
  const { restaurantName } = detail;

  const targetRestaurant = this.#restaurants.find(
    (restaurant) => restaurant.getName() === restaurantName,
  );

  if (!targetRestaurant) return errorHandler.doseNotExistRestaurant();

  targetRestaurant.toggleFavorite();

  render.toggleRestaurantFavorite(this.#restaurantListType, targetRestaurant);

  saveRestaurants(this.#restaurants);
};
```

2023-03-12 15:49 UTC, yujo11 commented on src/domain/Restaurant.ts
> +    this.validateName(name, existRestaurantsName);
다른 validate과 다르게 valdateName을 수행하기 위해서 새로운 식당이 추가 될 때마다 외부에서 생성된 `existRestaurantsName`을 매번 생성해서 인자로 전달받고 있는데요.

이러한 로직은 Restaurant 외부에서 진행되어도 좋을거 같아요.

데이터 유효성을 보장하기 위한 검사이지만 데이터 유효성 검사가 복잡해지면서 filed가 추가되고, 외부에서도 매번 인자로 같이 넘겨주면서 전체 코드의 복잡도가 증가한거 같은 느낌을 받았어요.

또한 로직을 타고가다 보면 결국 `validateRestaurantNameDuplication`에서 검증을 수행하게 되는데요. `validateRestaurantNameDuplication`에서는 `existRestaurantsName`이 존재하지 않을 경우 그냥 return을 하고 있습니다. `existRestaurantsName` filed가 optional로 되어있어 사용하는 쪽에서 `existRestaurantsName`를 빼먹는다면 쉽게 중복되는 이름이 생길거 같아요.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/61097373/224555473-e0c65638-91d7-4d4d-8316-875d3718b4e5.png">

---

++)
개인적으로는 이러한 validation의 복잡성이 증가하는 문제와 더불어 Data Class나 Model에 가까운 class를 작성할 때는 class 외부에서 validation을 진행하고 이러한 Class가 똑똑해지지 않도록(?) 만드는걸 선호하는데요.

이 부분까지는 취향과 선택의 영역이라고 생각하기 때문에 그냥 저 사람은 그렇게 생각하는구나 정도로만 받아들여 주시면 됩니다!

2023-03-12 15:49 UTC, yujo11 commented on src/utils/constants.ts
> +  restaurantNameLength: `음식점 이름은 ${RESTAURANT_NAME_LENGTH.min} ~ ${RESTAURANT_NAME_LENGTH.max}자 사이어야 합니다.`,
👍👍👍

2023-03-12 15:49 UTC, merged

2023-03-13 01:53 UTC, nlom0218 commented on src/app.ts
>    };
훨씬 깔끔하네요! 감사합니다:)

2023-03-13 01:55 UTC, nlom0218 commented on src/app.ts
> +  };
`Array.find()` 메서드를 앞으로 많이 사용해봐야겠습니다ㅎㅎ 👍👍👍

2023-03-13 01:58 UTC, nlom0218 commented on src/domain/Restaurant.ts
> +    this.validateName(name, existRestaurantsName);
좋은 의견 감사합니다. 저도 이번 미션 뿐 아니라 항상 고민하고 있는 것이, `어디에서 유효성을 검사해야 하는가?` 입니다. 인스턴스가 생성될 때 하는 것이 좋은지 아니면 인스턴스가 생성되기 전 값을 받아올 때 하는 것이 좋은지가 고민이더라고요ㅠㅠ! 앞서 말씀해주신 `existRestaurantsName` 인자가 필수값이 아니기 때문에 이에 대한 대비책에 대해 고민해보도록 하겠습니다. 감사합니다!🙇🏻‍♂️

2023-03-13 03:59 UTC, nlom0218 commented on src/domain/Validation.ts
> +    if (category === '') throw new Error(ERROR_MESSAGE.restaurantCategory);
오.. 빈 문자열도 불리언으로 `false` 이네요! 감사합니다:)