[2단계 - 음식점 목록] 파인(임낭경) 미션 제출합니다.
woowacourse/javascript-lunch pull request #67
Opened 2023-03-10 14:22 UTC by nangkyeonglim

안녕하세요 체프!
step2 리뷰도 잘 부탁드립니다!

### [배포 페이지](https://nangkyeonglim.github.io/javascript-lunch/)

## 실행 방법

`npm run start`

## E2E 테스트 실행

`npm run start`
`npm run test-e2e`

## 점심 뭐먹지 미션

이번 Step2에서는 아래 사항들을 구현하였습니다. 
개인적으로 이번 미션은 굉장히 다양한 플로우로 테스트해봤는데 그 때마다 UX를 고려하고 어떤 식으로 보여주는 것이 좋을 지 고민을 많이 했었던 것 같습니다.

1. 음식점 즐겨찾기 추가 및 삭제
2. 각 음식점 상세정보 모달 구현
3. 음식점 삭제 
4. E2E 테스트

### 컴포넌트 설계

<img width="486" alt="image" src="https://user-images.githubusercontent.com/57815133/224334578-5a982af9-a800-4f61-8257-a9d404fc3d4c.png">

이번에는 RestaurantTab을 컴포넌트로 구현해보았습니다. 
그리고 음식점 상세 정보 모달에서 기존의 음식점 등록 모달을 재사용하기 위해 CustomModal로 분리해서 재사용해보았습니다.

## 궁금한 점

### Q1. 

현재 list를 렌더링 해줄 때마다 각 listItem의 이벤트리스너를 다시 붙여줍니다. filter나 sorting, tab전환 등 리스트 전체를 렌더링 하는 일이 많은데 개선해 볼 점이 있을까요?

2023-03-12 12:20 UTC, Puterism approved these changes

2023-03-12 12:20 UTC, Puterism commented on src/components/restaurant/RestaurantListItem.js
> +      e.stopPropagation();
stopPropagation은 남용하면 안되는 메소드라고 알려져 있는데요. 그 이유는 무엇일까요?

2023-03-12 12:20 UTC, Puterism commented on src/domain/restaurants.ts
> +    this.list.splice(deleteRestaurantIndex, 1);
deleteRestaurantIndex가 -1일 경우에 `this.list.splice`가 정상적으로 동작하나요?

2023-03-12 12:20 UTC, Puterism requested changes
파인 안녕하세요 :) 체프입니다.
꽤 오랫동안 코드를 들여다 봤는데 떠오르는 주요한 피드백은 없었어요. 깔끔하게 구현하신 것 같습니다.
질문해주신 내용에 대한 답변만 확인해주시면 좋을 것 같습니다.
2단계 미션까지 수행하시느라 수고 많으셨습니다. 👏

> 현재 list를 렌더링 해줄 때마다 각 listItem의 이벤트리스너를 다시 붙여줍니다. filter나 sorting, tab전환 등 리스트 전체를 렌더링 하는 일이 많은데 개선해 볼 점이 있을까요?

이 질문에 대해서는 힌트만 드려볼게요. 이벤트 버블링을 이용해보세요. 하나의 이벤트 리스너로도 처리하실 수 있을 거예요.

2023-03-13 04:55 UTC, nangkyeonglim commented on docs/REQUIREMENTS.md
> +- [ ] 새로고침해도 추가한 정보들이 유지되어야 한다.
업데이트 완료 하였습니다!

2023-03-13 05:05 UTC, nangkyeonglim commented on src/domain/restaurants.ts
> +    this.list.splice(deleteRestaurantIndex, 1);
해당 음식점을 찾지 못하면 -1이 반환되어 list의 가장 마지막 원소가 지워지겠군요! 음식점을 찾지 못한 경우에는 삭제 로직을 수행하지 않도록 수정하였습니다!

2023-03-13 05:21 UTC, nangkyeonglim commented on cypress/e2e/spec.cy.ts
> +});
우선 Jest를 이용해서 테스트를 작성했을 때는 컴포넌트가 정상적으로 렌더가 됐는지 여부를 검사했기 때문에 테스트가 그냥 통과하더라도 제대로 앱이 작동하는 지 여부를 검사할 수 없었습니다. Cypress를 사용해서 전체적인 E2E 테스트를 진행했을 때에는 사용자의 입장에서 다양한 플로우로 테스트 해 보면서 확실히 전체적인 앱 작동 여부를 테스트 해볼 수 있었고 시각적으로 보여서 좋았던 것 같습니다.

2023-03-13 06:04 UTC, nangkyeonglim commented on src/components/restaurant/RestaurantListItem.js
> +      e.stopPropagation();
stopPropagation이 버블링을 막아서 상위에 같은 이벤트가 존재할 때 stopPropagation을 사용한 영역은 죽은 영역이 되기 때문에 추후에 예상치 못한 동작을 할 수도 있다고 생각합니다.
예를 들어서 사람들이 페이지에서 어디를 클릭했는지 분석하기 위해 document에 click 이벤트에 리스너를 달았다면 해당 즐겨찾기 버튼 영역은 버블링이 막아져 상위에서는 죽은 영역이 되기 때문에 click 이벤트가 감지되지 않아 예상치 못한 동작을 할 수 있다는 점에서 남용을 하면 안된다고 생각합니다.

2023-03-13 06:26 UTC, nangkyeonglim commented
안녕하세요 체프😁
질문에 대한 답을 하면서 머리속으로 한번 더 정리해보는 시간을 갖게 되었던 것 같습니다.
버블링을 이용해서 하나의 이벤트 리스너로 처리하는 방법도 머리속에 떠오르긴 하네요! 다음에 구현할 때는 그렇게 진행해보려고 합니다 :) 
긴 미션 기간동안 리뷰해주셔서 고생 많으셨습니다! 감사합니다 😌

2023-03-14 10:54 UTC, merged