[2단계 - 자주 가는 음식점] 패트릭(박근철) 미션 제출합니다.
woowacourse/javascript-lunch pull request #73
Opened 2023-03-11 08:35 UTC by GC-Park

안녕하세요 그루밍 패트릭입니다 ! 
2단계 미션이 생각보다 오래 걸려서 벌써 주말이네요 .. 🥲
요구 사항에 맞게 기능 구현을 하였고 구현 과정에서 저조차도 보기 힘들었던 코드들을 리팩토릭 하였습니다 !
또한 UI테스트를 조금 추가하였고 e2e테스트도 경험할 수 있었습니다.

## 궁금한 점
- 즐겨찾기 기능을 구현하면서 ModalRestaurantDetail 파일과 RestaurantRegistry 파일 이 두 곳에 중복되는 메서드들이 생기게 되었습니다. 즐겨찾기 버튼을 누르면 빨간색 별과 빈 별로 토글되는 기능과 LocalStorage의 restaurant과 favorite 이 두곳에 저장하는 기능입니다. 하는 역할이 똑같아 메서드들이 모두 같은데 각자의 파일에서 다른 파일의 메서드를 불러 호출하려 하니 'not a function' 이라는 에러가 뜨면서 사용할 수 없었습니다. 그래서 아예 파일을 따로 만들어야 하나 고민하고 있고 만들어야 한다면 어느 곳에 만들지 궁금합니다 ! 구르밍이라면 어떻게 하시겠나요 ?!
<img width="541" alt="스크린샷 2023-03-11 오후 5 34 45" src="https://user-images.githubusercontent.com/72205402/224474222-9475f278-c45f-4816-8cbf-5638e6c0da77.png">
<img width="544" alt="스크린샷 2023-03-11 오후 5 34 58" src="https://user-images.githubusercontent.com/72205402/224474230-2c283cb1-e981-40ba-9213-4bd1402b2c21.png">

## 홈페이지 링크
https://gc-park.github.io/javascript-lunch/dist/

2023-03-13 08:41 UTC, GC-Park commented
그루밍 ! 

오늘 6시까지가 리뷰 요청 마감이라 위의 부족했던 부분들 먼저 개선 후 push하고 리뷰 요청 보냅니다 !!

그루밍이 리뷰 주시면 따로 공부 후 적용시켜 보겠습니다 !! 감사합니다 ㅎㅎ

2023-03-13 16:17 UTC, ddongule requested changes
안녕하세요 패트릭! 그루밍입니다! 🐝
컴포넌트를 만드는 방법에 대해 다양한 고민을 해보셨네요~!
기능 단위로 컴포넌트를 만들었을 때 어떤 장점과 단점이 있었는지, 단점들을 어떻게 개선해야할지에 대해서 중점적으로 고민해보시고, 직접 구현해보시면서 기준을 잡아나가시면 좋을 것 같아요! 👍
지금은 아직 각 컴포넌트와 함수들이 서로 간에 의존성이 높아 분리가 다소 필요해보여요. 

코드에서 아직 lint/prettier가 제대로 적용되지 않은 부분들이 곳곳에 보여요. 요부분도 신경써서 확인해주시면 협업이나 리뷰를 받을 때 더 좋을 것 같아요. 한번 확인해주세용! ㅎㅅㅎ

그리고 즐겨찾기를 하고나서 필터링 하는 부분에 바로 반영이 되지 않는 문제가 있네요! 한번 살펴주시면 좋을 것 같아용 영상 올려둘게요! 

https://user-images.githubusercontent.com/26598561/224754766-5060fd87-cb61-499f-bc6f-1aebaa939139.mov

전체적으로 localstorage에 필요 이상으로 많이 접근하시는 것 같아요. localstorage를 사용함에 있어서 장단점이 어떤 것들이 있는지 공부해보셔도 좋을 것 같습니다. 🫙

그리구 Typescript를 조금씩 더 사용해보셔도 좋을 것 같아요! 처음이라 잘 안되더라도 족굼씩 족굼씩 도으전~ 해보시는거 어떠신가욧! ㅎㅅㅎ 점점 익숙해지실거에요 

### QnA
#### 1. 
같은 역할을 하는 함수가 여러 곳에 있다면 분리하는 것이 좋을 것 같아요. 다만 함수 내에서 반복해서 사용되는 부분들이 어떤 내용이느냐에 따라 그 위치는 상이할 것으로 보입니다. 한번 직접 분리해보시구 다시 리뷰요청 주셔도 좋을 것 같아요 🤓 

#### 2. 
저는 E2E 테스트를 할 때에는 UI 레이아웃 등이 제대로 동작하지 않으면 해당 프로젝트와 사용자가 제대로 상호작용을 하지 못할 수 있으니 렌더링까지 테스트하는 것이 좋을 것 같아요. 하지만 그때 그때 프로젝트의 목표와 성격에 따라 조금씩 달라질 수는 있겠죠! 딱히 디자인이 중요하지 않는 등의 프로젝트에서는 굳이 렌더링 테스트까지 작게 나누어서 테스트하기보다는 기능이나 동작에 조금 더 초점을 맞추어 테스트하는 것이 더 좋아보여용. ㅎㅎ

리팩토링하느라 수고 많으셨어요~! 
코멘트 확인해보시면서 궁금한점 있으시면 언제든 알려주셔용!!
고생 많으셨습니닷!

2023-03-13 16:17 UTC, ddongule commented on src/UI/RestaurantInventory.js
> +  }
위에 코멘트 드린 것처럼, class를 add/remove 하도록 변경하면 이런 스타일링 코드는 조금 줄어들 수 있을 것 같아요ㅎㅎ

2023-03-15 00:06 UTC, GC-Park commented on cypress/support/e2e.ts
> +// require('./commands')
이런 파일이 있었네요 !   삭제하도록 하겠습니다 !!!

2023-03-15 00:42 UTC, GC-Park commented on src/App.js
> +          2
로컬에 레스토랑을 추가할 때 다음 id 값을 설정해주는 코드였습니다 ! 

중간에 삭제한 후 삭제된 id값도 다시 할당하게 만들려다 보니 복잡하게 되었는데 

마지막 id보다 1만 크도록 수정하여 조금 더 가독성 있게 바꾸었습니다 !

2023-03-15 00:43 UTC, GC-Park commented on src/App.js
> +    if (getRestaurantListFromLocalstorage(RESTAURANT_LOCALSTORAGE_KEY))
오 너무 좋은 것 같습니다 !!  적용해보도록 하겠습니다 감사합니다 ㅎㅎ

2023-03-16 00:25 UTC, GC-Park commented on src/App.js
>    }
성능 저하까지 생각해서 코드를 작성했어야 했는데 기능 완성에 집중한 나머지 고려하지 못했었네요 🥲 밖으로 빼는게 나은 것 같고 idNumber부분인 46-47 줄은 두 번째 리뷰에서 수정한 것 덕분에 사실상 불필요한 코드가 되어 삭제하였습니다 !

if문 조건문의 조건을 함수를 따로 만들어 표현해주었습니다 !! 사실 코드를 작성할 때 오히려 저렇게 두면 명시된다고 생각했는데 함수 이름으로 표현하는게 더 직관적일 것 같습니다 ! 감사합니다 ㅎㅎ

2023-03-16 00:32 UTC, GC-Park commented on src/UI/ModalRestaurantDetail.js
> +    $(".button--delete").addEventListener("click", () => this.deleteButtonInDetail());
his.deleteButtonInDetail 함수에 매개변수가 있었다가 리팩토링 하면서 매개변수가 빠진 것 같습니다 ! 

수정해줬어야 하는데 알려주셔서 감사합니다 !!

2023-03-16 22:20 UTC, GC-Park commented on src/UI/ModalRestaurantDetail.js
> +    }
css를 js에서 어떻게 효율적으로 사용할 수 있을지 고민이었는데 클래스를 활용해 할 수 있다니 좋은 것 같습니다 !! 

적용해 보도록 하겠습니다 !

2023-03-16 22:33 UTC, GC-Park commented on src/UI/RestaurantInventory.js
> +  }
확실히 코드가 줄고 css를 묶어서 관리할 수 있어서 좋은 것 같습니다 ㅎㅎ 좋은 방법을 익혔습니다 감사합니다 !!

2023-03-17 00:24 UTC, GC-Park commented on src/utils/Constant.js
> +export const FAVORITE_UNENROLL = "./favorite-icon-lined.png"
비슷한 도메인으로 가진 값들을 묶는 방법을 알고 있었는데 바쁘게 구현하다보니 생각하지 못했네요 🥹

저도 묶는 방법이 좋을 것 같습니다 수정하겠습니다 ㅎㅎ !

2023-03-17 00:24 UTC, GC-Park commented on src/UI/ModalRestaurantDetail.js
> +    };
오 아직 상수화가 필요한 부분이 남아있었군요 ! 적용 하도록 하겠습니다 ! !

2023-03-17 00:33 UTC, GC-Park commented on src/utils/LocalStorage.js
> +}
첫 번째 방법은 변수 개수가 2개가 될 것 같고 세 번째 방법은 지금 방식과 크게 다르지 않은 것 같아 

변수의 개수도 줄일 수 있고 좀 더 utils와 적합한 두 번째 방법으로 변경하였습니다 ! 좋은 제안 감사합니다 !

2023-03-17 04:23 UTC, GC-Park commented on src/UI/RestaurantRegistry.js
> +    });
와우 그루밍의 리뷰 덕분에 불변성에 대해 공부할 수 있었습니다. 
- 값으로 전달받은 객체에 변경을 가하더라도 원본 객체는 변하지 않아야 하는 경우 사용
- Boolean, Number, String, null, undefined, Symbol 타입들은 불변성을 유지하고 Object타입은 변경 가능하다

앞으로도 불변성이 필요한 부분들을 고려해서 프로그래밍을 해야할 것 같습니다 ! 감사합니다 !

2023-03-17 04:30 UTC, GC-Park commented on src/UI/RestaurantRegistry.js
> +  }
오.. 이렇게 배열을 복사할 수 있군요 !  좋은 방법을 배운 것 같습니다 !! 감사합니다 ㅎㅎ

2023-03-17 04:33 UTC, GC-Park commented on src/UI/ModalRestaurantDetail.js
> +      return restaurant;
네 위와 같이 수정하였습니다 ! ! !

2023-03-17 04:42 UTC, GC-Park commented on src/utils/Validation.js
> +};
배열 안의 요소 중 주어진 판별 함수를 적어도 하나라도 통과하면 true를 반환하는 메서드인 array.some을 알 수 있었습니다 !

every를 써도 답은 나오나 한번도 안써도 some을 써보도록 하겠습니다.

감사합니다 !

2023-03-17 04:48 UTC, GC-Park commented on src/utils/LocalStorage.js
> +}
모든 파일에 다시 한번 적용하도록 하겠습니다 !!!

2023-03-17 05:57 UTC, GC-Park commented
안녕하세요 그루밍 !

새로운 미션인 영화 리뷰를 하느라 이제야 점심 뭐 먹지 미션 리뷰 요청을 보냅니다. 늦어서 죄송한 마음입니다 🥲

그루밍의 리뷰를 보고 왜 이것으로 바꾸면 좋은지 등을 고민하고 이해하면서 리뷰를 반영 하였고

 localStorage의 장단점,, array.some, 불변성, 얕은 복사 등을 공부할 수 있었습니다 !!!

그리고 그루밍의 타입 스크립트를 많이 써보라는 조언을 바탕으로 이번 새로운 미션에서는 ts를 위주로 진행하였고 조금은 익숙해졌습니다.

정성스러운 리뷰 정말 감사하고 이번에도 잘 부탁드립니다 !! 

## 에러 해결한 홈페이지 링크
https://gc-park.github.io/javascript-lunch/dist/

2023-03-17 16:49 UTC, ddongule requested changes
안녕하세요 패트릭~!
코드 반영해주신 내용 확인했습니다!
리뷰 대부분 잘 반영해주셨더라구요~😎 고생 많으셨습니당!!!!
다만 몇가지 코멘트를 남겨두었는데, 한번 확인해주시면 좋을 것 같아요!!~!! 
그리구 배포해주신 페이지에 즐겨찾기 아이콘(별 이미지)이 로드가 되지 않더라구요 ⭐️⭐️
요부분도 같이 한번 확인해주시면 좋을 것 같습니다 허헛ㅎㅎ

새로운 미션도 같이 들어가느라 정신없고 바쁘실텐데, 수고가 많으십니다 흐규흐규 
우리 초콤만 더 힘내서 달려봐욧!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
🚗🚗🚗🚗🚗

2023-03-17 16:49 UTC, ddongule commented on src/App.js
> +    } else localStorage.setItem(LOCALSTORAGE_KEY.NUMBER, 0);
그냥 제안사항인데, if에서 `{ }`로 감싸주고있어서 else에도 `{ }`가 있으면 더 통일감 있을 것 같아요!

2023-03-17 16:49 UTC, ddongule commented on src/App.js
> +      [].map(restaurant => {
혹쉬 여기 괄호로 감싸주지 않아도 잘 동작하나용?
```ts
(localRestaurants || []).map( ... ) 
```

2023-03-17 16:49 UTC, ddongule commented on src/UI/ModalRestaurantDetail.js
> +    const restaurant_copy = [...getRestaurantListFromLocalstorage(LOCALSTORAGE_KEY.RESTAURANT)];
여기두 camelCase로 맞춰주는게 좋을 것 같아요!

2023-03-17 16:49 UTC, ddongule commented on src/UI/RestaurantRegistry.js
>      };
요 부분은 아직 반영이 안되었네욤!

2023-03-17 16:49 UTC, ddongule commented on src/domain/RestaurantList.ts
>        return this.list;
요기는 굳이 복사해서 할당하는 이유가 있을까용? 🤔

2023-03-17 16:49 UTC, ddongule commented on src/domain/RestaurantList.ts
>    }
Array.filter는 조건에 맞는 새 배열을 반환하는 메서드여서, 요 상황에는 단순 배열을 순회하는 foreach가 더 알맞아 보이네용! 😉

2023-03-17 16:49 UTC, ddongule commented on src/domain/RestaurantList.ts
>    }
filteredList는 함수 인자로 전달되는 배열인데, 그 배열을 직접 변경해 return하는 건 조금 위험해보여요. fileredList를 직접 수정하지 않는 방법을 사용하는 편이 좋겠어요!

2023-03-17 16:49 UTC, ddongule commented on src/utils/Validation.js
> +};
Array.every 메서드와 Array.some 두가지 모두 사용할 수 있지만, Array.every 메서드는 모든 배열의 요소를 검사해야하는 반면 Array.some 메서드는 해당 조건이 true인 최초의 요소를 발견하면 그 즉시 반복을 중지하고 true를 반환해요. 그렇기 때문에 성능에 차이가 있을 수 있답니다! 
(물론 array 개수가 별로 없으면 유의미한 차이가 없기는 하지만 알아두면 좋을 것 같아서 덧붙여용~!)

2023-03-18 08:42 UTC, GC-Park commented on src/App.js
> +    } else localStorage.setItem(LOCALSTORAGE_KEY.NUMBER, 0);
통일감 중요하다고 생각합니다 ! 적용하도록 하겠습니다 !!!

2023-03-18 09:46 UTC, GC-Park commented on src/App.js
> +      [].map(restaurant => {
네 ! 이 부분은 처음 시작할 때나 새로고침 할 때  localStorage에 즐겨찾기 목록들을 가져와서 localStorage의 레스토랑과 비교 후 같은게 있으면 레스토랑 목록의 즐겨찾기 아이콘을 바꿔주는 역할을 하는 곳입니다 !  

과로로 감싸주지 않아도 잘 동작하는지 확인하기 위해 localStorage를 초기화 한 후 새로고침하니 빈 배열이 들어간걸 확인할 수 있었습니다 !

그리고 이 코드들의 경우 즐겨찾기 기능 구현 중 초기에 만든 것으로 현재는 즐겨찾기 즉시 localStorage 레스토랑에 들어가서 불필요한 코드라고 생각해 지웠습니다 !

2023-03-18 09:48 UTC, GC-Park commented on src/UI/ModalRestaurantDetail.js
> +    const restaurant_copy = [...getRestaurantListFromLocalstorage(LOCALSTORAGE_KEY.RESTAURANT)];
상수 부분을 적용 하다가 해서 변수 이름을 저렇게 설정했네요..  수정하도록 하겠습니다 !!

2023-03-18 09:51 UTC, GC-Park commented on src/UI/RestaurantRegistry.js
>      };
아이고 바로 반영하도록 하겠습니다 !! 감사합니다 !

2023-03-18 09:53 UTC, GC-Park commented on src/domain/RestaurantList.ts
>        return this.list;
아 이부분을 할당한 이유는 저번 리뷰 때 받았던 즐겨찾기 후 이름순/거리순 필터링을 하면 적용되지 않는 에러를 해결하기 위해서였습니다 !

그루밍의 리뷰를 통해 얕은 복사를 공부할 수 있었고 기능 에러를 해결할 때 적용 시킬 수 있었습니다 !

2023-03-18 09:56 UTC, GC-Park commented on src/domain/RestaurantList.ts
>    }
오 같은 생각입니다 !!  앞으로 새 배열 반환과 단순 순회를 확실히 구분하여 쓸 수 있는 연습을 해야할 것 같습니다 ! 감사합니다 !

2023-03-18 09:58 UTC, GC-Park commented on src/domain/RestaurantList.ts
>    }
categoryFilter 메서드에서 선언되던 filteredList를 인자로 전달이 아닌 foodFilter에서 선언되도록 수정하였습니다 !

2023-03-18 10:29 UTC, GC-Park commented
안녕하세요 그루밍 !

빠르게 리뷰 주셔서 감사합니다 ! 제가 놓쳤던 부분들을 알려주셔서 코드를 개선할 수 있었습니다 ㅎㅎ

그리고 "배포해주신 페이지에 즐겨찾기 아이콘(별 이미지)이 로드가 되지 않더라구요 ⭐️⭐️" 코멘트를 보고 바로 확인했는데 문제가 없었고 

혹시나 해서 다른 컴퓨터나 핸드폰으로 들어갔을 때도 다 로드가 됐습니다 !  다시 한번 확인해주시면 감사하겠습니다 !

### 홈페이지 링크
https://gc-park.github.io/javascript-lunch/dist/

2023-03-18 12:33 UTC, ddongule approved these changes
아하 이전에 등록해뒀던 localstorage 문제였나봅니다! 삭제도 안되고 별도 안보여서 데이터를 모두 지우고 다시 실행해보니 잘 동작하네요 :) ㅎㅎ 

(이렇게 떴었어가지구,,.. 허헣 ↓)

<img width="200" alt="image" src="https://user-images.githubusercontent.com/26598561/226106174-75d947f1-afcf-4b1a-a164-4f14d6d118e3.png">

남겨주신 내용 모두 확인했습니다 :) 고생많으셨어요! ㅎㅎ 
앞으로도 화이팅입니당!!!!!!!

2023-03-18 12:33 UTC, merged