[2단계 - 자주 가는 음식점] 푸만능(황준승) 미션 제출합니다.
woowacourse/javascript-lunch pull request #78
Opened 2023-03-11 12:25 UTC by turtle601

## 신경써서 구현한 점

기능이 추가되면서 컴포넌트를 어떻게 하면 재사용성을 높이고 어떻게 하면 코드를 적게 작성할 수 있을까 고민하였습니다!!
공통된 스타일을 추상화(구조, 기능, 스타일 등 비슷한 부분들을 최대한 추상화 클래스에 작성화할려고 노력했습니다)를 만들었어요!!

Modal, Selector, Button, Tab 들을 각각 추상화했습니다!! 
이러한 구조가 제대로 작성 되었는지 궁금합니다.

## 궁금한 점

페어인 요술토끼와 이야기하다 Flux 패턴에 대한 이야기를 한 적이 있습니다. 
flux 패턴의 구조와 저의 코드 구조가 상당히 비슷하다는 생각이 들어서 유조에게 한번 여쭤보고 싶어요!!

> ### Flux 패턴의 정의
Flux는 사용자 입력을 기반으로 Action을 만들고 Action을 Dispatcher에 전달하여 Store(Model)의 데이터를 변경한 뒤 View에 반영하는 단방향의 흐름으로 애플리케이션을 만드는 아키텍처입니다. 
[flux 패턴에 대해 공부한 참고 자료](https://velog.io/@andy0011/Flux-%ED%8C%A8%ED%84%B4%EC%9D%B4%EB%9E%80)

저의 코드에는 Flux 패턴의 dispatcher(모든 데이터의 흐름을 관리하는 중앙 허브)가 actions라는 객체에 존재하고 
그 액션들이 각각의 이벤트에서 실행되면 store을 수정, 다시 view로 렌더링되는 구조입니다. 

그렇다면 제 코드는 과연 Flux 패턴으로 볼 수 있나요?? 그렇지 않다면 어떤 점이 많이 다를까요??

## 아직 구현하지 못한 것들
- 1. 컴포넌트 테스트 코드
- 2. cypress 테스트 코드 
- 3. 각종 UX/UI 경험 고려

> 위의 구현하지 못한 것들이 있지만 이전에 기능 구현 관련 코드 먼저 리뷰 받고 싶어서 리뷰요청 보내요 `✨유조`!!

2023-03-12 09:53 UTC, yujo11 requested changes
안녕하세요~ 푸만능~

> Modal, Selector, Button, Tab 들을 각각 추상화했습니다!!
이러한 구조가 제대로 작성 되었는지 궁금합니다.

이 부분은 일종의 추상 클래스를 구현하려고 하신거 같은데요. 

각 클래스를 보면 꽤 많은 로직을 포함하고 있는거 같아요. `Button` Class를 보게 되면 `closeModal` 같은 메서드를 가지고 있는데요. 이 `closeModal`같은 경우는 일반적으로 사용되는 속성이 아니라 특정 Button에서만 쓰일거 같아요.

추상화를 위해서라면 `closeModal` 같은 메서드보다는 `onClick`같은 메서드를 정의해두는게 좋을거 같아요.

그리고 추가로 추상 클래스의 구현이라면 typescript의 [abstract클래스](https://www.typescriptlang.org/docs/handbook/2/classes.html#abstract-classes-and-members)를 사용해보셔도 좋을거 같아요.

>그렇다면 제 코드는 과연 Flux 패턴으로 볼 수 있나요?? 그렇지 않다면 어떤 점이 많이 다를까요??

dispatcher가 별도로 구현되어 있지는 않지만 구현 방식만으로 보면 Flux 패턴과 유사하게 보입니다. 

dispatcher를 별도로 분리해보셔도 좋을거 같아요.

Flux 패턴과 관련하여 [여기](https://facebook.github.io/flux/)도 참고해보시면 Flux 패턴을 이해하시는데 더 도움이 될거 같네요!

---

step2 진행하느라 고생 많으셨습니다 푸만능~~ 코멘트 남긴 내용들 확인 부탁드릴게요~~ 👍 👍 👍

2023-03-13 01:40 UTC, turtle601 commented on src/domain/Restaurants.ts
> +  }
이렇게 작성한 개인적인 이유는 javascript가 못 미덥다는 이유가 가장 큰 것 같아요!!
restaurant.favorite 속성이 `boolean`이 라는 것을 알고 있지만 한 번도 !!를 두어서 확실하게 하려고 했습니다.

2023-03-13 01:50 UTC, turtle601 commented on src/utils/querySelector.ts
> +};
> 그런데 여기에서 Error를 Throw하고 있지만 사용하는 곳에서는 Catch를 하지 않고 있네요.

제가 생각하는 `catch`구문을 사용하는 이유는 에러가 발생했을 시 사용자에게 어떤 문제가 발생했는지 알려주기 위해 사용한다라고 인지하고 있었습니다.

하지만 위의 코드에서 제가 `throw` 에러를 처리한 이유는 해당 DOMList가 `HTMLElement []`로 타입을 지정하기 위해서 에러문을 사용하였습니다. 

실제 구현이 완성되는 앱에서는 `dom` 에러가 나지 않는다고 생각하기 때문에 굳이 `catch` 구문을 사용할 이유가 있을지 의문입니다. 

`✨유조`의 생각은 어떠신가요??

2023-03-13 02:02 UTC, turtle601 commented on src/view/components/Tab/FavoritTab.ts
> +  }
> dom 접근과 성능에 대한 추가적인 질문이 있습니다!!

모달을 구현할 시 제가 생각한 두 가지 방식은 다음과 같습니다.
1. `isModal`이라는 state의 값(true/false)에 따라 html을 렌더링 하는 방식
2. `css(display: none)`을 통해서 모달 show 여부를 조절하는 방식

성능에 대한 푸만능의 생각

1번 성능
- `isModal: true`: 모달의 태그들을 모두 가져온다. 해당 모달의 스타일에 대한 내용을 리플로우, 리페인트 작업을 거친다. 
- `isModal: false`: 아무런 스타일도 적용되지 않는다. (실제 웹에서 흔적도 없다.)
 
2번 성능
- 실제 웹에서는 흔적이 남지만 `display: none`, `display: block` 을 반복적으로 실행하면서 모달을 보여줄 때와 보여주지 않을 때 모두 리플로우, 리페인트 작업을 한다. 

__`✨유조`는 어떤 방식으로 모달을 주로 구현하며 어떤 방식이 더 성능이 좋다고 생각하시나요??__

2023-03-13 02:07 UTC, turtle601 commented on src/view/components/Tab/abstract/Tab.ts
> +    });
`setEvent()` 메서드 안에는 각각의 하위 컴포넌트에서 동일하게 사용하고 있는 

```typescript
  if(e.target instanceof HTMLLIElement)
```
코드를 공유하고 있기 때문에 `setEvent()`와 하위 컴포넌트에 자신만의 이벤트를 설정할 수 있는 `addEvent()`를 분리하였습니다.

2023-03-13 03:11 UTC, turtle601 commented on src/type/common.ts
> +  id?: number;
> id가 있을 수도 있고, 없을 수도 있다는 상황 자체가 조금 어색하게 느껴지는데요. 이렇게 타입을 정의하신 이유가 있을까요?

구현 상 편의를 위해서 일단은 옵셔널로 지정을 했습니다.

2단계 구현 사항에 `음식점 삭제`와 `특정 음식점 클릭`이라는 기능이 추가되면서 특정 음식점을 구분할 수 있는 데이터 정보가 필요했고 그것을 구현하기 위해 음식점이라는 속성에 `id`값을 넣었습니다. 

```typescript

  addRestaurant(restaurant: Restaurant) {
    this.#restaurants.push({ id: this.#id++, ...restaurant });
  }

```

기존 코드인 `addRestaurant(restaurant:Restaurant)` 유지하면서 id 값을 추가로 넣고 싶어서 `id?: number` 로 지정했습니다!!

> 실제로 구현하면서도 id값은 꼭 있어야되는거 아니야?? 라고 생각을 했습니다. `id:number` 로 바꿀 수 있도록 수정해보겠습니다.

2023-03-13 05:32 UTC, turtle601 commented on src/domain/Restaurants.ts
> +  }
> 수정했습니다!! 👍👍

2023-03-13 05:32 UTC, turtle601 commented on src/domain/Restaurants.ts
> +  }
> 수정했습니다!! 👍👍

2023-03-13 05:40 UTC, turtle601 commented on src/type/common.ts
> +  id?: number;
> Omit이라는 Utility Types를 사용해서 해결했습니다!!

2023-03-13 05:44 UTC, turtle601 commented
## 유조의 피드백 적용기
- [ ] 이벤트 위임 생각해보기
- [ ] typescript abstract 적용해보기
- [ ] 상위 태그에서 스타일 변경하기

2023-03-13 06:10 UTC, turtle601 commented on src/view/components/RestaurantItem.ts
> +      if (e.target instanceof HTMLImageElement && e.target.closest('.star')) {
> closest()의 경우 DOM 의 변경에 굉장히 취약할 수 있는데요. 

음... closest가 DOM의 변경에 취약하다는 말이 제 입장에서는 잘 와닿지 않는 거 같아요!!
이벤트가 발생한 부모 태그에 여러 개의 class가 있을 수 있어서 변경에 취약하다고 말씀하시는 건가요?? 

__푸만능이 생각한 예시__
```
<div class="star">
  <div class="star">
    <div class="star">

...
```

> `이벤트 위임`과 관련 키워드인 `이벤트 버블링`에 대해 학습해보고 수정해보았습니다!!

__공부한 자료__

[이벤트 버블링과 캡처링](https://ko.javascript.info/bubbling-and-capturing)
[이벤트 위임](https://ko.javascript.info/event-delegation)

2023-03-13 07:12 UTC, turtle601 commented on src/view/components/Tab/abstract/Tab.ts
> +  }
위의 코드의 경우 탭 각각에 대해서 스타일을 초기화, 클릭한 탭에서만 스타일을 부여해야 되기 때문에 다음과 같이 작성할 수 밖에 없을 거 같아요... (머리를 아무리 굴려봐도 이 방법밖에는 모르겠네요 ㅎㅎ)

2023-03-13 10:24 UTC, yujo11 commented on src/domain/Restaurants.ts
> +  }
>이렇게 작성한 개인적인 이유는 javascript가 못 미덥다는 이유가 가장 큰 것 같아요!!

이 내용에 대해서는 공감할 수 있지만 그렇다고 해도 이 부분만 형변환을 해주는거는 조금 이해하기 어려웠었네요

Javascript의 타입이 불안하다면 TypeScript외에도 Runtime Validation이 가능한 방법들을 찾아보셔도 좋을거 같아요!

2023-03-13 10:28 UTC, yujo11 commented on src/utils/querySelector.ts
> +};
>하지만 위의 코드에서 제가 throw 에러를 처리한 이유는 해당 DOMList가 HTMLElement []로 타입을 지정하기 위해서 에러문을 사용하였습니다.
>실제 구현이 완성되는 앱에서는 dom 에러가 나지 않는다고 생각하기 때문에 굳이 catch 구문을 사용할 이유가 있을지 의문입니다.


타입을 좁혀나가는건 좋지만 그것만을 위해 Error를 Throw하는 부분은 적절하지 않게 느껴져요. 

100% 안전하다는 생각이 들었고, 실제로 필요없는 구문이라면 Error를 Throw하는 방법 말고 `as`를 통해 assertion 하는 방법이나 다른 방법들로도 충분히 처리가 가능하럭 같은데요. 

Trhow한 Error 객체를 catch 하지않으면 에러 발생 시점에서 프로그램이 멈춰버리기 때문에 이런 식의 throw 활용은 좋지 못해보이네요

2023-03-13 10:32 UTC, yujo11 commented on src/view/components/Tab/FavoritTab.ts
> +  }
1번 방식에 대해서는 푸만능이 설명해준 방식을 잘 이해하지 못 헀네요

저는 개인적으로 CSS 속성을 통해 관리하는 방법을 선호합니다!

추가적으로 `display: none` 과 `visibility: hidden`의 차이에 대해서도 알아보시면 좋을거 같네요!

2023-03-13 10:34 UTC, yujo11 commented on src/view/components/Tab/abstract/Tab.ts
> +    if (!eventTarget) throw new Error('[ERROR]');
>실제 구현이 완성되는 앱에서는 굳이 사용자가 오버라이딩 에러를 알아야하나?? 라는 생각이 들어서 catch 구문을 사용할 이유가 있을지 의문입니다.

"사용자가 오버라이딩 에러를 알아야하나??"라는 고민에는 동의하지만 catch하지 않으면 에러가 Throw 되는 시점에서 앱이 멈춰버릴텐데요. 이것이 더욱 안 좋은 사용자 경험이라고 생각합니다

2023-03-13 10:38 UTC, yujo11 commented on src/view/components/RestaurantItem.ts
> +      if (e.target instanceof HTMLImageElement && e.target.closest('.star')) {
푸만능이 언급한 케이스도 있겠지만 HTML 요소의 render 방식이 달라지거나 하는 경우에도 closest()가 찾는 타겟이 달라질 수 있어요.

공부하고 적용하신 내용 멋지네요! 👍 👍 👍

2023-03-13 10:40 UTC, yujo11 approved these changes
안녕하세요 푸만능~

벌써 이번 미션의 마지막 리뷰네요! 이전 코멘트로 남겨주신 질문들에는 답변을 달았으니 확인 부탁드릴게요!

미션 기간 동안 코멘트를 많이 주고 받았는데요. 제가 남긴 코멘트가 푸만능에게 도움이 되는 부분들이 있었다니 다행이네요 ㅎㅎ

적극적으로 질문하고 학습하고 공유하는 푸만능의 모습에 저도 리뷰를 하면서 배워가는 점들도 많았네요!

이제 레벨 1 마지막 미션을 진행하실텐데 마지막 미션도, 남은 우테코 과정도 지금처럼 적극적인 자세로 학습해나가시면 더욱 더 성장하실 수 있을거라는 생각이 드네요!

그동안 고생 많으셨습니다~~ 앞으로의 과정도 응원하겠습니다~~ 👍 👍 👍

2023-03-13 10:40 UTC, merged